/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 4.8.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QStatusBar>
#include <QtGui/QTabWidget>
#include <QtGui/QWidget>
#include "QELabel.h"
#include "QELineEdit.h"
#include "QEPushButton.h"
#include "QESlider.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionQuit;
    QWidget *centralwidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    QELineEdit *qelineedit;
    QELineEdit *qelineedit_2;
    QELineEdit *qelineedit_3;
    QELineEdit *qelineedit_4;
    QELineEdit *qelineedit_9;
    QELineEdit *qelineedit_10;
    QELineEdit *qelineedit_39;
    QELineEdit *qelineedit_40;
    QESlider *qeslider;
    QESlider *qeslider_2;
    QESlider *qeslider_3;
    QESlider *qeslider_4;
    QLabel *label;
    QLabel *label_2;
    QELabel *qelabel;
    QLabel *label_3;
    QEPushButton *qepushbutton;
    QEPushButton *qepushbutton_2;
    QWidget *tab_3;
    QELineEdit *qelineedit_11;
    QELabel *qelabel_31;
    QELineEdit *qelineedit_12;
    QELabel *qelabel_32;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QELineEdit *qelineedit_13;
    QELineEdit *qelineedit_14;
    QELabel *qelabel_33;
    QELabel *qelabel_34;
    QELineEdit *qelineedit_15;
    QELineEdit *qelineedit_16;
    QELabel *qelabel_35;
    QELabel *qelabel_36;
    QELineEdit *qelineedit_17;
    QELineEdit *qelineedit_18;
    QELabel *qelabel_37;
    QELabel *qelabel_38;
    QWidget *tab_4;
    QELabel *qelabel_39;
    QELabel *qelabel_40;
    QELabel *qelabel_41;
    QELabel *qelabel_42;
    QELabel *qelabel_43;
    QELabel *qelabel_44;
    QELabel *qelabel_45;
    QELabel *qelabel_46;
    QELabel *qelabel_47;
    QELabel *qelabel_48;
    QELabel *qelabel_49;
    QELabel *qelabel_50;
    QELabel *qelabel_51;
    QELabel *qelabel_52;
    QELabel *qelabel_53;
    QELabel *qelabel_54;
    QELabel *qelabel_55;
    QELabel *qelabel_56;
    QELineEdit *qelineedit_19;
    QELineEdit *qelineedit_20;
    QELineEdit *qelineedit_21;
    QELineEdit *qelineedit_22;
    QELineEdit *qelineedit_23;
    QELineEdit *qelineedit_24;
    QELabel *qelabel_57;
    QELabel *qelabel_58;
    QELabel *qelabel_59;
    QELabel *qelabel_60;
    QELabel *qelabel_61;
    QELabel *qelabel_62;
    QWidget *tab_2;
    QLabel *label_9;
    QMenuBar *menubar;
    QMenu *menuFile;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(445, 379);
        actionQuit = new QAction(MainWindow);
        actionQuit->setObjectName(QString::fromUtf8("actionQuit"));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        tabWidget = new QTabWidget(centralwidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(-4, 0, 421, 313));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        qelineedit = new QELineEdit(tab);
        qelineedit->setObjectName(QString::fromUtf8("qelineedit"));
        qelineedit->setGeometry(QRect(52, 128, 85, 21));
        qelineedit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_2 = new QELineEdit(tab);
        qelineedit_2->setObjectName(QString::fromUtf8("qelineedit_2"));
        qelineedit_2->setGeometry(QRect(52, 152, 85, 21));
        qelineedit_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_3 = new QELineEdit(tab);
        qelineedit_3->setObjectName(QString::fromUtf8("qelineedit_3"));
        qelineedit_3->setGeometry(QRect(52, 176, 85, 21));
        qelineedit_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_4 = new QELineEdit(tab);
        qelineedit_4->setObjectName(QString::fromUtf8("qelineedit_4"));
        qelineedit_4->setGeometry(QRect(52, 200, 85, 21));
        qelineedit_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_9 = new QELineEdit(tab);
        qelineedit_9->setObjectName(QString::fromUtf8("qelineedit_9"));
        qelineedit_9->setGeometry(QRect(140, 128, 53, 21));
        qelineedit_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_10 = new QELineEdit(tab);
        qelineedit_10->setObjectName(QString::fromUtf8("qelineedit_10"));
        qelineedit_10->setGeometry(QRect(140, 152, 53, 21));
        qelineedit_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_39 = new QELineEdit(tab);
        qelineedit_39->setObjectName(QString::fromUtf8("qelineedit_39"));
        qelineedit_39->setGeometry(QRect(140, 176, 53, 21));
        qelineedit_39->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_40 = new QELineEdit(tab);
        qelineedit_40->setObjectName(QString::fromUtf8("qelineedit_40"));
        qelineedit_40->setGeometry(QRect(140, 200, 53, 21));
        qelineedit_40->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qeslider = new QESlider(tab);
        qeslider->setObjectName(QString::fromUtf8("qeslider"));
        qeslider->setGeometry(QRect(196, 132, 113, 17));
        qeslider->setOrientation(Qt::Horizontal);
        qeslider_2 = new QESlider(tab);
        qeslider_2->setObjectName(QString::fromUtf8("qeslider_2"));
        qeslider_2->setGeometry(QRect(196, 156, 113, 17));
        qeslider_2->setOrientation(Qt::Horizontal);
        qeslider_3 = new QESlider(tab);
        qeslider_3->setObjectName(QString::fromUtf8("qeslider_3"));
        qeslider_3->setGeometry(QRect(196, 180, 113, 17));
        qeslider_3->setOrientation(Qt::Horizontal);
        qeslider_4 = new QESlider(tab);
        qeslider_4->setObjectName(QString::fromUtf8("qeslider_4"));
        qeslider_4->setGeometry(QRect(196, 204, 113, 17));
        qeslider_4->setOrientation(Qt::Horizontal);
        label = new QLabel(tab);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(12, 12, 337, 33));
        QFont font;
        font.setPointSize(12);
        font.setBold(true);
        font.setWeight(75);
        label->setFont(font);
        label_2 = new QLabel(tab);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(12, 52, 165, 25));
        label_2->setFont(font);
        qelabel = new QELabel(tab);
        qelabel->setObjectName(QString::fromUtf8("qelabel"));
        qelabel->setGeometry(QRect(176, 56, 69, 17));
        qelabel->setFont(font);
        label_3 = new QLabel(tab);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(248, 52, 101, 25));
        label_3->setFont(font);
        qepushbutton = new QEPushButton(tab);
        qepushbutton->setObjectName(QString::fromUtf8("qepushbutton"));
        qepushbutton->setGeometry(QRect(320, 128, 45, 21));
        qepushbutton->setCheckable(true);
        qepushbutton->setChecked(false);
        qepushbutton->setSubscribe(true);
        qepushbutton->setDisplayAlarmState(false);
        qepushbutton->setAddUnits(false);
        qepushbutton->setProperty("updateOption", QVariant(QEPushButton::Text));
        qepushbutton->setWriteOnPress(true);
        qepushbutton->setWriteOnRelease(true);
        qepushbutton->setWriteOnClick(false);
        qepushbutton_2 = new QEPushButton(tab);
        qepushbutton_2->setObjectName(QString::fromUtf8("qepushbutton_2"));
        qepushbutton_2->setGeometry(QRect(320, 152, 45, 21));
        qepushbutton_2->setCheckable(true);
        qepushbutton_2->setChecked(false);
        qepushbutton_2->setSubscribe(true);
        qepushbutton_2->setDisplayAlarmState(false);
        qepushbutton_2->setAddUnits(false);
        tabWidget->addTab(tab, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        qelineedit_11 = new QELineEdit(tab_3);
        qelineedit_11->setObjectName(QString::fromUtf8("qelineedit_11"));
        qelineedit_11->setGeometry(QRect(16, 24, 127, 21));
        qelineedit_11->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_31 = new QELabel(tab_3);
        qelabel_31->setObjectName(QString::fromUtf8("qelabel_31"));
        qelabel_31->setGeometry(QRect(160, 24, 41, 21));
        qelabel_31->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_31->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_31->setRadix(16u);
        qelineedit_12 = new QELineEdit(tab_3);
        qelineedit_12->setObjectName(QString::fromUtf8("qelineedit_12"));
        qelineedit_12->setGeometry(QRect(216, 24, 61, 21));
        qelabel_32 = new QELabel(tab_3);
        qelabel_32->setObjectName(QString::fromUtf8("qelabel_32"));
        qelabel_32->setGeometry(QRect(296, 24, 53, 21));
        qelabel_32->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_32->setPrecision(2);
        qelabel_32->setAddUnits(false);
        qelabel_32->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_32->setRadix(16u);
        label_5 = new QLabel(tab_3);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(56, 8, 56, 15));
        label_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_6 = new QLabel(tab_3);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(152, 8, 49, 16));
        label_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_7 = new QLabel(tab_3);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(224, 4, 41, 16));
        label_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_8 = new QLabel(tab_3);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(304, 4, 41, 16));
        label_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_13 = new QELineEdit(tab_3);
        qelineedit_13->setObjectName(QString::fromUtf8("qelineedit_13"));
        qelineedit_13->setGeometry(QRect(216, 48, 61, 21));
        qelineedit_14 = new QELineEdit(tab_3);
        qelineedit_14->setObjectName(QString::fromUtf8("qelineedit_14"));
        qelineedit_14->setGeometry(QRect(16, 48, 127, 21));
        qelineedit_14->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_33 = new QELabel(tab_3);
        qelabel_33->setObjectName(QString::fromUtf8("qelabel_33"));
        qelabel_33->setGeometry(QRect(296, 48, 53, 21));
        qelabel_33->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_33->setPrecision(2);
        qelabel_33->setAddUnits(false);
        qelabel_33->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_33->setRadix(16u);
        qelabel_34 = new QELabel(tab_3);
        qelabel_34->setObjectName(QString::fromUtf8("qelabel_34"));
        qelabel_34->setGeometry(QRect(160, 48, 41, 21));
        qelabel_34->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_34->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_34->setRadix(16u);
        qelineedit_15 = new QELineEdit(tab_3);
        qelineedit_15->setObjectName(QString::fromUtf8("qelineedit_15"));
        qelineedit_15->setGeometry(QRect(216, 72, 61, 21));
        qelineedit_16 = new QELineEdit(tab_3);
        qelineedit_16->setObjectName(QString::fromUtf8("qelineedit_16"));
        qelineedit_16->setGeometry(QRect(16, 72, 127, 21));
        qelineedit_16->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_35 = new QELabel(tab_3);
        qelabel_35->setObjectName(QString::fromUtf8("qelabel_35"));
        qelabel_35->setGeometry(QRect(296, 72, 53, 21));
        qelabel_35->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_35->setPrecision(2);
        qelabel_35->setAddUnits(false);
        qelabel_35->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_35->setRadix(16u);
        qelabel_36 = new QELabel(tab_3);
        qelabel_36->setObjectName(QString::fromUtf8("qelabel_36"));
        qelabel_36->setGeometry(QRect(160, 72, 41, 21));
        qelabel_36->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_36->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_36->setRadix(16u);
        qelineedit_17 = new QELineEdit(tab_3);
        qelineedit_17->setObjectName(QString::fromUtf8("qelineedit_17"));
        qelineedit_17->setGeometry(QRect(216, 96, 61, 21));
        qelineedit_18 = new QELineEdit(tab_3);
        qelineedit_18->setObjectName(QString::fromUtf8("qelineedit_18"));
        qelineedit_18->setGeometry(QRect(16, 96, 127, 21));
        qelineedit_18->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_37 = new QELabel(tab_3);
        qelabel_37->setObjectName(QString::fromUtf8("qelabel_37"));
        qelabel_37->setGeometry(QRect(296, 96, 53, 21));
        qelabel_37->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_37->setPrecision(2);
        qelabel_37->setAddUnits(false);
        qelabel_37->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_37->setRadix(16u);
        qelabel_38 = new QELabel(tab_3);
        qelabel_38->setObjectName(QString::fromUtf8("qelabel_38"));
        qelabel_38->setGeometry(QRect(160, 96, 41, 21));
        qelabel_38->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_38->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_38->setRadix(16u);
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        qelabel_39 = new QELabel(tab_4);
        qelabel_39->setObjectName(QString::fromUtf8("qelabel_39"));
        qelabel_39->setGeometry(QRect(16, 10, 149, 16));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Monospace"));
        font1.setPointSize(10);
        font1.setBold(true);
        font1.setWeight(75);
        qelabel_39->setFont(font1);
        qelabel_39->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_40 = new QELabel(tab_4);
        qelabel_40->setObjectName(QString::fromUtf8("qelabel_40"));
        qelabel_40->setGeometry(QRect(172, 10, 61, 16));
        qelabel_40->setFont(font1);
        qelabel_40->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        qelabel_41 = new QELabel(tab_4);
        qelabel_41->setObjectName(QString::fromUtf8("qelabel_41"));
        qelabel_41->setGeometry(QRect(16, 28, 149, 16));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Monospace"));
        font2.setPointSize(9);
        font2.setBold(false);
        font2.setWeight(50);
        qelabel_41->setFont(font2);
        qelabel_41->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_42 = new QELabel(tab_4);
        qelabel_42->setObjectName(QString::fromUtf8("qelabel_42"));
        qelabel_42->setGeometry(QRect(16, 44, 149, 16));
        qelabel_42->setFont(font2);
        qelabel_42->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_43 = new QELabel(tab_4);
        qelabel_43->setObjectName(QString::fromUtf8("qelabel_43"));
        qelabel_43->setGeometry(QRect(16, 60, 149, 16));
        qelabel_43->setFont(font2);
        qelabel_43->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_44 = new QELabel(tab_4);
        qelabel_44->setObjectName(QString::fromUtf8("qelabel_44"));
        qelabel_44->setGeometry(QRect(16, 80, 149, 16));
        qelabel_44->setFont(font2);
        qelabel_44->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_45 = new QELabel(tab_4);
        qelabel_45->setObjectName(QString::fromUtf8("qelabel_45"));
        qelabel_45->setGeometry(QRect(16, 96, 149, 16));
        qelabel_45->setFont(font2);
        qelabel_45->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_46 = new QELabel(tab_4);
        qelabel_46->setObjectName(QString::fromUtf8("qelabel_46"));
        qelabel_46->setGeometry(QRect(16, 112, 149, 16));
        qelabel_46->setFont(font2);
        qelabel_46->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_47 = new QELabel(tab_4);
        qelabel_47->setObjectName(QString::fromUtf8("qelabel_47"));
        qelabel_47->setGeometry(QRect(16, 128, 149, 16));
        qelabel_47->setFont(font2);
        qelabel_47->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_48 = new QELabel(tab_4);
        qelabel_48->setObjectName(QString::fromUtf8("qelabel_48"));
        qelabel_48->setGeometry(QRect(16, 144, 149, 16));
        qelabel_48->setFont(font2);
        qelabel_48->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_49 = new QELabel(tab_4);
        qelabel_49->setObjectName(QString::fromUtf8("qelabel_49"));
        qelabel_49->setGeometry(QRect(172, 28, 53, 16));
        qelabel_49->setFont(font2);
        qelabel_49->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        qelabel_49->setUseDbPrecision(false);
        qelabel_49->setAddUnits(false);
        qelabel_49->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_49->setRadix(16u);
        qelabel_50 = new QELabel(tab_4);
        qelabel_50->setObjectName(QString::fromUtf8("qelabel_50"));
        qelabel_50->setGeometry(QRect(172, 44, 53, 16));
        qelabel_50->setFont(font2);
        qelabel_50->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        qelabel_50->setUseDbPrecision(false);
        qelabel_50->setAddUnits(false);
        qelabel_50->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_50->setRadix(16u);
        qelabel_51 = new QELabel(tab_4);
        qelabel_51->setObjectName(QString::fromUtf8("qelabel_51"));
        qelabel_51->setGeometry(QRect(172, 60, 53, 16));
        qelabel_51->setFont(font2);
        qelabel_51->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        qelabel_51->setUseDbPrecision(false);
        qelabel_51->setAddUnits(false);
        qelabel_51->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_51->setRadix(16u);
        qelabel_52 = new QELabel(tab_4);
        qelabel_52->setObjectName(QString::fromUtf8("qelabel_52"));
        qelabel_52->setGeometry(QRect(172, 80, 53, 16));
        qelabel_52->setFont(font2);
        qelabel_52->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        qelabel_52->setUseDbPrecision(false);
        qelabel_52->setAddUnits(false);
        qelabel_52->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_52->setRadix(16u);
        qelabel_53 = new QELabel(tab_4);
        qelabel_53->setObjectName(QString::fromUtf8("qelabel_53"));
        qelabel_53->setGeometry(QRect(172, 96, 53, 16));
        qelabel_53->setFont(font2);
        qelabel_53->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        qelabel_53->setUseDbPrecision(false);
        qelabel_53->setAddUnits(false);
        qelabel_53->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_53->setRadix(16u);
        qelabel_54 = new QELabel(tab_4);
        qelabel_54->setObjectName(QString::fromUtf8("qelabel_54"));
        qelabel_54->setGeometry(QRect(172, 112, 53, 16));
        qelabel_54->setFont(font2);
        qelabel_54->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        qelabel_54->setUseDbPrecision(false);
        qelabel_54->setAddUnits(false);
        qelabel_54->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_54->setRadix(16u);
        qelabel_55 = new QELabel(tab_4);
        qelabel_55->setObjectName(QString::fromUtf8("qelabel_55"));
        qelabel_55->setGeometry(QRect(172, 128, 53, 16));
        qelabel_55->setFont(font2);
        qelabel_55->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        qelabel_55->setUseDbPrecision(false);
        qelabel_55->setAddUnits(false);
        qelabel_55->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_55->setRadix(16u);
        qelabel_56 = new QELabel(tab_4);
        qelabel_56->setObjectName(QString::fromUtf8("qelabel_56"));
        qelabel_56->setGeometry(QRect(172, 144, 53, 16));
        qelabel_56->setFont(font2);
        qelabel_56->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        qelabel_56->setUseDbPrecision(false);
        qelabel_56->setAddUnits(false);
        qelabel_56->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_56->setRadix(16u);
        qelineedit_19 = new QELineEdit(tab_4);
        qelineedit_19->setObjectName(QString::fromUtf8("qelineedit_19"));
        qelineedit_19->setGeometry(QRect(168, 160, 73, 20));
        qelineedit_19->setAddUnits(false);
        qelineedit_19->setRadix(16u);
        qelineedit_20 = new QELineEdit(tab_4);
        qelineedit_20->setObjectName(QString::fromUtf8("qelineedit_20"));
        qelineedit_20->setEnabled(false);
        qelineedit_20->setGeometry(QRect(168, 180, 73, 20));
        qelineedit_20->setRadix(16u);
        qelineedit_21 = new QELineEdit(tab_4);
        qelineedit_21->setObjectName(QString::fromUtf8("qelineedit_21"));
        qelineedit_21->setEnabled(false);
        qelineedit_21->setGeometry(QRect(168, 200, 73, 20));
        qelineedit_21->setRadix(10u);
        qelineedit_22 = new QELineEdit(tab_4);
        qelineedit_22->setObjectName(QString::fromUtf8("qelineedit_22"));
        qelineedit_22->setEnabled(false);
        qelineedit_22->setGeometry(QRect(168, 220, 73, 20));
        qelineedit_22->setRadix(10u);
        qelineedit_23 = new QELineEdit(tab_4);
        qelineedit_23->setObjectName(QString::fromUtf8("qelineedit_23"));
        qelineedit_23->setEnabled(false);
        qelineedit_23->setGeometry(QRect(168, 240, 73, 20));
        qelineedit_23->setRadix(10u);
        qelineedit_24 = new QELineEdit(tab_4);
        qelineedit_24->setObjectName(QString::fromUtf8("qelineedit_24"));
        qelineedit_24->setEnabled(false);
        qelineedit_24->setGeometry(QRect(168, 260, 73, 20));
        qelineedit_24->setRadix(10u);
        qelabel_57 = new QELabel(tab_4);
        qelabel_57->setObjectName(QString::fromUtf8("qelabel_57"));
        qelabel_57->setGeometry(QRect(16, 164, 149, 16));
        qelabel_57->setFont(font2);
        qelabel_57->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_58 = new QELabel(tab_4);
        qelabel_58->setObjectName(QString::fromUtf8("qelabel_58"));
        qelabel_58->setGeometry(QRect(16, 184, 149, 16));
        qelabel_58->setFont(font2);
        qelabel_58->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_59 = new QELabel(tab_4);
        qelabel_59->setObjectName(QString::fromUtf8("qelabel_59"));
        qelabel_59->setGeometry(QRect(16, 204, 149, 16));
        qelabel_59->setFont(font2);
        qelabel_59->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_60 = new QELabel(tab_4);
        qelabel_60->setObjectName(QString::fromUtf8("qelabel_60"));
        qelabel_60->setGeometry(QRect(16, 224, 149, 16));
        qelabel_60->setFont(font2);
        qelabel_60->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_61 = new QELabel(tab_4);
        qelabel_61->setObjectName(QString::fromUtf8("qelabel_61"));
        qelabel_61->setGeometry(QRect(16, 244, 149, 16));
        qelabel_61->setFont(font2);
        qelabel_61->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_62 = new QELabel(tab_4);
        qelabel_62->setObjectName(QString::fromUtf8("qelabel_62"));
        qelabel_62->setGeometry(QRect(16, 264, 149, 16));
        qelabel_62->setFont(font2);
        qelabel_62->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tabWidget->addTab(tab_4, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        label_9 = new QLabel(tab_2);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(28, 16, 229, 16));
        label_9->setFont(font1);
        label_9->setAlignment(Qt::AlignCenter);
        tabWidget->addTab(tab_2, QString());
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 445, 20));
        menuFile = new QMenu(menubar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        menubar->addAction(menuFile->menuAction());
        menuFile->addAction(actionQuit);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
        actionQuit->setText(QApplication::translate("MainWindow", "Quit", 0, QApplication::UnicodeUTF8));
        qelineedit->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:4132-4:PC:CH1.DESC", 0, QApplication::UnicodeUTF8)));
        qelineedit->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelineedit_2->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:4132-4:PC:CH2.DESC", 0, QApplication::UnicodeUTF8)));
        qelineedit_2->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelineedit_3->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:4132-4:PC:CH3.DESC", 0, QApplication::UnicodeUTF8)));
        qelineedit_3->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelineedit_4->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:4132-4:PC:CH4.DESC", 0, QApplication::UnicodeUTF8)));
        qelineedit_4->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelineedit_9->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:PC:4132-4:PC:CH1", 0, QApplication::UnicodeUTF8)));
        qelineedit_9->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelineedit_10->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:PC:4132-4:PC:CH2", 0, QApplication::UnicodeUTF8)));
        qelineedit_10->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelineedit_39->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:PC:4132-4:PC:CH3", 0, QApplication::UnicodeUTF8)));
        qelineedit_39->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelineedit_40->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:PC:4132-4:PC:CH4", 0, QApplication::UnicodeUTF8)));
        qelineedit_40->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qeslider->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:PC:4132-4:PC:CH1", 0, QApplication::UnicodeUTF8)));
        qeslider->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qeslider_2->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:PC:4132-4:PC:CH2", 0, QApplication::UnicodeUTF8)));
        qeslider_2->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qeslider_3->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:PC:4132-4:PC:CH3", 0, QApplication::UnicodeUTF8)));
        qeslider_3->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qeslider_4->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:PC:4132-4:PC:CH4", 0, QApplication::UnicodeUTF8)));
        qeslider_4->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        label->setText(QApplication::translate("MainWindow", "ESA BeamPosition Screen controls", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("MainWindow", "Main Switch is in:", 0, QApplication::UnicodeUTF8));
        qelabel->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):MBBI:REM:LOC", 0, QApplication::UnicodeUTF8)));
        qelabel->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        label_3->setText(QApplication::translate("MainWindow", "position", 0, QApplication::UnicodeUTF8));
        qepushbutton->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:2408-4:BIT1", 0, QApplication::UnicodeUTF8)));
        qepushbutton->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qepushbutton->setPressText(QApplication::translate("MainWindow", "1", 0, QApplication::UnicodeUTF8));
        qepushbutton->setReleaseText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        qepushbutton_2->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:2408-4:BIT2", 0, QApplication::UnicodeUTF8)));
        qepushbutton_2->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_2->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Controls", 0, QApplication::UnicodeUTF8));
        qelineedit_11->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AI:4132-4:PC:CH1.DESC", 0, QApplication::UnicodeUTF8)));
        qelineedit_11->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelabel_31->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:4132-4:SBYTE1", 0, QApplication::UnicodeUTF8)));
        qelabel_31->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelineedit_12->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:4132-4:PC:CH1", 0, QApplication::UnicodeUTF8)));
        qelineedit_12->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelabel_32->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:4132-4:PC:CH1.RVAL", 0, QApplication::UnicodeUTF8)));
        qelabel_32->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        label_5->setText(QApplication::translate("MainWindow", "channel", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("MainWindow", "sByte", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("MainWindow", "value", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("MainWindow", "RVAL", 0, QApplication::UnicodeUTF8));
        qelineedit_13->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:4132-4:PC:CH2", 0, QApplication::UnicodeUTF8)));
        qelineedit_13->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelineedit_14->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AI:4132-4:PC:CH2.DESC", 0, QApplication::UnicodeUTF8)));
        qelineedit_14->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelabel_33->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:4132-4:PC:CH2.RVAL", 0, QApplication::UnicodeUTF8)));
        qelabel_33->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelabel_34->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:4132-4:SBYTE2", 0, QApplication::UnicodeUTF8)));
        qelabel_34->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelineedit_15->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:4132-4:PC:CH3", 0, QApplication::UnicodeUTF8)));
        qelineedit_15->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelineedit_16->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AI:4132-4:PC:CH3.DESC", 0, QApplication::UnicodeUTF8)));
        qelineedit_16->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelabel_35->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:4132-4:PC:CH3.RVAL", 0, QApplication::UnicodeUTF8)));
        qelabel_35->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelabel_36->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:4132-4:SBYTE3", 0, QApplication::UnicodeUTF8)));
        qelabel_36->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelineedit_17->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:4132-4:PC:CH4", 0, QApplication::UnicodeUTF8)));
        qelineedit_17->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelineedit_18->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AI:4132-4:PC:CH4.DESC", 0, QApplication::UnicodeUTF8)));
        qelineedit_18->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelabel_37->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:4132-4:PC:CH4.RVAL", 0, QApplication::UnicodeUTF8)));
        qelabel_37->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        qelabel_38->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:4132-4:SBYTE3", 0, QApplication::UnicodeUTF8)));
        qelabel_38->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESAA", 0, QApplication::UnicodeUTF8)));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", "ADC-DAC", 0, QApplication::UnicodeUTF8));
        qelabel_39->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):ASUB:BKH4:MID.DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_39->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_40->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):ASUB:BKH4:MID.VALA", 0, QApplication::UnicodeUTF8)));
        qelabel_40->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_41->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO10.DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_41->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_42->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO11.DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_42->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_43->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO12.DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_43->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_44->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO16.DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_44->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_45->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO17.DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_45->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_46->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO18.DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_46->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_47->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO19.DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_47->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_48->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO32.DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_48->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_49->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO10", 0, QApplication::UnicodeUTF8)));
        qelabel_49->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_50->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO11", 0, QApplication::UnicodeUTF8)));
        qelabel_50->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_51->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO12", 0, QApplication::UnicodeUTF8)));
        qelabel_51->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_52->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO16", 0, QApplication::UnicodeUTF8)));
        qelabel_52->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_53->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO17", 0, QApplication::UnicodeUTF8)));
        qelabel_53->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_54->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO18", 0, QApplication::UnicodeUTF8)));
        qelabel_54->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_55->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO19", 0, QApplication::UnicodeUTF8)));
        qelabel_55->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_56->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:BKH4:RO32", 0, QApplication::UnicodeUTF8)));
        qelabel_56->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelineedit_19->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LO:BKH4:RW1", 0, QApplication::UnicodeUTF8)));
        qelineedit_19->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelineedit_20->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LO:BKH4:RW2", 0, QApplication::UnicodeUTF8)));
        qelineedit_20->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelineedit_21->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LO:BKH4:RW23", 0, QApplication::UnicodeUTF8)));
        qelineedit_21->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelineedit_22->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LO:BKH4:RW24", 0, QApplication::UnicodeUTF8)));
        qelineedit_22->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelineedit_23->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LO:BKH4:RW25", 0, QApplication::UnicodeUTF8)));
        qelineedit_23->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelineedit_24->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LO:BKH4:RW26", 0, QApplication::UnicodeUTF8)));
        qelineedit_24->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_57->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LO:BKH4:RW1.DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_57->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_58->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LO:BKH4:RW2.DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_58->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_59->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LO:BKH4:RW23.DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_59->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_60->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LO:BKH4:RW24.DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_60->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_61->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LO:BKH4:RW25.DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_61->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        qelabel_62->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LO:BKH4:RW26.DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_62->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=ESA", 0, QApplication::UnicodeUTF8)));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("MainWindow", "BK9000", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("MainWindow", "Read/Write Terminl Registers", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "TRegs", 0, QApplication::UnicodeUTF8));
        menuFile->setTitle(QApplication::translate("MainWindow", "File", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
