/********************************************************************************
** Form generated from reading UI file 'feature.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_FEATURE_H
#define UI_FEATURE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QListWidget>
#include "QBitStatus.h"
#include "QEBitStatus.h"
#include "QELabel.h"
#include "abutton.h"
#include "cabutton.h"

QT_BEGIN_NAMESPACE

class Ui_Feature
{
public:
    QLabel *label_38;
    QLabel *label_43;
    QEBitStatus *qebitstatus_4;
    QLabel *label_40;
    QLabel *label_52;
    QLabel *label_35;
    QLabel *label_53;
    QLabel *label_59;
    QLabel *label_54;
    QLabel *label_60;
    QLabel *label_55;
    QLabel *label_61;
    QLabel *label_56;
    QLabel *label_62;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *label_42;
    QLabel *label_37;
    QLabel *label_46;
    QLabel *label_44;
    QLabel *label_39;
    QLabel *label_45;
    QLabel *label_33;
    QLabel *label_36;
    QLabel *label_34;
    QFrame *line_5;
    QFrame *line_9;
    QFrame *line_2;
    QListWidget *listWidget;
    QFrame *line_10;
    QListWidget *listWidget_2;
    QFrame *line_11;
    QFrame *line_7;
    QListWidget *listWidget_3;
    QFrame *line_6;
    QFrame *line_4;
    QFrame *line_3;
    QFrame *line_12;
    QFrame *line_8;
    CAButton *cabutton;
    CAButton *cabutton_2;
    CAButton *cabutton_3;
    CAButton *cabutton_4;
    CAButton *cabutton_5;
    CAButton *cabutton_6;
    CAButton *cabutton_7;
    CAButton *cabutton_8;
    CAButton *cabutton_9;
    CAButton *cabutton_10;
    CAButton *cabutton_11;
    CAButton *cabutton_12;
    CAButton *cabutton_13;
    CAButton *cabutton_14;
    CAButton *cabutton_15;
    CAButton *cabutton_16;
    QELabel *qelabel;
    QLabel *label_41;

    void setupUi(QDialog *Feature)
    {
        if (Feature->objectName().isEmpty())
            Feature->setObjectName(QStringLiteral("Feature"));
        Feature->resize(418, 264);
        label_38 = new QLabel(Feature);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(10, 96, 14, 12));
        QFont font;
        font.setPointSize(8);
        label_38->setFont(font);
        label_38->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_43 = new QLabel(Feature);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(42, 212, 77, 16));
        QFont font1;
        font1.setPointSize(7);
        label_43->setFont(font1);
        qebitstatus_4 = new QEBitStatus(Feature);
        qebitstatus_4->setObjectName(QStringLiteral("qebitstatus_4"));
        qebitstatus_4->setGeometry(QRect(26, 46, 12, 192));
        qebitstatus_4->setNumberOfBits(16);
        qebitstatus_4->setOrientation(QBitStatus::LSB_On_Bottom);
        qebitstatus_4->setOffColour(QColor(157, 171, 193));
        qebitstatus_4->setDisplayAlarmState(false);
        label_40 = new QLabel(Feature);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(10, 48, 14, 12));
        label_40->setFont(font);
        label_40->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_52 = new QLabel(Feature);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(42, 68, 77, 16));
        label_52->setFont(font1);
        label_35 = new QLabel(Feature);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(10, 180, 14, 12));
        label_35->setFont(font);
        label_35->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_53 = new QLabel(Feature);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(42, 80, 77, 16));
        label_53->setFont(font1);
        label_59 = new QLabel(Feature);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(42, 152, 77, 16));
        label_59->setFont(font1);
        label_54 = new QLabel(Feature);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(42, 92, 77, 16));
        label_54->setFont(font1);
        label_60 = new QLabel(Feature);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(42, 164, 77, 16));
        label_60->setFont(font1);
        label_55 = new QLabel(Feature);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(42, 104, 77, 16));
        label_55->setFont(font1);
        label_61 = new QLabel(Feature);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(42, 176, 77, 16));
        label_61->setFont(font1);
        label_56 = new QLabel(Feature);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(42, 116, 77, 16));
        label_56->setFont(font1);
        label_62 = new QLabel(Feature);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(42, 188, 77, 16));
        label_62->setFont(font1);
        label_57 = new QLabel(Feature);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(42, 130, 81, 13));
        label_57->setFont(font1);
        label_58 = new QLabel(Feature);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(42, 140, 77, 16));
        label_58->setFont(font1);
        label_42 = new QLabel(Feature);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(42, 200, 77, 16));
        label_42->setFont(font1);
        label_37 = new QLabel(Feature);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(10, 132, 14, 12));
        label_37->setFont(font);
        label_37->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_46 = new QLabel(Feature);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(42, 56, 77, 16));
        label_46->setFont(font1);
        label_44 = new QLabel(Feature);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(42, 224, 77, 16));
        label_44->setFont(font1);
        label_39 = new QLabel(Feature);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(10, 84, 14, 12));
        label_39->setFont(font);
        label_39->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_45 = new QLabel(Feature);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(42, 44, 77, 16));
        label_45->setFont(font1);
        label_33 = new QLabel(Feature);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(10, 228, 14, 12));
        label_33->setFont(font);
        label_33->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_36 = new QLabel(Feature);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(10, 148, 14, 12));
        label_36->setFont(font);
        label_36->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_34 = new QLabel(Feature);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(10, 192, 14, 12));
        label_34->setFont(font);
        label_34->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        line_5 = new QFrame(Feature);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(161, 40, 25, 16));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(Feature);
        line_9->setObjectName(QStringLiteral("line_9"));
        line_9->setGeometry(QRect(186, 180, 3, 22));
        line_9->setFrameShape(QFrame::VLine);
        line_9->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(Feature);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(161, 196, 25, 16));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        listWidget = new QListWidget(Feature);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        listWidget->setObjectName(QStringLiteral("listWidget"));
        listWidget->setGeometry(QRect(258, 32, 153, 85));
        line_10 = new QFrame(Feature);
        line_10->setObjectName(QStringLiteral("line_10"));
        line_10->setGeometry(QRect(187, 80, 60, 3));
        line_10->setFrameShape(QFrame::HLine);
        line_10->setFrameShadow(QFrame::Sunken);
        listWidget_2 = new QListWidget(Feature);
        new QListWidgetItem(listWidget_2);
        new QListWidgetItem(listWidget_2);
        new QListWidgetItem(listWidget_2);
        listWidget_2->setObjectName(QStringLiteral("listWidget_2"));
        listWidget_2->setGeometry(QRect(258, 120, 153, 53));
        line_11 = new QFrame(Feature);
        line_11->setObjectName(QStringLiteral("line_11"));
        line_11->setGeometry(QRect(206, 144, 40, 3));
        line_11->setFrameShape(QFrame::HLine);
        line_11->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(Feature);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(162, 164, 45, 16));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        listWidget_3 = new QListWidget(Feature);
        new QListWidgetItem(listWidget_3);
        new QListWidgetItem(listWidget_3);
        new QListWidgetItem(listWidget_3);
        new QListWidgetItem(listWidget_3);
        new QListWidgetItem(listWidget_3);
        listWidget_3->setObjectName(QStringLiteral("listWidget_3"));
        listWidget_3->setGeometry(QRect(258, 176, 153, 81));
        line_6 = new QFrame(Feature);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(186, 48, 3, 70));
        line_6->setFrameShape(QFrame::VLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(Feature);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(161, 112, 25, 16));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(Feature);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(161, 172, 25, 16));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_12 = new QFrame(Feature);
        line_12->setObjectName(QStringLiteral("line_12"));
        line_12->setGeometry(QRect(187, 196, 60, 3));
        line_12->setFrameShape(QFrame::HLine);
        line_12->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(Feature);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setGeometry(QRect(206, 144, 3, 26));
        line_8->setFrameShape(QFrame::VLine);
        line_8->setFrameShadow(QFrame::Sunken);
        cabutton = new CAButton(Feature);
        cabutton->setObjectName(QStringLiteral("cabutton"));
        cabutton->setGeometry(QRect(144, 228, 12, 12));
        cabutton->setCheckable(true);
        cabutton->setAutoDefault(false);
        cabutton->setProperty("writeOnPress", QVariant(false));
        cabutton->setProperty("writeOnClick", QVariant(true));
        cabutton->setProperty("writeBits", QVariant(true));
        cabutton->setShowLabel(false);
        cabutton->setSubscribe(true);
        cabutton->setProperty("AlarmEnable", QVariant(false));
        cabutton_2 = new CAButton(Feature);
        cabutton_2->setObjectName(QStringLiteral("cabutton_2"));
        cabutton_2->setGeometry(QRect(144, 216, 12, 12));
        cabutton_2->setCheckable(true);
        cabutton_2->setAutoDefault(false);
        cabutton_2->setProperty("writeOnPress", QVariant(false));
        cabutton_2->setProperty("writeOnClick", QVariant(true));
        cabutton_2->setProperty("writeBits", QVariant(true));
        cabutton_2->setShowLabel(false);
        cabutton_2->setProperty("bitNumber", QVariant(1u));
        cabutton_2->setSubscribe(true);
        cabutton_2->setProperty("AlarmEnable", QVariant(false));
        cabutton_3 = new CAButton(Feature);
        cabutton_3->setObjectName(QStringLiteral("cabutton_3"));
        cabutton_3->setGeometry(QRect(144, 204, 12, 12));
        cabutton_3->setCheckable(true);
        cabutton_3->setAutoDefault(false);
        cabutton_3->setProperty("writeOnPress", QVariant(false));
        cabutton_3->setProperty("writeOnClick", QVariant(true));
        cabutton_3->setProperty("writeBits", QVariant(true));
        cabutton_3->setShowLabel(false);
        cabutton_3->setProperty("bitNumber", QVariant(2u));
        cabutton_3->setSubscribe(true);
        cabutton_3->setProperty("AlarmEnable", QVariant(false));
        cabutton_4 = new CAButton(Feature);
        cabutton_4->setObjectName(QStringLiteral("cabutton_4"));
        cabutton_4->setGeometry(QRect(144, 192, 12, 12));
        cabutton_4->setCheckable(true);
        cabutton_4->setAutoDefault(false);
        cabutton_4->setProperty("writeOnPress", QVariant(false));
        cabutton_4->setProperty("writeOnClick", QVariant(true));
        cabutton_4->setProperty("writeBits", QVariant(true));
        cabutton_4->setShowLabel(false);
        cabutton_4->setProperty("bitNumber", QVariant(3u));
        cabutton_4->setSubscribe(true);
        cabutton_4->setProperty("AlarmEnable", QVariant(false));
        cabutton_5 = new CAButton(Feature);
        cabutton_5->setObjectName(QStringLiteral("cabutton_5"));
        cabutton_5->setGeometry(QRect(144, 180, 12, 12));
        cabutton_5->setCheckable(true);
        cabutton_5->setAutoDefault(false);
        cabutton_5->setProperty("writeOnPress", QVariant(false));
        cabutton_5->setProperty("writeOnClick", QVariant(true));
        cabutton_5->setProperty("writeBits", QVariant(true));
        cabutton_5->setShowLabel(false);
        cabutton_5->setProperty("bitNumber", QVariant(4u));
        cabutton_5->setSubscribe(true);
        cabutton_5->setProperty("AlarmEnable", QVariant(false));
        cabutton_6 = new CAButton(Feature);
        cabutton_6->setObjectName(QStringLiteral("cabutton_6"));
        cabutton_6->setGeometry(QRect(144, 144, 12, 12));
        cabutton_6->setCheckable(true);
        cabutton_6->setAutoDefault(false);
        cabutton_6->setProperty("writeOnPress", QVariant(false));
        cabutton_6->setProperty("writeOnClick", QVariant(true));
        cabutton_6->setProperty("writeBits", QVariant(true));
        cabutton_6->setShowLabel(false);
        cabutton_6->setProperty("bitNumber", QVariant(7u));
        cabutton_6->setSubscribe(true);
        cabutton_6->setProperty("AlarmEnable", QVariant(false));
        cabutton_7 = new CAButton(Feature);
        cabutton_7->setObjectName(QStringLiteral("cabutton_7"));
        cabutton_7->setGeometry(QRect(144, 168, 12, 12));
        cabutton_7->setCheckable(true);
        cabutton_7->setAutoDefault(false);
        cabutton_7->setProperty("writeOnPress", QVariant(false));
        cabutton_7->setProperty("writeOnClick", QVariant(true));
        cabutton_7->setProperty("writeBits", QVariant(true));
        cabutton_7->setShowLabel(false);
        cabutton_7->setProperty("bitNumber", QVariant(5u));
        cabutton_7->setSubscribe(true);
        cabutton_7->setProperty("AlarmEnable", QVariant(false));
        cabutton_8 = new CAButton(Feature);
        cabutton_8->setObjectName(QStringLiteral("cabutton_8"));
        cabutton_8->setGeometry(QRect(144, 156, 12, 12));
        cabutton_8->setCheckable(true);
        cabutton_8->setAutoDefault(false);
        cabutton_8->setProperty("writeOnPress", QVariant(false));
        cabutton_8->setProperty("writeOnClick", QVariant(true));
        cabutton_8->setProperty("writeBits", QVariant(true));
        cabutton_8->setShowLabel(false);
        cabutton_8->setProperty("bitNumber", QVariant(6u));
        cabutton_8->setSubscribe(true);
        cabutton_8->setProperty("AlarmEnable", QVariant(false));
        cabutton_9 = new CAButton(Feature);
        cabutton_9->setObjectName(QStringLiteral("cabutton_9"));
        cabutton_9->setGeometry(QRect(144, 132, 12, 12));
        cabutton_9->setCheckable(true);
        cabutton_9->setAutoDefault(false);
        cabutton_9->setProperty("writeOnPress", QVariant(false));
        cabutton_9->setProperty("writeOnClick", QVariant(true));
        cabutton_9->setProperty("writeBits", QVariant(true));
        cabutton_9->setShowLabel(false);
        cabutton_9->setProperty("bitNumber", QVariant(8u));
        cabutton_9->setSubscribe(true);
        cabutton_9->setProperty("AlarmEnable", QVariant(false));
        cabutton_10 = new CAButton(Feature);
        cabutton_10->setObjectName(QStringLiteral("cabutton_10"));
        cabutton_10->setGeometry(QRect(144, 60, 12, 12));
        cabutton_10->setCheckable(true);
        cabutton_10->setAutoDefault(false);
        cabutton_10->setProperty("writeOnPress", QVariant(false));
        cabutton_10->setProperty("writeOnClick", QVariant(true));
        cabutton_10->setProperty("writeBits", QVariant(true));
        cabutton_10->setShowLabel(false);
        cabutton_10->setProperty("bitNumber", QVariant(14u));
        cabutton_10->setSubscribe(true);
        cabutton_10->setProperty("AlarmEnable", QVariant(false));
        cabutton_11 = new CAButton(Feature);
        cabutton_11->setObjectName(QStringLiteral("cabutton_11"));
        cabutton_11->setGeometry(QRect(144, 84, 12, 12));
        cabutton_11->setCheckable(true);
        cabutton_11->setAutoDefault(false);
        cabutton_11->setProperty("writeOnPress", QVariant(false));
        cabutton_11->setProperty("writeOnClick", QVariant(true));
        cabutton_11->setProperty("writeBits", QVariant(true));
        cabutton_11->setShowLabel(false);
        cabutton_11->setProperty("bitNumber", QVariant(12u));
        cabutton_11->setSubscribe(true);
        cabutton_11->setProperty("AlarmEnable", QVariant(false));
        cabutton_12 = new CAButton(Feature);
        cabutton_12->setObjectName(QStringLiteral("cabutton_12"));
        cabutton_12->setGeometry(QRect(144, 72, 12, 12));
        cabutton_12->setCheckable(true);
        cabutton_12->setAutoDefault(false);
        cabutton_12->setProperty("writeOnPress", QVariant(false));
        cabutton_12->setProperty("writeOnClick", QVariant(true));
        cabutton_12->setProperty("writeBits", QVariant(true));
        cabutton_12->setShowLabel(false);
        cabutton_12->setProperty("bitNumber", QVariant(13u));
        cabutton_12->setSubscribe(true);
        cabutton_12->setProperty("AlarmEnable", QVariant(false));
        cabutton_13 = new CAButton(Feature);
        cabutton_13->setObjectName(QStringLiteral("cabutton_13"));
        cabutton_13->setGeometry(QRect(144, 96, 12, 12));
        cabutton_13->setCheckable(true);
        cabutton_13->setAutoDefault(false);
        cabutton_13->setProperty("writeOnPress", QVariant(false));
        cabutton_13->setProperty("writeOnClick", QVariant(true));
        cabutton_13->setProperty("writeBits", QVariant(true));
        cabutton_13->setShowLabel(false);
        cabutton_13->setProperty("bitNumber", QVariant(11u));
        cabutton_13->setSubscribe(true);
        cabutton_13->setProperty("AlarmEnable", QVariant(false));
        cabutton_14 = new CAButton(Feature);
        cabutton_14->setObjectName(QStringLiteral("cabutton_14"));
        cabutton_14->setGeometry(QRect(144, 120, 12, 12));
        cabutton_14->setCheckable(true);
        cabutton_14->setAutoDefault(false);
        cabutton_14->setProperty("writeOnPress", QVariant(false));
        cabutton_14->setProperty("writeOnClick", QVariant(true));
        cabutton_14->setProperty("writeBits", QVariant(true));
        cabutton_14->setShowLabel(false);
        cabutton_14->setProperty("bitNumber", QVariant(9u));
        cabutton_14->setSubscribe(true);
        cabutton_14->setProperty("AlarmEnable", QVariant(false));
        cabutton_15 = new CAButton(Feature);
        cabutton_15->setObjectName(QStringLiteral("cabutton_15"));
        cabutton_15->setGeometry(QRect(144, 108, 12, 12));
        cabutton_15->setCheckable(true);
        cabutton_15->setAutoDefault(false);
        cabutton_15->setProperty("writeOnPress", QVariant(false));
        cabutton_15->setProperty("writeOnClick", QVariant(true));
        cabutton_15->setProperty("writeBits", QVariant(true));
        cabutton_15->setShowLabel(false);
        cabutton_15->setProperty("bitNumber", QVariant(10u));
        cabutton_15->setSubscribe(true);
        cabutton_15->setProperty("AlarmEnable", QVariant(false));
        cabutton_16 = new CAButton(Feature);
        cabutton_16->setObjectName(QStringLiteral("cabutton_16"));
        cabutton_16->setGeometry(QRect(144, 48, 12, 12));
        cabutton_16->setCheckable(true);
        cabutton_16->setAutoDefault(false);
        cabutton_16->setProperty("writeOnPress", QVariant(false));
        cabutton_16->setProperty("writeOnClick", QVariant(true));
        cabutton_16->setProperty("writeBits", QVariant(true));
        cabutton_16->setShowLabel(false);
        cabutton_16->setProperty("bitNumber", QVariant(15u));
        cabutton_16->setSubscribe(true);
        cabutton_16->setProperty("AlarmEnable", QVariant(false));
        qelabel = new QELabel(Feature);
        qelabel->setObjectName(QStringLiteral("qelabel"));
        qelabel->setGeometry(QRect(58, 10, 81, 16));
        QFont font2;
        font2.setPointSize(12);
        qelabel->setFont(font2);
        qelabel->setDisplayAlarmState(false);
        label_41 = new QLabel(Feature);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(152, 10, 125, 16));
        QFont font3;
        font3.setPointSize(11);
        label_41->setFont(font3);

        retranslateUi(Feature);

        QMetaObject::connectSlotsByName(Feature);
    } // setupUi

    void retranslateUi(QDialog *Feature)
    {
        Feature->setWindowTitle(QApplication::translate("Feature", "Dialog", 0));
        label_38->setText(QApplication::translate("Feature", "11", 0));
        label_43->setText(QApplication::translate("Feature", "EnAutoStop", 0));
        qebitstatus_4->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LI:$(M)-$(N):RWE:FEAT", 0)));
        qebitstatus_4->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        label_40->setText(QApplication::translate("Feature", "15", 0));
        label_52->setText(QApplication::translate("Feature", "EnPosGateLock", 0));
        label_35->setText(QApplication::translate("Feature", "4", 0));
        label_53->setText(QApplication::translate("Feature", "EnNegGateLock", 0));
        label_59->setText(QApplication::translate("Feature", "InvPosFeedback", 0));
        label_54->setText(QApplication::translate("Feature", "FeedbackType", 0));
        label_60->setText(QApplication::translate("Feature", "RampType", 0));
        label_55->setText(QApplication::translate("Feature", "EnSignalDisplay", 0));
        label_61->setText(QApplication::translate("Feature", "OpMode-1", 0));
        label_56->setText(QApplication::translate("Feature", "EnMultiLatchVal", 0));
        label_62->setText(QApplication::translate("Feature", "OpMode-0", 0));
        label_57->setText(QApplication::translate("Feature", "EnLatchEvntClr", 0));
        label_58->setText(QApplication::translate("Feature", "EnUserCurTable", 0));
        label_42->setText(QApplication::translate("Feature", "DisWatchTimer", 0));
        label_37->setText(QApplication::translate("Feature", "8", 0));
        label_46->setText(QApplication::translate("Feature", "DisEncFilter", 0));
        label_44->setText(QApplication::translate("Feature", "EnAutoSsstart", 0));
        label_39->setText(QApplication::translate("Feature", "12", 0));
        label_45->setText(QApplication::translate("Feature", "EnCounterMode", 0));
        label_33->setText(QApplication::translate("Feature", "0", 0));
        label_36->setText(QApplication::translate("Feature", "7", 0));
        label_34->setText(QApplication::translate("Feature", "3", 0));

        const bool __sortingEnabled = listWidget->isSortingEnabled();
        listWidget->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem = listWidget->item(0);
        ___qlistwidgetitem->setText(QApplication::translate("Feature", "Bits 10 - 15 for", 0));
        QListWidgetItem *___qlistwidgetitem1 = listWidget->item(1);
        ___qlistwidgetitem1->setText(QApplication::translate("Feature", " KL2541 only", 0));
        QListWidgetItem *___qlistwidgetitem2 = listWidget->item(2);
        ___qlistwidgetitem2->setText(QApplication::translate("Feature", "Feedback type:", 0));
        QListWidgetItem *___qlistwidgetitem3 = listWidget->item(3);
        ___qlistwidgetitem3->setText(QApplication::translate("Feature", "  0 external encoder", 0));
        QListWidgetItem *___qlistwidgetitem4 = listWidget->item(4);
        ___qlistwidgetitem4->setText(QApplication::translate("Feature", "  1 internal counter", 0));
        listWidget->setSortingEnabled(__sortingEnabled);


        const bool __sortingEnabled1 = listWidget_2->isSortingEnabled();
        listWidget_2->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem5 = listWidget_2->item(0);
        ___qlistwidgetitem5->setText(QApplication::translate("Feature", "Ramp Type:", 0));
        QListWidgetItem *___qlistwidgetitem6 = listWidget_2->item(1);
        ___qlistwidgetitem6->setText(QApplication::translate("Feature", "  0 Linear", 0));
        QListWidgetItem *___qlistwidgetitem7 = listWidget_2->item(2);
        ___qlistwidgetitem7->setText(QApplication::translate("Feature", "  1 Exponential", 0));
        listWidget_2->setSortingEnabled(__sortingEnabled1);


        const bool __sortingEnabled2 = listWidget_3->isSortingEnabled();
        listWidget_3->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem8 = listWidget_3->item(0);
        ___qlistwidgetitem8->setText(QApplication::translate("Feature", "Op Mode:", 0));
        QListWidgetItem *___qlistwidgetitem9 = listWidget_3->item(1);
        ___qlistwidgetitem9->setText(QApplication::translate("Feature", "  00 Velocity Direct", 0));
        QListWidgetItem *___qlistwidgetitem10 = listWidget_3->item(2);
        ___qlistwidgetitem10->setText(QApplication::translate("Feature", "  01 Velo with Ramp", 0));
        QListWidgetItem *___qlistwidgetitem11 = listWidget_3->item(3);
        ___qlistwidgetitem11->setText(QApplication::translate("Feature", "  10 Position tracking", 0));
        QListWidgetItem *___qlistwidgetitem12 = listWidget_3->item(4);
        ___qlistwidgetitem12->setText(QApplication::translate("Feature", "  11 Path Control", 0));
        listWidget_3->setSortingEnabled(__sortingEnabled2);

        cabutton->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        cabutton_2->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton_2->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        cabutton_3->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton_3->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        cabutton_4->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton_4->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        cabutton_5->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton_5->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        cabutton_6->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton_6->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        cabutton_7->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton_7->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        cabutton_8->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton_8->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        cabutton_9->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton_9->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        cabutton_10->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton_10->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        cabutton_11->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton_11->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        cabutton_12->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton_12->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        cabutton_13->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton_13->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        cabutton_14->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton_14->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        cabutton_15->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton_15->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        cabutton_16->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LO:$(M)-$(N):RWE:FEAT", 0)));
        cabutton_16->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        qelabel->setProperty("variable", QVariant(QApplication::translate("Feature", "$(P):LI:$(M)-$(N):DATA.DESC", 0)));
        qelabel->setProperty("variableSubstitutions", QVariant(QApplication::translate("Feature", "P=CHA,M=2531-1,N=2", 0)));
        label_41->setText(QApplication::translate("Feature", "Feature register", 0));
    } // retranslateUi

};

namespace Ui {
    class Feature: public Ui_Feature {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_FEATURE_H
