/********************************************************************************
** Form generated from reading UI file 'csr.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CSR_H
#define UI_CSR_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include "QBitStatus.h"
#include "QEBitStatus.h"
#include "QELabel.h"
#include "QELineEdit.h"
#include "abutton.h"
#include "cabutton.h"

QT_BEGIN_NAMESPACE

class Ui_CSR
{
public:
    QLabel *SB_label_15;
    QLabel *SB_label_9;
    QLabel *SB_label_8;
    QLabel *SB_label_12;
    QLabel *SB_label_14;
    QLabel *SB_label_13;
    QELabel *qelabel_7;
    QLabel *label_11;
    QLabel *SB_label_10;
    QLabel *label_9;
    QLabel *label_10;
    QEBitStatus *qebitstatus_2;
    QLabel *SB_label_11;
    QELineEdit *qelineedit_2;
    QELabel *qelabel_8;
    QLabel *SB_label_22;
    QLabel *SB_label_23;
    QLabel *label_12;
    QLabel *label_31;
    QLabel *SB_label_18;
    QLabel *SB_label_20;
    QLabel *SB_label_19;
    QLabel *SB_label_17;
    QLabel *label_32;
    QLabel *SB_label_16;
    QLabel *SB_label_21;
    QELineEdit *qelineedit;
    QLabel *SB_label_36;
    QLabel *SB_label_37;
    QELabel *qelabel_13;
    QLabel *SB_label_38;
    QLabel *SB_label_39;
    QLabel *label_29;
    QLabel *SB_label_25;
    QLabel *label_22;
    QLabel *label_28;
    QLabel *label_15;
    QEBitStatus *qebitstatus_3;
    QLabel *SB_label_26;
    QLabel *SB_label_27;
    QLabel *label_20;
    QLabel *label_14;
    QLabel *label_21;
    QLabel *SB_label_24;
    QLabel *label_19;
    QLabel *SB_label_31;
    QLabel *SB_label_32;
    QLabel *SB_label_33;
    QLabel *SB_label_28;
    QLabel *SB_label_34;
    QLabel *SB_label_29;
    QLabel *label_13;
    QLabel *SB_label_35;
    QLabel *SB_label_30;
    QELineEdit *qelineedit_3;
    QLabel *SB_label_54;
    QLabel *SB_label_52;
    QLabel *SB_label_41;
    QLabel *SB_label_42;
    QLabel *label_30;
    QLabel *SB_label_50;
    QLabel *SB_label_40;
    QLabel *SB_label_51;
    QLabel *SB_label_43;
    QLabel *SB_label_45;
    QLabel *SB_label_47;
    QLabel *SB_label_53;
    QLabel *SB_label_46;
    QLabel *SB_label_48;
    QLabel *SB_label_44;
    QLabel *SB_label_49;
    QLabel *label;
    QLabel *label_2;
    CAButton *cabutton;
    CAButton *cabutton_2;
    CAButton *cabutton_3;
    CAButton *cabutton_4;
    CAButton *cabutton_5;
    CAButton *cabutton_6;
    CAButton *cabutton_7;
    CAButton *cabutton_8;
    CAButton *cabutton_9;
    CAButton *cabutton_10;
    CAButton *cabutton_11;
    CAButton *cabutton_12;
    CAButton *cabutton_13;
    CAButton *cabutton_14;
    CAButton *cabutton_15;
    CAButton *cabutton_16;
    CAButton *cabutton_17;
    CAButton *cabutton_18;
    CAButton *cabutton_19;
    CAButton *cabutton_20;
    CAButton *cabutton_21;
    CAButton *cabutton_22;
    CAButton *cabutton_23;
    QELabel *qelabel;

    void setupUi(QDialog *CSR)
    {
        if (CSR->objectName().isEmpty())
            CSR->setObjectName(QStringLiteral("CSR"));
        CSR->resize(432, 271);
        SB_label_15 = new QLabel(CSR);
        SB_label_15->setObjectName(QStringLiteral("SB_label_15"));
        SB_label_15->setGeometry(QRect(36, 98, 65, 12));
        QFont font;
        font.setPointSize(7);
        SB_label_15->setFont(font);
        SB_label_9 = new QLabel(CSR);
        SB_label_9->setObjectName(QStringLiteral("SB_label_9"));
        SB_label_9->setGeometry(QRect(36, 134, 65, 12));
        SB_label_9->setFont(font);
        SB_label_8 = new QLabel(CSR);
        SB_label_8->setObjectName(QStringLiteral("SB_label_8"));
        SB_label_8->setGeometry(QRect(36, 74, 65, 12));
        SB_label_8->setFont(font);
        SB_label_12 = new QLabel(CSR);
        SB_label_12->setObjectName(QStringLiteral("SB_label_12"));
        SB_label_12->setGeometry(QRect(36, 110, 65, 12));
        SB_label_12->setFont(font);
        SB_label_14 = new QLabel(CSR);
        SB_label_14->setObjectName(QStringLiteral("SB_label_14"));
        SB_label_14->setGeometry(QRect(36, 86, 65, 12));
        SB_label_14->setFont(font);
        SB_label_13 = new QLabel(CSR);
        SB_label_13->setObjectName(QStringLiteral("SB_label_13"));
        SB_label_13->setGeometry(QRect(36, 50, 65, 12));
        SB_label_13->setFont(font);
        qelabel_7 = new QELabel(CSR);
        qelabel_7->setObjectName(QStringLiteral("qelabel_7"));
        qelabel_7->setGeometry(QRect(32, 154, 26, 16));
        qelabel_7->setDisplayAlarmState(false);
        qelabel_7->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_7->setRadix(16u);
        qelabel_7->setProperty("notation", QVariant(QELabel::Automatic));
        qelabel_7->setProperty("arrayAction", QVariant(QELabel::Ascii));
        qelabel_7->setProperty("updateOption", QVariant(QELabel::Text));
        label_11 = new QLabel(CSR);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(8, 50, 12, 12));
        QFont font1;
        font1.setPointSize(8);
        label_11->setFont(font1);
        SB_label_10 = new QLabel(CSR);
        SB_label_10->setObjectName(QStringLiteral("SB_label_10"));
        SB_label_10->setGeometry(QRect(36, 122, 65, 12));
        SB_label_10->setFont(font);
        label_9 = new QLabel(CSR);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(8, 156, 12, 12));
        label_9->setFont(font1);
        label_10 = new QLabel(CSR);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(20, 30, 69, 16));
        qebitstatus_2 = new QEBitStatus(CSR);
        qebitstatus_2->setObjectName(QStringLiteral("qebitstatus_2"));
        qebitstatus_2->setGeometry(QRect(20, 50, 12, 96));
        qebitstatus_2->setOrientation(QBitStatus::LSB_On_Bottom);
        qebitstatus_2->setOffColour(QColor(157, 171, 193));
        SB_label_11 = new QLabel(CSR);
        SB_label_11->setObjectName(QStringLiteral("SB_label_11"));
        SB_label_11->setGeometry(QRect(36, 62, 65, 12));
        SB_label_11->setFont(font);
        qelineedit_2 = new QELineEdit(CSR);
        qelineedit_2->setObjectName(QStringLiteral("qelineedit_2"));
        qelineedit_2->setGeometry(QRect(110, 150, 41, 21));
        qelineedit_2->setDisplayAlarmState(false);
        qelineedit_2->setProperty("format", QVariant(QELineEdit::UnsignedInteger));
        qelineedit_2->setRadix(16u);
        qelabel_8 = new QELabel(CSR);
        qelabel_8->setObjectName(QStringLiteral("qelabel_8"));
        qelabel_8->setGeometry(QRect(130, 182, 57, 16));
        qelabel_8->setDisplayAlarmState(false);
        SB_label_22 = new QLabel(CSR);
        SB_label_22->setObjectName(QStringLiteral("SB_label_22"));
        SB_label_22->setGeometry(QRect(126, 134, 53, 12));
        SB_label_22->setFont(font);
        SB_label_23 = new QLabel(CSR);
        SB_label_23->setObjectName(QStringLiteral("SB_label_23"));
        SB_label_23->setGeometry(QRect(126, 110, 53, 12));
        SB_label_23->setFont(font);
        label_12 = new QLabel(CSR);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(110, 30, 73, 16));
        label_31 = new QLabel(CSR);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(66, 182, 56, 15));
        label_31->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        SB_label_18 = new QLabel(CSR);
        SB_label_18->setObjectName(QStringLiteral("SB_label_18"));
        SB_label_18->setGeometry(QRect(126, 86, 53, 12));
        SB_label_18->setFont(font);
        SB_label_20 = new QLabel(CSR);
        SB_label_20->setObjectName(QStringLiteral("SB_label_20"));
        SB_label_20->setGeometry(QRect(126, 122, 53, 12));
        SB_label_20->setFont(font);
        SB_label_19 = new QLabel(CSR);
        SB_label_19->setObjectName(QStringLiteral("SB_label_19"));
        SB_label_19->setGeometry(QRect(126, 62, 53, 12));
        SB_label_19->setFont(font);
        SB_label_17 = new QLabel(CSR);
        SB_label_17->setObjectName(QStringLiteral("SB_label_17"));
        SB_label_17->setGeometry(QRect(126, 74, 53, 12));
        SB_label_17->setFont(font);
        label_32 = new QLabel(CSR);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(66, 206, 56, 15));
        label_32->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        SB_label_16 = new QLabel(CSR);
        SB_label_16->setObjectName(QStringLiteral("SB_label_16"));
        SB_label_16->setGeometry(QRect(126, 98, 53, 12));
        SB_label_16->setFont(font);
        SB_label_21 = new QLabel(CSR);
        SB_label_21->setObjectName(QStringLiteral("SB_label_21"));
        SB_label_21->setGeometry(QRect(126, 48, 53, 16));
        SB_label_21->setFont(font);
        qelineedit = new QELineEdit(CSR);
        qelineedit->setObjectName(QStringLiteral("qelineedit"));
        qelineedit->setGeometry(QRect(128, 202, 65, 21));
        qelineedit->setDisplayAlarmState(false);
        SB_label_36 = new QLabel(CSR);
        SB_label_36->setObjectName(QStringLiteral("SB_label_36"));
        SB_label_36->setGeometry(QRect(236, 206, 65, 12));
        SB_label_36->setFont(font);
        SB_label_37 = new QLabel(CSR);
        SB_label_37->setObjectName(QStringLiteral("SB_label_37"));
        SB_label_37->setGeometry(QRect(236, 194, 65, 12));
        SB_label_37->setFont(font);
        qelabel_13 = new QELabel(CSR);
        qelabel_13->setObjectName(QStringLiteral("qelabel_13"));
        qelabel_13->setGeometry(QRect(232, 250, 45, 16));
        qelabel_13->setDisplayAlarmState(false);
        qelabel_13->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_13->setRadix(16u);
        qelabel_13->setProperty("notation", QVariant(QELabel::Automatic));
        qelabel_13->setProperty("arrayAction", QVariant(QELabel::Ascii));
        qelabel_13->setProperty("updateOption", QVariant(QELabel::Text));
        SB_label_38 = new QLabel(CSR);
        SB_label_38->setObjectName(QStringLiteral("SB_label_38"));
        SB_label_38->setGeometry(QRect(236, 146, 65, 12));
        SB_label_38->setFont(font);
        SB_label_39 = new QLabel(CSR);
        SB_label_39->setObjectName(QStringLiteral("SB_label_39"));
        SB_label_39->setGeometry(QRect(236, 170, 65, 12));
        SB_label_39->setFont(font);
        label_29 = new QLabel(CSR);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(216, 30, 69, 16));
        SB_label_25 = new QLabel(CSR);
        SB_label_25->setObjectName(QStringLiteral("SB_label_25"));
        SB_label_25->setGeometry(QRect(236, 74, 65, 12));
        SB_label_25->setFont(font);
        label_22 = new QLabel(CSR);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(202, 86, 14, 12));
        label_22->setFont(font1);
        label_22->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_28 = new QLabel(CSR);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(202, 50, 14, 12));
        label_28->setFont(font1);
        label_28->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_15 = new QLabel(CSR);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(202, 186, 14, 12));
        label_15->setFont(font1);
        label_15->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qebitstatus_3 = new QEBitStatus(CSR);
        qebitstatus_3->setObjectName(QStringLiteral("qebitstatus_3"));
        qebitstatus_3->setGeometry(QRect(220, 50, 12, 192));
        qebitstatus_3->setNumberOfBits(16);
        qebitstatus_3->setOrientation(QBitStatus::LSB_On_Bottom);
        qebitstatus_3->setOffColour(QColor(157, 171, 193));
        SB_label_26 = new QLabel(CSR);
        SB_label_26->setObjectName(QStringLiteral("SB_label_26"));
        SB_label_26->setGeometry(QRect(236, 86, 65, 12));
        SB_label_26->setFont(font);
        SB_label_27 = new QLabel(CSR);
        SB_label_27->setObjectName(QStringLiteral("SB_label_27"));
        SB_label_27->setGeometry(QRect(236, 62, 65, 12));
        SB_label_27->setFont(font);
        label_20 = new QLabel(CSR);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(202, 138, 14, 12));
        label_20->setFont(font1);
        label_20->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_14 = new QLabel(CSR);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(202, 198, 14, 12));
        label_14->setFont(font1);
        label_14->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_21 = new QLabel(CSR);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(202, 102, 14, 12));
        label_21->setFont(font1);
        label_21->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        SB_label_24 = new QLabel(CSR);
        SB_label_24->setObjectName(QStringLiteral("SB_label_24"));
        SB_label_24->setGeometry(QRect(236, 98, 65, 12));
        SB_label_24->setFont(font);
        label_19 = new QLabel(CSR);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(202, 150, 14, 12));
        label_19->setFont(font1);
        label_19->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        SB_label_31 = new QLabel(CSR);
        SB_label_31->setObjectName(QStringLiteral("SB_label_31"));
        SB_label_31->setGeometry(QRect(236, 110, 65, 12));
        SB_label_31->setFont(font);
        SB_label_32 = new QLabel(CSR);
        SB_label_32->setObjectName(QStringLiteral("SB_label_32"));
        SB_label_32->setGeometry(QRect(236, 218, 65, 12));
        SB_label_32->setFont(font);
        SB_label_33 = new QLabel(CSR);
        SB_label_33->setObjectName(QStringLiteral("SB_label_33"));
        SB_label_33->setGeometry(QRect(236, 182, 65, 12));
        SB_label_33->setFont(font);
        SB_label_28 = new QLabel(CSR);
        SB_label_28->setObjectName(QStringLiteral("SB_label_28"));
        SB_label_28->setGeometry(QRect(236, 122, 65, 12));
        SB_label_28->setFont(font);
        SB_label_34 = new QLabel(CSR);
        SB_label_34->setObjectName(QStringLiteral("SB_label_34"));
        SB_label_34->setGeometry(QRect(236, 230, 65, 12));
        SB_label_34->setFont(font);
        SB_label_29 = new QLabel(CSR);
        SB_label_29->setObjectName(QStringLiteral("SB_label_29"));
        SB_label_29->setGeometry(QRect(236, 50, 65, 12));
        SB_label_29->setFont(font);
        label_13 = new QLabel(CSR);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(202, 230, 14, 12));
        label_13->setFont(font1);
        label_13->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        SB_label_35 = new QLabel(CSR);
        SB_label_35->setObjectName(QStringLiteral("SB_label_35"));
        SB_label_35->setGeometry(QRect(236, 156, 69, 16));
        SB_label_35->setFont(font);
        SB_label_30 = new QLabel(CSR);
        SB_label_30->setObjectName(QStringLiteral("SB_label_30"));
        SB_label_30->setGeometry(QRect(236, 134, 65, 12));
        SB_label_30->setFont(font);
        qelineedit_3 = new QELineEdit(CSR);
        qelineedit_3->setObjectName(QStringLiteral("qelineedit_3"));
        qelineedit_3->setGeometry(QRect(328, 246, 57, 21));
        qelineedit_3->setDisplayAlarmState(false);
        qelineedit_3->setProperty("format", QVariant(QELineEdit::UnsignedInteger));
        qelineedit_3->setRadix(16u);
        SB_label_54 = new QLabel(CSR);
        SB_label_54->setObjectName(QStringLiteral("SB_label_54"));
        SB_label_54->setGeometry(QRect(344, 194, 80, 12));
        SB_label_54->setFont(font);
        SB_label_52 = new QLabel(CSR);
        SB_label_52->setObjectName(QStringLiteral("SB_label_52"));
        SB_label_52->setGeometry(QRect(344, 182, 80, 12));
        SB_label_52->setFont(font);
        SB_label_41 = new QLabel(CSR);
        SB_label_41->setObjectName(QStringLiteral("SB_label_41"));
        SB_label_41->setGeometry(QRect(344, 62, 80, 12));
        SB_label_41->setFont(font);
        SB_label_42 = new QLabel(CSR);
        SB_label_42->setObjectName(QStringLiteral("SB_label_42"));
        SB_label_42->setGeometry(QRect(344, 122, 80, 12));
        SB_label_42->setFont(font);
        label_30 = new QLabel(CSR);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(332, 30, 77, 16));
        SB_label_50 = new QLabel(CSR);
        SB_label_50->setObjectName(QStringLiteral("SB_label_50"));
        SB_label_50->setGeometry(QRect(344, 170, 80, 12));
        SB_label_50->setFont(font);
        SB_label_40 = new QLabel(CSR);
        SB_label_40->setObjectName(QStringLiteral("SB_label_40"));
        SB_label_40->setGeometry(QRect(344, 134, 80, 12));
        SB_label_40->setFont(font);
        SB_label_51 = new QLabel(CSR);
        SB_label_51->setObjectName(QStringLiteral("SB_label_51"));
        SB_label_51->setGeometry(QRect(344, 218, 80, 12));
        SB_label_51->setFont(font);
        SB_label_43 = new QLabel(CSR);
        SB_label_43->setObjectName(QStringLiteral("SB_label_43"));
        SB_label_43->setGeometry(QRect(344, 98, 80, 12));
        SB_label_43->setFont(font);
        SB_label_45 = new QLabel(CSR);
        SB_label_45->setObjectName(QStringLiteral("SB_label_45"));
        SB_label_45->setGeometry(QRect(344, 74, 80, 12));
        SB_label_45->setFont(font);
        SB_label_47 = new QLabel(CSR);
        SB_label_47->setObjectName(QStringLiteral("SB_label_47"));
        SB_label_47->setGeometry(QRect(344, 144, 80, 16));
        SB_label_47->setFont(font);
        SB_label_53 = new QLabel(CSR);
        SB_label_53->setObjectName(QStringLiteral("SB_label_53"));
        SB_label_53->setGeometry(QRect(344, 158, 80, 12));
        SB_label_53->setFont(font);
        SB_label_46 = new QLabel(CSR);
        SB_label_46->setObjectName(QStringLiteral("SB_label_46"));
        SB_label_46->setGeometry(QRect(344, 86, 80, 12));
        SB_label_46->setFont(font);
        SB_label_48 = new QLabel(CSR);
        SB_label_48->setObjectName(QStringLiteral("SB_label_48"));
        SB_label_48->setGeometry(QRect(344, 228, 80, 16));
        SB_label_48->setFont(font);
        SB_label_44 = new QLabel(CSR);
        SB_label_44->setObjectName(QStringLiteral("SB_label_44"));
        SB_label_44->setGeometry(QRect(344, 110, 80, 12));
        SB_label_44->setFont(font);
        SB_label_49 = new QLabel(CSR);
        SB_label_49->setObjectName(QStringLiteral("SB_label_49"));
        SB_label_49->setGeometry(QRect(344, 206, 80, 12));
        SB_label_49->setFont(font);
        label = new QLabel(CSR);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(24, 154, 16, 16));
        label_2 = new QLabel(CSR);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(224, 250, 16, 16));
        cabutton = new CAButton(CSR);
        cabutton->setObjectName(QStringLiteral("cabutton"));
        cabutton->setGeometry(QRect(110, 134, 12, 12));
        cabutton->setCheckable(true);
        cabutton->setAutoDefault(false);
        cabutton->setProperty("writeOnPress", QVariant(false));
        cabutton->setProperty("writeOnClick", QVariant(true));
        cabutton->setProperty("writeBits", QVariant(true));
        cabutton->setShowLabel(false);
        cabutton->setSubscribe(true);
        cabutton->setProperty("AlarmEnable", QVariant(false));
        cabutton_2 = new CAButton(CSR);
        cabutton_2->setObjectName(QStringLiteral("cabutton_2"));
        cabutton_2->setGeometry(QRect(110, 122, 12, 12));
        cabutton_2->setCheckable(false);
        cabutton_2->setAutoDefault(false);
        cabutton_2->setOnColor(QColor(255, 0, 0));
        cabutton_2->setOffColor(QColor(120, 0, 0));
        cabutton_2->setProperty("writeOnPress", QVariant(true));
        cabutton_2->setProperty("writeOnRelease", QVariant(true));
        cabutton_2->setProperty("writeOnClick", QVariant(false));
        cabutton_2->setProperty("writeBits", QVariant(true));
        cabutton_2->setShowLabel(false);
        cabutton_2->setProperty("bitNumber", QVariant(1u));
        cabutton_2->setSubscribe(true);
        cabutton_2->setProperty("AlarmEnable", QVariant(false));
        cabutton_3 = new CAButton(CSR);
        cabutton_3->setObjectName(QStringLiteral("cabutton_3"));
        cabutton_3->setGeometry(QRect(110, 110, 12, 12));
        cabutton_3->setCheckable(true);
        cabutton_3->setAutoDefault(false);
        cabutton_3->setProperty("writeOnPress", QVariant(false));
        cabutton_3->setProperty("writeOnClick", QVariant(true));
        cabutton_3->setProperty("writeBits", QVariant(true));
        cabutton_3->setShowLabel(false);
        cabutton_3->setProperty("bitNumber", QVariant(2u));
        cabutton_3->setSubscribe(true);
        cabutton_3->setProperty("AlarmEnable", QVariant(false));
        cabutton_4 = new CAButton(CSR);
        cabutton_4->setObjectName(QStringLiteral("cabutton_4"));
        cabutton_4->setGeometry(QRect(110, 98, 12, 12));
        cabutton_4->setCheckable(false);
        cabutton_4->setAutoDefault(false);
        cabutton_4->setOnColor(QColor(255, 0, 0));
        cabutton_4->setOffColor(QColor(120, 0, 0));
        cabutton_4->setProperty("writeOnPress", QVariant(true));
        cabutton_4->setProperty("writeOnRelease", QVariant(true));
        cabutton_4->setProperty("writeOnClick", QVariant(false));
        cabutton_4->setProperty("writeBits", QVariant(true));
        cabutton_4->setShowLabel(false);
        cabutton_4->setProperty("bitNumber", QVariant(3u));
        cabutton_4->setSubscribe(true);
        cabutton_4->setProperty("AlarmEnable", QVariant(false));
        cabutton_5 = new CAButton(CSR);
        cabutton_5->setObjectName(QStringLiteral("cabutton_5"));
        cabutton_5->setGeometry(QRect(110, 74, 12, 12));
        cabutton_5->setCheckable(true);
        cabutton_5->setAutoDefault(false);
        cabutton_5->setProperty("writeOnPress", QVariant(false));
        cabutton_5->setProperty("writeOnClick", QVariant(true));
        cabutton_5->setProperty("writeBits", QVariant(true));
        cabutton_5->setShowLabel(false);
        cabutton_5->setProperty("bitNumber", QVariant(5u));
        cabutton_5->setSubscribe(true);
        cabutton_5->setProperty("AlarmEnable", QVariant(false));
        cabutton_6 = new CAButton(CSR);
        cabutton_6->setObjectName(QStringLiteral("cabutton_6"));
        cabutton_6->setGeometry(QRect(110, 86, 12, 12));
        cabutton_6->setCheckable(true);
        cabutton_6->setAutoDefault(false);
        cabutton_6->setProperty("writeOnPress", QVariant(false));
        cabutton_6->setProperty("writeOnClick", QVariant(true));
        cabutton_6->setProperty("writeBits", QVariant(true));
        cabutton_6->setShowLabel(false);
        cabutton_6->setProperty("bitNumber", QVariant(4u));
        cabutton_6->setSubscribe(true);
        cabutton_6->setProperty("AlarmEnable", QVariant(false));
        cabutton_7 = new CAButton(CSR);
        cabutton_7->setObjectName(QStringLiteral("cabutton_7"));
        cabutton_7->setGeometry(QRect(110, 62, 12, 12));
        cabutton_7->setCheckable(false);
        cabutton_7->setAutoDefault(false);
        cabutton_7->setOnColor(QColor(255, 0, 0));
        cabutton_7->setOffColor(QColor(120, 0, 0));
        cabutton_7->setProperty("writeOnPress", QVariant(true));
        cabutton_7->setProperty("writeOnRelease", QVariant(true));
        cabutton_7->setProperty("writeOnClick", QVariant(false));
        cabutton_7->setProperty("writeBits", QVariant(true));
        cabutton_7->setShowLabel(false);
        cabutton_7->setProperty("bitNumber", QVariant(6u));
        cabutton_7->setSubscribe(true);
        cabutton_7->setProperty("AlarmEnable", QVariant(false));
        cabutton_8 = new CAButton(CSR);
        cabutton_8->setObjectName(QStringLiteral("cabutton_8"));
        cabutton_8->setGeometry(QRect(110, 50, 12, 12));
        cabutton_8->setCheckable(false);
        cabutton_8->setAutoDefault(false);
        cabutton_8->setOnColor(QColor(255, 0, 0));
        cabutton_8->setOffColor(QColor(120, 0, 0));
        cabutton_8->setProperty("writeOnPress", QVariant(true));
        cabutton_8->setProperty("writeOnRelease", QVariant(true));
        cabutton_8->setProperty("writeOnClick", QVariant(false));
        cabutton_8->setProperty("writeBits", QVariant(true));
        cabutton_8->setShowLabel(false);
        cabutton_8->setProperty("bitNumber", QVariant(7u));
        cabutton_8->setSubscribe(true);
        cabutton_8->setProperty("AlarmEnable", QVariant(false));
        cabutton_9 = new CAButton(CSR);
        cabutton_9->setObjectName(QStringLiteral("cabutton_9"));
        cabutton_9->setGeometry(QRect(328, 230, 12, 12));
        cabutton_9->setCheckable(true);
        cabutton_9->setAutoDefault(false);
        cabutton_9->setProperty("writeOnPress", QVariant(false));
        cabutton_9->setProperty("writeOnClick", QVariant(true));
        cabutton_9->setProperty("writeBits", QVariant(true));
        cabutton_9->setShowLabel(false);
        cabutton_9->setSubscribe(true);
        cabutton_9->setProperty("AlarmEnable", QVariant(false));
        cabutton_10 = new CAButton(CSR);
        cabutton_10->setObjectName(QStringLiteral("cabutton_10"));
        cabutton_10->setGeometry(QRect(328, 218, 12, 12));
        cabutton_10->setCheckable(true);
        cabutton_10->setAutoDefault(false);
        cabutton_10->setProperty("writeOnPress", QVariant(false));
        cabutton_10->setProperty("writeOnClick", QVariant(true));
        cabutton_10->setProperty("writeBits", QVariant(true));
        cabutton_10->setShowLabel(false);
        cabutton_10->setProperty("bitNumber", QVariant(1u));
        cabutton_10->setSubscribe(true);
        cabutton_10->setProperty("AlarmEnable", QVariant(false));
        cabutton_11 = new CAButton(CSR);
        cabutton_11->setObjectName(QStringLiteral("cabutton_11"));
        cabutton_11->setGeometry(QRect(328, 206, 12, 12));
        cabutton_11->setCheckable(true);
        cabutton_11->setAutoDefault(false);
        cabutton_11->setProperty("writeOnPress", QVariant(false));
        cabutton_11->setProperty("writeOnClick", QVariant(true));
        cabutton_11->setProperty("writeBits", QVariant(true));
        cabutton_11->setShowLabel(false);
        cabutton_11->setProperty("bitNumber", QVariant(2u));
        cabutton_11->setSubscribe(true);
        cabutton_11->setProperty("AlarmEnable", QVariant(false));
        cabutton_12 = new CAButton(CSR);
        cabutton_12->setObjectName(QStringLiteral("cabutton_12"));
        cabutton_12->setGeometry(QRect(328, 194, 12, 12));
        cabutton_12->setCheckable(true);
        cabutton_12->setAutoDefault(false);
        cabutton_12->setProperty("writeOnPress", QVariant(false));
        cabutton_12->setProperty("writeOnClick", QVariant(true));
        cabutton_12->setProperty("writeBits", QVariant(true));
        cabutton_12->setShowLabel(false);
        cabutton_12->setProperty("bitNumber", QVariant(3u));
        cabutton_12->setSubscribe(true);
        cabutton_12->setProperty("AlarmEnable", QVariant(false));
        cabutton_13 = new CAButton(CSR);
        cabutton_13->setObjectName(QStringLiteral("cabutton_13"));
        cabutton_13->setGeometry(QRect(328, 182, 12, 12));
        cabutton_13->setCheckable(true);
        cabutton_13->setAutoDefault(false);
        cabutton_13->setProperty("writeOnPress", QVariant(false));
        cabutton_13->setProperty("writeOnClick", QVariant(true));
        cabutton_13->setProperty("writeBits", QVariant(true));
        cabutton_13->setShowLabel(false);
        cabutton_13->setProperty("bitNumber", QVariant(4u));
        cabutton_13->setSubscribe(true);
        cabutton_13->setProperty("AlarmEnable", QVariant(false));
        cabutton_14 = new CAButton(CSR);
        cabutton_14->setObjectName(QStringLiteral("cabutton_14"));
        cabutton_14->setGeometry(QRect(328, 170, 12, 12));
        cabutton_14->setCheckable(true);
        cabutton_14->setAutoDefault(false);
        cabutton_14->setProperty("writeOnPress", QVariant(false));
        cabutton_14->setProperty("writeOnClick", QVariant(true));
        cabutton_14->setProperty("writeBits", QVariant(true));
        cabutton_14->setShowLabel(false);
        cabutton_14->setProperty("bitNumber", QVariant(5u));
        cabutton_14->setSubscribe(true);
        cabutton_14->setProperty("AlarmEnable", QVariant(false));
        cabutton_15 = new CAButton(CSR);
        cabutton_15->setObjectName(QStringLiteral("cabutton_15"));
        cabutton_15->setGeometry(QRect(328, 158, 12, 12));
        cabutton_15->setCheckable(true);
        cabutton_15->setAutoDefault(false);
        cabutton_15->setProperty("writeOnPress", QVariant(false));
        cabutton_15->setProperty("writeOnClick", QVariant(true));
        cabutton_15->setProperty("writeBits", QVariant(true));
        cabutton_15->setShowLabel(false);
        cabutton_15->setProperty("bitNumber", QVariant(6u));
        cabutton_15->setSubscribe(true);
        cabutton_15->setProperty("AlarmEnable", QVariant(false));
        cabutton_16 = new CAButton(CSR);
        cabutton_16->setObjectName(QStringLiteral("cabutton_16"));
        cabutton_16->setGeometry(QRect(328, 146, 12, 12));
        cabutton_16->setCheckable(true);
        cabutton_16->setAutoDefault(false);
        cabutton_16->setProperty("writeOnPress", QVariant(false));
        cabutton_16->setProperty("writeOnClick", QVariant(true));
        cabutton_16->setProperty("writeBits", QVariant(true));
        cabutton_16->setShowLabel(false);
        cabutton_16->setProperty("bitNumber", QVariant(7u));
        cabutton_16->setSubscribe(true);
        cabutton_16->setProperty("AlarmEnable", QVariant(false));
        cabutton_17 = new CAButton(CSR);
        cabutton_17->setObjectName(QStringLiteral("cabutton_17"));
        cabutton_17->setGeometry(QRect(328, 122, 12, 12));
        cabutton_17->setCheckable(true);
        cabutton_17->setAutoDefault(false);
        cabutton_17->setProperty("writeOnPress", QVariant(false));
        cabutton_17->setProperty("writeOnClick", QVariant(true));
        cabutton_17->setProperty("writeBits", QVariant(true));
        cabutton_17->setShowLabel(false);
        cabutton_17->setProperty("bitNumber", QVariant(9u));
        cabutton_17->setSubscribe(true);
        cabutton_17->setProperty("AlarmEnable", QVariant(false));
        cabutton_18 = new CAButton(CSR);
        cabutton_18->setObjectName(QStringLiteral("cabutton_18"));
        cabutton_18->setGeometry(QRect(328, 134, 12, 12));
        cabutton_18->setCheckable(false);
        cabutton_18->setAutoDefault(false);
        cabutton_18->setProperty("writeOnPress", QVariant(true));
        cabutton_18->setProperty("writeOnRelease", QVariant(true));
        cabutton_18->setProperty("writeOnClick", QVariant(false));
        cabutton_18->setProperty("writeBits", QVariant(true));
        cabutton_18->setShowLabel(false);
        cabutton_18->setProperty("bitNumber", QVariant(8u));
        cabutton_18->setSubscribe(true);
        cabutton_18->setProperty("AlarmEnable", QVariant(false));
        cabutton_19 = new CAButton(CSR);
        cabutton_19->setObjectName(QStringLiteral("cabutton_19"));
        cabutton_19->setGeometry(QRect(328, 110, 12, 12));
        cabutton_19->setCheckable(false);
        cabutton_19->setAutoDefault(false);
        cabutton_19->setProperty("writeOnPress", QVariant(true));
        cabutton_19->setProperty("writeOnRelease", QVariant(true));
        cabutton_19->setProperty("writeOnClick", QVariant(false));
        cabutton_19->setProperty("writeBits", QVariant(true));
        cabutton_19->setShowLabel(false);
        cabutton_19->setProperty("bitNumber", QVariant(10u));
        cabutton_19->setSubscribe(true);
        cabutton_19->setProperty("AlarmEnable", QVariant(false));
        cabutton_20 = new CAButton(CSR);
        cabutton_20->setObjectName(QStringLiteral("cabutton_20"));
        cabutton_20->setGeometry(QRect(328, 98, 12, 12));
        cabutton_20->setCheckable(false);
        cabutton_20->setAutoDefault(false);
        cabutton_20->setProperty("writeOnPress", QVariant(true));
        cabutton_20->setProperty("writeOnRelease", QVariant(true));
        cabutton_20->setProperty("writeOnClick", QVariant(false));
        cabutton_20->setProperty("writeBits", QVariant(true));
        cabutton_20->setShowLabel(false);
        cabutton_20->setProperty("bitNumber", QVariant(11u));
        cabutton_20->setSubscribe(true);
        cabutton_20->setProperty("AlarmEnable", QVariant(false));
        cabutton_21 = new CAButton(CSR);
        cabutton_21->setObjectName(QStringLiteral("cabutton_21"));
        cabutton_21->setGeometry(QRect(328, 74, 12, 12));
        cabutton_21->setCheckable(false);
        cabutton_21->setAutoDefault(false);
        cabutton_21->setProperty("writeOnPress", QVariant(true));
        cabutton_21->setProperty("writeOnRelease", QVariant(true));
        cabutton_21->setProperty("writeOnClick", QVariant(false));
        cabutton_21->setProperty("writeBits", QVariant(true));
        cabutton_21->setShowLabel(false);
        cabutton_21->setProperty("bitNumber", QVariant(13u));
        cabutton_21->setSubscribe(true);
        cabutton_21->setProperty("AlarmEnable", QVariant(false));
        cabutton_22 = new CAButton(CSR);
        cabutton_22->setObjectName(QStringLiteral("cabutton_22"));
        cabutton_22->setGeometry(QRect(328, 86, 12, 12));
        cabutton_22->setCheckable(false);
        cabutton_22->setAutoDefault(false);
        cabutton_22->setProperty("writeOnPress", QVariant(true));
        cabutton_22->setProperty("writeOnRelease", QVariant(true));
        cabutton_22->setProperty("writeOnClick", QVariant(false));
        cabutton_22->setProperty("writeBits", QVariant(true));
        cabutton_22->setShowLabel(false);
        cabutton_22->setProperty("bitNumber", QVariant(12u));
        cabutton_22->setSubscribe(true);
        cabutton_22->setProperty("AlarmEnable", QVariant(false));
        cabutton_23 = new CAButton(CSR);
        cabutton_23->setObjectName(QStringLiteral("cabutton_23"));
        cabutton_23->setGeometry(QRect(328, 62, 12, 12));
        cabutton_23->setCheckable(false);
        cabutton_23->setAutoDefault(false);
        cabutton_23->setProperty("writeOnPress", QVariant(true));
        cabutton_23->setProperty("writeOnRelease", QVariant(true));
        cabutton_23->setProperty("writeOnClick", QVariant(false));
        cabutton_23->setProperty("writeBits", QVariant(true));
        cabutton_23->setShowLabel(false);
        cabutton_23->setProperty("bitNumber", QVariant(14u));
        cabutton_23->setSubscribe(true);
        cabutton_23->setProperty("AlarmEnable", QVariant(false));
        qelabel = new QELabel(CSR);
        qelabel->setObjectName(QStringLiteral("qelabel"));
        qelabel->setGeometry(QRect(8, 4, 81, 25));
        QFont font2;
        font2.setPointSize(12);
        qelabel->setFont(font2);
        qelabel->setDisplayAlarmState(false);

        retranslateUi(CSR);

        QMetaObject::connectSlotsByName(CSR);
    } // setupUi

    void retranslateUi(QDialog *CSR)
    {
        CSR->setWindowTitle(QApplication::translate("CSR", "Dialog", 0));
        SB_label_15->setText(QApplication::translate("CSR", "LoadAngle 3", 0));
        SB_label_9->setText(QApplication::translate("CSR", "Ready", 0));
        SB_label_8->setText(QApplication::translate("CSR", "Warning", 0));
        SB_label_12->setText(QApplication::translate("CSR", "LoadAngle 2", 0));
        SB_label_14->setText(QApplication::translate("CSR", "Idle", 0));
        SB_label_13->setText(QApplication::translate("CSR", "RegAccess", 0));
        qelabel_7->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LI:$(Q)-$(N):SBYTE", 0)));
        qelabel_7->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        label_11->setText(QApplication::translate("CSR", "7", 0));
        SB_label_10->setText(QApplication::translate("CSR", "LoadAngle 1", 0));
        label_9->setText(QApplication::translate("CSR", "0", 0));
        label_10->setText(QApplication::translate("CSR", "StatusByte", 0));
        qebitstatus_2->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LI:$(Q)-$(N):SBYTE", 0)));
        qebitstatus_2->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        SB_label_11->setText(QApplication::translate("CSR", "Error", 0));
        qelineedit_2->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:SC:$(Q)-$(N):CBYTE", 0)));
        qelineedit_2->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        qelabel_8->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LI:$(Q)-$(N):DATA", 0)));
        qelabel_8->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        SB_label_22->setText(QApplication::translate("CSR", "Enable", 0));
        SB_label_23->setText(QApplication::translate("CSR", "Start", 0));
        label_12->setText(QApplication::translate("CSR", "ControlByte", 0));
        label_31->setText(QApplication::translate("CSR", "Data In", 0));
        SB_label_18->setText(QApplication::translate("CSR", "AutoStart", 0));
        SB_label_20->setText(QApplication::translate("CSR", "FastStop", 0));
        SB_label_19->setText(QApplication::translate("CSR", "Reset", 0));
        SB_label_17->setText(QApplication::translate("CSR", "AutoStop", 0));
        label_32->setText(QApplication::translate("CSR", "Data Out", 0));
        SB_label_16->setText(QApplication::translate("CSR", "Reduced", 0));
        SB_label_21->setText(QApplication::translate("CSR", "RegAccess", 0));
        qelineedit->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:SC:$(Q)-$(N):DATAOUT", 0)));
        qelineedit->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        SB_label_36->setText(QApplication::translate("CSR", "SetPosReady", 0));
        SB_label_37->setText(QApplication::translate("CSR", "TargetReached", 0));
        qelabel_13->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LI:$(Q)-$(N):SWORD", 0)));
        qelabel_13->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        SB_label_38->setText(QApplication::translate("CSR", "EncDisabled", 0));
        SB_label_39->setText(QApplication::translate("CSR", "LatchDataIn", 0));
        label_29->setText(QApplication::translate("CSR", "StatusWord", 0));
        SB_label_25->setText(QApplication::translate("CSR", "OverCurr B", 0));
        label_22->setText(QApplication::translate("CSR", "12", 0));
        label_28->setText(QApplication::translate("CSR", "15", 0));
        label_15->setText(QApplication::translate("CSR", "4", 0));
        qebitstatus_3->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LI:$(Q)-$(N):SWORD", 0)));
        qebitstatus_3->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        SB_label_26->setText(QApplication::translate("CSR", "OverCurr A", 0));
        SB_label_27->setText(QApplication::translate("CSR", "NoCtrlPower", 0));
        label_20->setText(QApplication::translate("CSR", "8", 0));
        label_14->setText(QApplication::translate("CSR", "3", 0));
        label_21->setText(QApplication::translate("CSR", "11", 0));
        SB_label_24->setText(QApplication::translate("CSR", "OpenLoop B", 0));
        label_19->setText(QApplication::translate("CSR", "7", 0));
        SB_label_31->setText(QApplication::translate("CSR", "OpenLoop A", 0));
        SB_label_32->setText(QApplication::translate("CSR", "Input 2", 0));
        SB_label_33->setText(QApplication::translate("CSR", "LatchValid", 0));
        SB_label_28->setText(QApplication::translate("CSR", "UnderVolt", 0));
        SB_label_34->setText(QApplication::translate("CSR", "Input 1", 0));
        SB_label_29->setText(QApplication::translate("CSR", "ConfigError", 0));
        label_13->setText(QApplication::translate("CSR", "0", 0));
        SB_label_35->setText(QApplication::translate("CSR", "LatchDataTogld", 0));
        SB_label_30->setText(QApplication::translate("CSR", "OverTemp", 0));
        qelineedit_3->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:SC:$(Q)-$(N):CWORD", 0)));
        qelineedit_3->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        SB_label_54->setText(QApplication::translate("CSR", "enLatchRiseEdge", 0));
        SB_label_52->setText(QApplication::translate("CSR", "enLatchFallEdge", 0));
        SB_label_41->setText(QApplication::translate("CSR", "SetPosInProcData", 0));
        SB_label_42->setText(QApplication::translate("CSR", "DisMixedDecay", 0));
        label_30->setText(QApplication::translate("CSR", "ControlWord", 0));
        SB_label_50->setText(QApplication::translate("CSR", "GetLatchData", 0));
        SB_label_40->setText(QApplication::translate("CSR", "GetEncPos", 0));
        SB_label_51->setText(QApplication::translate("CSR", "enLatchInput 1", 0));
        SB_label_43->setText(QApplication::translate("CSR", "ReducedCurr", 0));
        SB_label_45->setText(QApplication::translate("CSR", "ClearPosition", 0));
        SB_label_47->setText(QApplication::translate("CSR", "GetPosError", 0));
        SB_label_53->setText(QApplication::translate("CSR", "ToggleLatchData", 0));
        SB_label_46->setText(QApplication::translate("CSR", "ReducedDrivCurr", 0));
        SB_label_48->setText(QApplication::translate("CSR", "enLatchC (intrn)", 0));
        SB_label_44->setText(QApplication::translate("CSR", "SetPosition", 0));
        SB_label_49->setText(QApplication::translate("CSR", "enLatchInput 2", 0));
        label->setText(QApplication::translate("CSR", "0x", 0));
        label_2->setText(QApplication::translate("CSR", "0x", 0));
        cabutton->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CBYTE", 0)));
        cabutton->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_2->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CBYTE", 0)));
        cabutton_2->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_3->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CBYTE", 0)));
        cabutton_3->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_4->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CBYTE", 0)));
        cabutton_4->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_5->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CBYTE", 0)));
        cabutton_5->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_6->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CBYTE", 0)));
        cabutton_6->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_7->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CBYTE", 0)));
        cabutton_7->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_8->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CBYTE", 0)));
        cabutton_8->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_9->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CWORD", 0)));
        cabutton_9->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_10->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CWORD", 0)));
        cabutton_10->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_11->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CWORD", 0)));
        cabutton_11->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_12->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CWORD", 0)));
        cabutton_12->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_13->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CWORD", 0)));
        cabutton_13->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_14->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CWORD", 0)));
        cabutton_14->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_15->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CWORD", 0)));
        cabutton_15->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_16->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CWORD", 0)));
        cabutton_16->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_17->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CWORD", 0)));
        cabutton_17->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_18->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CWORD", 0)));
        cabutton_18->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_19->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CWORD", 0)));
        cabutton_19->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_20->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CWORD", 0)));
        cabutton_20->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_21->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CWORD", 0)));
        cabutton_21->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_22->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CWORD", 0)));
        cabutton_22->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        cabutton_23->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LO:$(Q)-$(N):CWORD", 0)));
        cabutton_23->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
        qelabel->setProperty("variable", QVariant(QApplication::translate("CSR", "$(P):LI:$(Q)-$(N):DATA.DESC", 0)));
        qelabel->setProperty("variableSubstitutions", QVariant(QApplication::translate("CSR", "P=CHA,Q=2531-1,N=2", 0)));
    } // retranslateUi

};

namespace Ui {
    class CSR: public Ui_CSR {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CSR_H
