/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>
#include "QELabel.h"
#include "QELineEdit.h"
#include "QEShape.h"
#include "abutton.h"
#include "ashape.h"
#include "cabutton.h"
#include "cashape.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionQuit;
    QWidget *centralwidget;
    QELabel *errMessage1;
    QELabel *qelError;
    CAShape *cashape;
    QFrame *frameX;
    QLabel *label;
    QLabel *label_2;
    QELabel *qelabel_2;
    QELabel *qelabel_3;
    QELabel *qelabel;
    QELabel *qelabel_4;
    QEShape *qeshape_4;
    QEShape *qeshape_9;
    QEShape *qeshape_3;
    QEShape *qeshape_2;
    QEShape *qeshape;
    QELabel *DenyFoXQELB;
    CAButton *REVX_PB;
    QELabel *DenyRvXQELB;
    QLabel *label_3;
    QELineEdit *qelineedit_2;
    QELabel *DenyGoXQELB;
    QLabel *label_4;
    CAButton *STOPX_PB;
    QELineEdit *qelineedit;
    CAButton *GOX_PB;
    CAButton *FORX_PB;
    QPushButton *pbMCtrlX;
    QFrame *frameY;
    QLabel *label_5;
    QLabel *label_6;
    QELabel *qelabel_5;
    QELabel *qelabel_6;
    QELabel *qelabel_7;
    QELabel *qelabel_8;
    QEShape *qeshape_5;
    QEShape *qeshape_10;
    QEShape *qeshape_6;
    QEShape *qeshape_7;
    QEShape *qeshape_8;
    QELabel *DenyFoYQELB;
    CAButton *REVY_PB;
    QELabel *DenyRvYQELB;
    QLabel *label_7;
    QELineEdit *qelineedit_3;
    QELabel *DenyGoYQELB;
    QLabel *label_8;
    CAButton *STOPY_PB;
    QELineEdit *qelineedit_4;
    CAButton *GOY_PB;
    CAButton *FORY_PB;
    QPushButton *pbMCtrlY;
    QPushButton *pbBkh;
    QMenuBar *menubar;
    QMenu *menuFile;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(415, 290);
        actionQuit = new QAction(MainWindow);
        actionQuit->setObjectName(QStringLiteral("actionQuit"));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        errMessage1 = new QELabel(centralwidget);
        errMessage1->setObjectName(QStringLiteral("errMessage1"));
        errMessage1->setGeometry(QRect(2, 246, 297, 16));
        errMessage1->setStyleSheet(QStringLiteral(""));
        errMessage1->setProperty("displayAlarmStateOption", QVariant(QELabel::Never));
        qelError = new QELabel(centralwidget);
        qelError->setObjectName(QStringLiteral("qelError"));
        qelError->setGeometry(QRect(16, 6, 56, 20));
        qelError->setStyleSheet(QStringLiteral("background: rgb(255,255,230)"));
        qelError->setAlignment(Qt::AlignCenter);
        qelError->setProperty("displayAlarmStateOption", QVariant(QELabel::Never));
        cashape = new CAShape(centralwidget);
        cashape->setObjectName(QStringLiteral("cashape"));
        cashape->setGeometry(QRect(14, 4, 60, 24));
        cashape->setLineWidth(2u);
        cashape->setProperty("rectangle", QVariant(QRect(0, 0, 60, 24)));
        cashape->setColor1(QColor(0, 255, 0));
        cashape->setColor2(QColor(255, 0, 0));
        frameX = new QFrame(centralwidget);
        frameX->setObjectName(QStringLiteral("frameX"));
        frameX->setGeometry(QRect(4, 32, 200, 204));
        frameX->setFrameShape(QFrame::Box);
        frameX->setFrameShadow(QFrame::Plain);
        label = new QLabel(frameX);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(18, 30, 29, 16));
        label_2 = new QLabel(frameX);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 46, 37, 16));
        qelabel_2 = new QELabel(frameX);
        qelabel_2->setObjectName(QStringLiteral("qelabel_2"));
        qelabel_2->setGeometry(QRect(58, 30, 89, 16));
        qelabel_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_2->setDisplayAlarmState(false);
        qelabel_2->setPrecision(2);
        qelabel_2->setUseDbPrecision(false);
        qelabel_3 = new QELabel(frameX);
        qelabel_3->setObjectName(QStringLiteral("qelabel_3"));
        qelabel_3->setGeometry(QRect(58, 46, 89, 16));
        qelabel_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_3->setDisplayAlarmState(false);
        qelabel = new QELabel(frameX);
        qelabel->setObjectName(QStringLiteral("qelabel"));
        qelabel->setGeometry(QRect(4, 6, 84, 20));
        QFont font;
        font.setPointSize(12);
        qelabel->setFont(font);
        qelabel->setDisplayAlarmState(false);
        qelabel_4 = new QELabel(frameX);
        qelabel_4->setObjectName(QStringLiteral("qelabel_4"));
        qelabel_4->setGeometry(QRect(56, 62, 77, 21));
        QFont font1;
        font1.setFamily(QStringLiteral("Monospace"));
        font1.setPointSize(10);
        font1.setBold(true);
        font1.setWeight(75);
        qelabel_4->setFont(font1);
        qelabel_4->setAlignment(Qt::AlignCenter);
        qelabel_4->setDisplayAlarmState(false);
        qeshape_4 = new QEShape(frameX);
        qeshape_4->setObjectName(QStringLiteral("qeshape_4"));
        qeshape_4->setGeometry(QRect(38, 86, 124, 17));
        qeshape_4->setProperty("point1", QVariant(QPoint(0, 1)));
        qeshape_4->setProperty("point2", QVariant(QPoint(125, 16)));
        qeshape_4->setProperty("color1", QVariant(QColor(152, 255, 249)));
        qeshape_4->setDrawBorder(false);
        qeshape_9 = new QEShape(frameX);
        qeshape_9->setObjectName(QStringLiteral("qeshape_9"));
        qeshape_9->setGeometry(QRect(162, 86, 10, 17));
        qeshape_9->setProperty("animation1", QVariant(QEShape::ColourHue));
        qeshape_9->setProperty("scale1", QVariant(-120));
        qeshape_9->setProperty("offset1", QVariant(120));
        qeshape_9->setProperty("point1", QVariant(QPoint(1, 1)));
        qeshape_9->setProperty("point2", QVariant(QPoint(8, 15)));
        qeshape_3 = new QEShape(frameX);
        qeshape_3->setObjectName(QStringLiteral("qeshape_3"));
        qeshape_3->setGeometry(QRect(28, 86, 10, 17));
        qeshape_3->setProperty("animation1", QVariant(QEShape::ColourHue));
        qeshape_3->setProperty("scale1", QVariant(-120));
        qeshape_3->setProperty("offset1", QVariant(120));
        qeshape_3->setProperty("point1", QVariant(QPoint(1, 1)));
        qeshape_3->setProperty("point2", QVariant(QPoint(8, 15)));
        qeshape_2 = new QEShape(frameX);
        qeshape_2->setObjectName(QStringLiteral("qeshape_2"));
        qeshape_2->setGeometry(QRect(38, 96, 124, 4));
        qeshape_2->setProperty("scale1", QVariant(0.005));
        qeshape_2->setProperty("offset1", QVariant(0));
        qeshape_2->setProperty("point2", QVariant(QPoint(125, 8)));
        qeshape_2->setProperty("color1", QVariant(QColor(200, 111, 135)));
        qeshape_2->setProperty("color5", QVariant(QColor(255, 157, 175)));
        qeshape_2->setProperty("color6", QVariant(QColor(250, 105, 255)));
        qeshape_2->setProperty("color7", QVariant(QColor(151, 248, 232)));
        qeshape_2->setProperty("color8", QVariant(QColor(129, 255, 140)));
        qeshape_2->setProperty("color9", QVariant(QColor(229, 255, 133)));
        qeshape_2->setProperty("color10", QVariant(QColor(255, 159, 90)));
        qeshape_2->setDrawBorder(false);
        qeshape = new QEShape(frameX);
        qeshape->setObjectName(QStringLiteral("qeshape"));
        qeshape->setGeometry(QRect(38, 90, 124, 4));
        qeshape->setProperty("animation1", QVariant(QEShape::Width));
        qeshape->setProperty("scale1", QVariant(0.005));
        qeshape->setProperty("offset1", QVariant(0));
        qeshape->setProperty("point2", QVariant(QPoint(124, 4)));
        qeshape->setProperty("color1", QVariant(QColor(118, 136, 235)));
        qeshape->setDrawBorder(false);
        DenyFoXQELB = new QELabel(frameX);
        DenyFoXQELB->setObjectName(QStringLiteral("DenyFoXQELB"));
        DenyFoXQELB->setGeometry(QRect(150, 178, 26, 15));
        DenyFoXQELB->setProperty("visible", QVariant(false));
        DenyFoXQELB->setDisplayAlarmState(false);
        REVX_PB = new CAButton(frameX);
        REVX_PB->setObjectName(QStringLiteral("REVX_PB"));
        REVX_PB->setGeometry(QRect(62, 142, 24, 24));
        QFont font2;
        font2.setFamily(QStringLiteral("Monospace"));
        font2.setBold(true);
        font2.setWeight(75);
        REVX_PB->setFont(font2);
        REVX_PB->setAutoDefault(false);
        REVX_PB->setUseTextColor(true);
        REVX_PB->setProperty("writeOnPress", QVariant(true));
        REVX_PB->setProperty("writeOnRelease", QVariant(false));
        REVX_PB->setShowLabel(true);
        REVX_PB->setSubscribe(true);
        REVX_PB->setProperty("AlarmEnable", QVariant(false));
        REVX_PB->setLiteralLabel(true);
        DenyRvXQELB = new QELabel(frameX);
        DenyRvXQELB->setObjectName(QStringLiteral("DenyRvXQELB"));
        DenyRvXQELB->setGeometry(QRect(52, 178, 26, 15));
        DenyRvXQELB->setProperty("visible", QVariant(false));
        DenyRvXQELB->setDisplayAlarmState(false);
        label_3 = new QLabel(frameX);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(14, 110, 56, 24));
        qelineedit_2 = new QELineEdit(frameX);
        qelineedit_2->setObjectName(QStringLiteral("qelineedit_2"));
        qelineedit_2->setGeometry(QRect(90, 142, 72, 24));
        qelineedit_2->setUseDbPrecision(true);
        qelineedit_2->setAddUnits(true);
        DenyGoXQELB = new QELabel(frameX);
        DenyGoXQELB->setObjectName(QStringLiteral("DenyGoXQELB"));
        DenyGoXQELB->setGeometry(QRect(22, 178, 26, 15));
        DenyGoXQELB->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        DenyGoXQELB->setProperty("visible", QVariant(false));
        DenyGoXQELB->setDisplayAlarmState(false);
        label_4 = new QLabel(frameX);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 142, 49, 24));
        STOPX_PB = new CAButton(frameX);
        STOPX_PB->setObjectName(QStringLiteral("STOPX_PB"));
        STOPX_PB->setGeometry(QRect(86, 174, 56, 24));
        STOPX_PB->setFont(font2);
        STOPX_PB->setAutoDefault(false);
        STOPX_PB->setOnColor(QColor(180, 20, 60));
        STOPX_PB->setOffColor(QColor(240, 20, 60));
        STOPX_PB->setUseTextColor(true);
        STOPX_PB->setTextColor(QColor(255, 240, 200));
        STOPX_PB->setSubscribe(true);
        STOPX_PB->setProperty("AlarmEnable", QVariant(false));
        STOPX_PB->setLiteralLabel(true);
        qelineedit = new QELineEdit(frameX);
        qelineedit->setObjectName(QStringLiteral("qelineedit"));
        qelineedit->setGeometry(QRect(76, 110, 78, 24));
        qelineedit->setUseDbPrecision(true);
        qelineedit->setAddUnits(true);
        GOX_PB = new CAButton(frameX);
        GOX_PB->setObjectName(QStringLiteral("GOX_PB"));
        GOX_PB->setGeometry(QRect(158, 110, 32, 24));
        GOX_PB->setAutoDefault(false);
        GOX_PB->setUseTextColor(true);
        GOX_PB->setProperty("writeOnPress", QVariant(true));
        GOX_PB->setProperty("writeOnRelease", QVariant(false));
        GOX_PB->setSubscribe(true);
        GOX_PB->setProperty("AlarmEnable", QVariant(false));
        GOX_PB->setLiteralLabel(true);
        FORX_PB = new CAButton(frameX);
        FORX_PB->setObjectName(QStringLiteral("FORX_PB"));
        FORX_PB->setGeometry(QRect(166, 142, 24, 24));
        FORX_PB->setFont(font2);
        FORX_PB->setAutoDefault(false);
        FORX_PB->setUseTextColor(true);
        FORX_PB->setProperty("writeOnPress", QVariant(true));
        FORX_PB->setProperty("writeOnRelease", QVariant(false));
        FORX_PB->setShowLabel(true);
        FORX_PB->setSubscribe(true);
        FORX_PB->setProperty("AlarmEnable", QVariant(false));
        FORX_PB->setLiteralLabel(true);
        pbMCtrlX = new QPushButton(frameX);
        pbMCtrlX->setObjectName(QStringLiteral("pbMCtrlX"));
        pbMCtrlX->setGeometry(QRect(114, 6, 80, 20));
        pbMCtrlX->raise();
        label->raise();
        label_2->raise();
        qelabel_2->raise();
        qelabel_3->raise();
        qelabel->raise();
        qelabel_4->raise();
        qeshape_4->raise();
        qeshape_9->raise();
        qeshape_3->raise();
        qeshape_2->raise();
        qeshape->raise();
        DenyFoXQELB->raise();
        REVX_PB->raise();
        DenyRvXQELB->raise();
        label_3->raise();
        qelineedit_2->raise();
        DenyGoXQELB->raise();
        label_4->raise();
        STOPX_PB->raise();
        qelineedit->raise();
        GOX_PB->raise();
        FORX_PB->raise();
        frameY = new QFrame(centralwidget);
        frameY->setObjectName(QStringLiteral("frameY"));
        frameY->setGeometry(QRect(210, 32, 200, 204));
        frameY->setFrameShape(QFrame::Box);
        frameY->setFrameShadow(QFrame::Plain);
        label_5 = new QLabel(frameY);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(18, 30, 29, 16));
        label_6 = new QLabel(frameY);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 46, 37, 16));
        qelabel_5 = new QELabel(frameY);
        qelabel_5->setObjectName(QStringLiteral("qelabel_5"));
        qelabel_5->setGeometry(QRect(58, 30, 89, 16));
        qelabel_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_5->setDisplayAlarmState(false);
        qelabel_5->setPrecision(2);
        qelabel_5->setUseDbPrecision(false);
        qelabel_6 = new QELabel(frameY);
        qelabel_6->setObjectName(QStringLiteral("qelabel_6"));
        qelabel_6->setGeometry(QRect(58, 46, 89, 16));
        qelabel_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_6->setDisplayAlarmState(false);
        qelabel_7 = new QELabel(frameY);
        qelabel_7->setObjectName(QStringLiteral("qelabel_7"));
        qelabel_7->setGeometry(QRect(4, 6, 84, 20));
        qelabel_7->setFont(font);
        qelabel_7->setDisplayAlarmState(false);
        qelabel_8 = new QELabel(frameY);
        qelabel_8->setObjectName(QStringLiteral("qelabel_8"));
        qelabel_8->setGeometry(QRect(56, 62, 77, 21));
        qelabel_8->setFont(font1);
        qelabel_8->setAlignment(Qt::AlignCenter);
        qelabel_8->setDisplayAlarmState(false);
        qeshape_5 = new QEShape(frameY);
        qeshape_5->setObjectName(QStringLiteral("qeshape_5"));
        qeshape_5->setGeometry(QRect(38, 86, 124, 17));
        qeshape_5->setProperty("point1", QVariant(QPoint(0, 1)));
        qeshape_5->setProperty("point2", QVariant(QPoint(125, 16)));
        qeshape_5->setProperty("color1", QVariant(QColor(152, 255, 249)));
        qeshape_5->setDrawBorder(false);
        qeshape_10 = new QEShape(frameY);
        qeshape_10->setObjectName(QStringLiteral("qeshape_10"));
        qeshape_10->setGeometry(QRect(162, 86, 10, 17));
        qeshape_10->setProperty("animation1", QVariant(QEShape::ColourHue));
        qeshape_10->setProperty("scale1", QVariant(-120));
        qeshape_10->setProperty("offset1", QVariant(120));
        qeshape_10->setProperty("point1", QVariant(QPoint(1, 1)));
        qeshape_10->setProperty("point2", QVariant(QPoint(8, 15)));
        qeshape_6 = new QEShape(frameY);
        qeshape_6->setObjectName(QStringLiteral("qeshape_6"));
        qeshape_6->setGeometry(QRect(28, 86, 10, 17));
        qeshape_6->setProperty("animation1", QVariant(QEShape::ColourHue));
        qeshape_6->setProperty("scale1", QVariant(-120));
        qeshape_6->setProperty("offset1", QVariant(120));
        qeshape_6->setProperty("point1", QVariant(QPoint(1, 1)));
        qeshape_6->setProperty("point2", QVariant(QPoint(8, 15)));
        qeshape_7 = new QEShape(frameY);
        qeshape_7->setObjectName(QStringLiteral("qeshape_7"));
        qeshape_7->setGeometry(QRect(38, 96, 124, 4));
        qeshape_7->setProperty("scale1", QVariant(0.005));
        qeshape_7->setProperty("offset1", QVariant(0));
        qeshape_7->setProperty("point2", QVariant(QPoint(125, 8)));
        qeshape_7->setProperty("color1", QVariant(QColor(200, 111, 135)));
        qeshape_7->setProperty("color5", QVariant(QColor(255, 157, 175)));
        qeshape_7->setProperty("color6", QVariant(QColor(250, 105, 255)));
        qeshape_7->setProperty("color7", QVariant(QColor(151, 248, 232)));
        qeshape_7->setProperty("color8", QVariant(QColor(129, 255, 140)));
        qeshape_7->setProperty("color9", QVariant(QColor(229, 255, 133)));
        qeshape_7->setProperty("color10", QVariant(QColor(255, 159, 90)));
        qeshape_7->setDrawBorder(false);
        qeshape_8 = new QEShape(frameY);
        qeshape_8->setObjectName(QStringLiteral("qeshape_8"));
        qeshape_8->setGeometry(QRect(38, 90, 124, 4));
        qeshape_8->setProperty("animation1", QVariant(QEShape::Width));
        qeshape_8->setProperty("scale1", QVariant(0.005));
        qeshape_8->setProperty("offset1", QVariant(0));
        qeshape_8->setProperty("point2", QVariant(QPoint(124, 4)));
        qeshape_8->setProperty("color1", QVariant(QColor(118, 136, 235)));
        qeshape_8->setDrawBorder(false);
        DenyFoYQELB = new QELabel(frameY);
        DenyFoYQELB->setObjectName(QStringLiteral("DenyFoYQELB"));
        DenyFoYQELB->setGeometry(QRect(150, 178, 26, 15));
        DenyFoYQELB->setProperty("visible", QVariant(false));
        DenyFoYQELB->setDisplayAlarmState(false);
        REVY_PB = new CAButton(frameY);
        REVY_PB->setObjectName(QStringLiteral("REVY_PB"));
        REVY_PB->setGeometry(QRect(62, 142, 24, 24));
        REVY_PB->setFont(font2);
        REVY_PB->setAutoDefault(false);
        REVY_PB->setUseTextColor(true);
        REVY_PB->setProperty("writeOnPress", QVariant(true));
        REVY_PB->setProperty("writeOnRelease", QVariant(false));
        REVY_PB->setShowLabel(true);
        REVY_PB->setSubscribe(true);
        REVY_PB->setProperty("AlarmEnable", QVariant(false));
        REVY_PB->setLiteralLabel(true);
        DenyRvYQELB = new QELabel(frameY);
        DenyRvYQELB->setObjectName(QStringLiteral("DenyRvYQELB"));
        DenyRvYQELB->setGeometry(QRect(52, 178, 26, 15));
        DenyRvYQELB->setProperty("visible", QVariant(false));
        DenyRvYQELB->setDisplayAlarmState(false);
        label_7 = new QLabel(frameY);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(14, 110, 56, 24));
        qelineedit_3 = new QELineEdit(frameY);
        qelineedit_3->setObjectName(QStringLiteral("qelineedit_3"));
        qelineedit_3->setGeometry(QRect(90, 142, 72, 24));
        qelineedit_3->setUseDbPrecision(true);
        qelineedit_3->setAddUnits(true);
        DenyGoYQELB = new QELabel(frameY);
        DenyGoYQELB->setObjectName(QStringLiteral("DenyGoYQELB"));
        DenyGoYQELB->setGeometry(QRect(22, 178, 26, 15));
        DenyGoYQELB->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        DenyGoYQELB->setProperty("visible", QVariant(false));
        DenyGoYQELB->setDisplayAlarmState(false);
        label_8 = new QLabel(frameY);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 142, 49, 24));
        STOPY_PB = new CAButton(frameY);
        STOPY_PB->setObjectName(QStringLiteral("STOPY_PB"));
        STOPY_PB->setGeometry(QRect(86, 174, 56, 24));
        STOPY_PB->setFont(font2);
        STOPY_PB->setAutoDefault(false);
        STOPY_PB->setOnColor(QColor(180, 20, 60));
        STOPY_PB->setOffColor(QColor(240, 20, 60));
        STOPY_PB->setUseTextColor(true);
        STOPY_PB->setTextColor(QColor(255, 240, 200));
        STOPY_PB->setSubscribe(true);
        STOPY_PB->setProperty("AlarmEnable", QVariant(false));
        STOPY_PB->setLiteralLabel(true);
        qelineedit_4 = new QELineEdit(frameY);
        qelineedit_4->setObjectName(QStringLiteral("qelineedit_4"));
        qelineedit_4->setGeometry(QRect(76, 110, 78, 24));
        qelineedit_4->setUseDbPrecision(true);
        qelineedit_4->setAddUnits(true);
        GOY_PB = new CAButton(frameY);
        GOY_PB->setObjectName(QStringLiteral("GOY_PB"));
        GOY_PB->setGeometry(QRect(158, 110, 32, 24));
        GOY_PB->setAutoDefault(false);
        GOY_PB->setUseTextColor(true);
        GOY_PB->setProperty("writeOnPress", QVariant(true));
        GOY_PB->setProperty("writeOnRelease", QVariant(false));
        GOY_PB->setSubscribe(true);
        GOY_PB->setProperty("AlarmEnable", QVariant(false));
        GOY_PB->setLiteralLabel(true);
        FORY_PB = new CAButton(frameY);
        FORY_PB->setObjectName(QStringLiteral("FORY_PB"));
        FORY_PB->setGeometry(QRect(166, 142, 24, 24));
        FORY_PB->setFont(font2);
        FORY_PB->setAutoDefault(false);
        FORY_PB->setUseTextColor(true);
        FORY_PB->setProperty("writeOnPress", QVariant(true));
        FORY_PB->setProperty("writeOnRelease", QVariant(false));
        FORY_PB->setShowLabel(true);
        FORY_PB->setSubscribe(true);
        FORY_PB->setProperty("AlarmEnable", QVariant(false));
        FORY_PB->setLiteralLabel(true);
        pbMCtrlY = new QPushButton(frameY);
        pbMCtrlY->setObjectName(QStringLiteral("pbMCtrlY"));
        pbMCtrlY->setGeometry(QRect(114, 6, 80, 20));
        pbBkh = new QPushButton(centralwidget);
        pbBkh->setObjectName(QStringLiteral("pbBkh"));
        pbBkh->setGeometry(QRect(324, 6, 80, 20));
        MainWindow->setCentralWidget(centralwidget);
        frameX->raise();
        cashape->raise();
        errMessage1->raise();
        qelError->raise();
        frameY->raise();
        pbBkh->raise();
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 415, 20));
        menuFile = new QMenu(menubar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        MainWindow->setStatusBar(statusbar);
#ifndef QT_NO_SHORTCUT
#endif // QT_NO_SHORTCUT

        menubar->addAction(menuFile->menuAction());
        menuFile->addAction(actionQuit);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        actionQuit->setText(QApplication::translate("MainWindow", "Quit", 0));
        actionQuit->setShortcut(QApplication::translate("MainWindow", "Ctrl+Q", 0));
        errMessage1->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):WF:BKHERR-$(N):MESSAGE", 0)));
        errMessage1->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,N=2", 0)));
        qelError->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BI:BKHERR-$(N):ERROR", 0)));
        qelError->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,N=2", 0)));
        cashape->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BI:BKHERR-$(N):ERROR", 0)));
        cashape->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,N=2", 0)));
        label->setText(QApplication::translate("MainWindow", "RBV", 0));
        label_2->setText(QApplication::translate("MainWindow", "Steps", 0));
        qelabel_2->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):CALC:$(R)-$(N):CH$(C)", 0)));
        qelabel_2->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,R=3132,N=2,C=1", 0)));
        qelabel_3->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):CALC:$(Q)-$(N):CH1:POS:MM", 0)));
        qelabel_3->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        qelabel->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:$(Q)-$(N):DATA.DESC", 0)));
        qelabel->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        qelabel_4->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):MBBI:$(Q)-$(N):CH1:MOTOR:STATE", 0)));
        qelabel_4->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        qeshape_9->setProperty("variable1", QVariant(QApplication::translate("MainWindow", "$(P):BI:$(Q)-$(N):CH1:LIM:FOR", 0)));
        qeshape_9->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        qeshape_3->setProperty("variable1", QVariant(QApplication::translate("MainWindow", "$(P):BI:$(Q)-$(N):CH1:LIM:REV", 0)));
        qeshape_3->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        qeshape_2->setProperty("variable1", QVariant(QApplication::translate("MainWindow", "$(P):AO:$(Q)-$(N):CH1:SET:POS:MM", 0)));
        qeshape_2->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        qeshape->setProperty("variable1", QVariant(QApplication::translate("MainWindow", "$(P):CALC:$(Q)-$(N):CH1:POS:MM", 0)));
        qeshape->setProperty("variable2", QVariant(QString()));
        qeshape->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        DenyFoXQELB->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BI:$(Q)-$(N):CH1:DENYFO", 0)));
        DenyFoXQELB->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        REVX_PB->setText(QApplication::translate("MainWindow", "<", 0));
        REVX_PB->setOnText(QApplication::translate("MainWindow", "Yes", 0));
        REVX_PB->setOffText(QApplication::translate("MainWindow", "Not", 0));
        REVX_PB->setOnLabel(QApplication::translate("MainWindow", "<", 0));
        REVX_PB->setOffLabel(QApplication::translate("MainWindow", "<", 0));
        REVX_PB->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:$(Q)-$(N):CH1:JOG:REV", 0)));
        REVX_PB->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        DenyRvXQELB->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BI:$(Q)-$(N):CH1:DENYRV", 0)));
        DenyRvXQELB->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        label_3->setText(QApplication::translate("MainWindow", "Absolute", 0));
        qelineedit_2->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:$(Q)-$(N):CH1:SET:INC:MM", 0)));
        qelineedit_2->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        DenyGoXQELB->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BI:$(Q)-$(N):CH1:DENYGO", 0)));
        DenyGoXQELB->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        label_4->setText(QApplication::translate("MainWindow", "Relative", 0));
        STOPX_PB->setOnText(QApplication::translate("MainWindow", "Yes", 0));
        STOPX_PB->setOffText(QApplication::translate("MainWindow", "Not", 0));
        STOPX_PB->setOnLabel(QApplication::translate("MainWindow", "STOP", 0));
        STOPX_PB->setOffLabel(QApplication::translate("MainWindow", "STOP", 0));
        STOPX_PB->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:$(Q)-$(N):CH1:STOP", 0)));
        STOPX_PB->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        qelineedit->setText(QApplication::translate("MainWindow", "140.00 mm", 0));
        qelineedit->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:SC:$(Q)-$(N):CH1:SET:POS:MM", 0)));
        qelineedit->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        GOX_PB->setOnText(QApplication::translate("MainWindow", "Yes", 0));
        GOX_PB->setOffText(QApplication::translate("MainWindow", "Not", 0));
        GOX_PB->setOnLabel(QApplication::translate("MainWindow", "Go", 0));
        GOX_PB->setOffLabel(QApplication::translate("MainWindow", "Go", 0));
        GOX_PB->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:$(Q)-$(N):CH1:GO:POS", 0)));
        GOX_PB->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        FORX_PB->setText(QApplication::translate("MainWindow", ">", 0));
        FORX_PB->setOnText(QApplication::translate("MainWindow", "Yes", 0));
        FORX_PB->setOffText(QApplication::translate("MainWindow", "Not", 0));
        FORX_PB->setOnLabel(QApplication::translate("MainWindow", ">", 0));
        FORX_PB->setOffLabel(QApplication::translate("MainWindow", ">", 0));
        FORX_PB->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:$(Q)-$(N):CH1:JOG:FOR", 0)));
        FORX_PB->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        pbMCtrlX->setText(QApplication::translate("MainWindow", "Control", 0));
        label_5->setText(QApplication::translate("MainWindow", "RBV", 0));
        label_6->setText(QApplication::translate("MainWindow", "Steps", 0));
        qelabel_5->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):CALC:$(R)-$(N):CH$(C)", 0)));
        qelabel_5->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,R=3132,N=2,C=2", 0)));
        qelabel_6->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):CALC:$(Q)-$(N):CH1:POS:MM", 0)));
        qelabel_6->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-2,N=2", 0)));
        qelabel_7->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LI:$(Q)-$(N):DATA.DESC", 0)));
        qelabel_7->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-2,N=2", 0)));
        qelabel_8->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):MBBI:$(Q)-$(N):CH1:MOTOR:STATE", 0)));
        qelabel_8->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-1,N=2", 0)));
        qeshape_10->setProperty("variable1", QVariant(QApplication::translate("MainWindow", "$(P):BI:$(Q)-$(N):CH1:LIM:FOR", 0)));
        qeshape_10->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-2,N=2", 0)));
        qeshape_6->setProperty("variable1", QVariant(QApplication::translate("MainWindow", "$(P):BI:$(Q)-$(N):CH1:LIM:REV", 0)));
        qeshape_6->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-2,N=2", 0)));
        qeshape_7->setProperty("variable1", QVariant(QApplication::translate("MainWindow", "$(P):AO:$(Q)-$(N):CH1:SET:POS:MM", 0)));
        qeshape_7->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-2,N=2", 0)));
        qeshape_8->setProperty("variable1", QVariant(QApplication::translate("MainWindow", "$(P):CALC:$(Q)-$(N):CH1:POS:MM", 0)));
        qeshape_8->setProperty("variable2", QVariant(QString()));
        qeshape_8->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-2,N=2", 0)));
        DenyFoYQELB->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BI:$(Q)-$(N):CH1:DENYFO", 0)));
        DenyFoYQELB->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-2,N=2", 0)));
        REVY_PB->setText(QApplication::translate("MainWindow", "<", 0));
        REVY_PB->setOnText(QApplication::translate("MainWindow", "Yes", 0));
        REVY_PB->setOffText(QApplication::translate("MainWindow", "Not", 0));
        REVY_PB->setOnLabel(QApplication::translate("MainWindow", "<", 0));
        REVY_PB->setOffLabel(QApplication::translate("MainWindow", "<", 0));
        REVY_PB->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:$(Q)-$(N):CH1:JOG:REV", 0)));
        REVY_PB->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-2,N=2", 0)));
        DenyRvYQELB->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BI:$(Q)-$(N):CH1:DENYRV", 0)));
        DenyRvYQELB->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-2,N=2", 0)));
        label_7->setText(QApplication::translate("MainWindow", "Absolute", 0));
        qelineedit_3->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:$(Q)-$(N):CH1:SET:INC:MM", 0)));
        qelineedit_3->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-2,N=2", 0)));
        DenyGoYQELB->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BI:$(Q)-$(N):CH1:DENYGO", 0)));
        DenyGoYQELB->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-2,N=2", 0)));
        label_8->setText(QApplication::translate("MainWindow", "Relative", 0));
        STOPY_PB->setOnText(QApplication::translate("MainWindow", "Yes", 0));
        STOPY_PB->setOffText(QApplication::translate("MainWindow", "Not", 0));
        STOPY_PB->setOnLabel(QApplication::translate("MainWindow", "STOP", 0));
        STOPY_PB->setOffLabel(QApplication::translate("MainWindow", "STOP", 0));
        STOPY_PB->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:$(Q)-$(N):CH1:STOP", 0)));
        STOPY_PB->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-2,N=2", 0)));
        qelineedit_4->setText(QApplication::translate("MainWindow", "50.00 mm", 0));
        qelineedit_4->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:SC:$(Q)-$(N):CH1:SET:POS:MM", 0)));
        qelineedit_4->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-2,N=2", 0)));
        GOY_PB->setOnText(QApplication::translate("MainWindow", "Yes", 0));
        GOY_PB->setOffText(QApplication::translate("MainWindow", "Not", 0));
        GOY_PB->setOnLabel(QApplication::translate("MainWindow", "Go", 0));
        GOY_PB->setOffLabel(QApplication::translate("MainWindow", "Go", 0));
        GOY_PB->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:$(Q)-$(N):CH1:GO:POS", 0)));
        GOY_PB->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-2,N=2", 0)));
        FORY_PB->setText(QApplication::translate("MainWindow", ">", 0));
        FORY_PB->setOnText(QApplication::translate("MainWindow", "Yes", 0));
        FORY_PB->setOffText(QApplication::translate("MainWindow", "Not", 0));
        FORY_PB->setOnLabel(QApplication::translate("MainWindow", ">", 0));
        FORY_PB->setOffLabel(QApplication::translate("MainWindow", ">", 0));
        FORY_PB->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:$(Q)-$(N):CH1:JOG:FOR", 0)));
        FORY_PB->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA,Q=2531-2,N=2", 0)));
        pbMCtrlY->setText(QApplication::translate("MainWindow", "Control", 0));
        pbBkh->setText(QApplication::translate("MainWindow", "Bkh More...", 0));
        menuFile->setTitle(QApplication::translate("MainWindow", "File", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
