/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>
#include "QELabel.h"
#include "QELineEdit.h"
#include "abutton.h"
#include "aplot.h"
#include "cabutton.h"
#include "camvbutton.h"
#include "caplot.h"
#include "knob.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionQuit;
    QWidget *centralwidget;
    QGroupBox *scopeArea;
    QELabel *trigState;
    CAPlot *caplot;
    QLabel *ch1Label;
    QELabel *ch1VDiv;
    QELabel *ch3VDiv;
    QLabel *ch3Label;
    QELabel *ch2VDiv;
    QLabel *ch2Label;
    QELabel *ch4VDiv;
    QLabel *ch4Label;
    QELabel *idnLabel;
    QTabWidget *tabWidget;
    QWidget *mainTab;
    CAMVButton *tbaseUnit;
    QELineEdit *timeScale;
    Knob *tBaseKnob;
    QPushButton *tBaseDown;
    QELineEdit *tBaseOfst;
    QPushButton *tBaseUp;
    Knob *hPosKnob;
    QFrame *timeFrame;
    QLabel *label;
    QLabel *label_8;
    Knob *ch4KnobY;
    Knob *ch4KnobV;
    QPushButton *ch4Up;
    QELineEdit *ch4Scale;
    QPushButton *ch4Down;
    QELineEdit *ch4YPos;
    CAButton *ch4CAEn;
    QFrame *ch4Frame;
    QFrame *ch3Frame;
    Knob *ch3KnobV;
    CAButton *ch3CAEn;
    QPushButton *ch3Up;
    QELineEdit *ch3Scale;
    QPushButton *ch3Down;
    Knob *ch3KnobY;
    QELineEdit *ch3YPos;
    QFrame *ch2Frame;
    QPushButton *ch2Down;
    QELineEdit *ch2Scale;
    QELineEdit *ch2YPos;
    Knob *ch2KnobY;
    CAButton *ch2CAEn;
    QPushButton *ch2Up;
    Knob *ch2KnobV;
    QFrame *ch1Frame;
    Knob *ch1KnobV;
    Knob *ch1KnobY;
    QPushButton *ch1Up;
    QPushButton *ch1Down;
    QELineEdit *ch1YPos;
    QELineEdit *ch1Scale;
    CAButton *ch1CAEn;
    CAMVButton *trigSource;
    CAMVButton *trigSlopeBut;
    CAMVButton *trigSweep;
    Knob *tLevKnob;
    QELineEdit *trigLevl;
    QFrame *trigFrame;
    QLabel *label_3;
    QLabel *label_2;
    QLabel *label_4;
    CAButton *runStopBut;
    QLabel *label_5;
    QELabel *qelabel;
    QLabel *label_6;
    QLabel *label_7;
    CAButton *runStopBut_2;
    QWidget *horTab;
    QWidget *trigTab;
    QWidget *tab;
    QMenuBar *menubar;
    QMenu *menuFile;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(867, 473);
        MainWindow->setStyleSheet(QStringLiteral(""));
        actionQuit = new QAction(MainWindow);
        actionQuit->setObjectName(QStringLiteral("actionQuit"));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        scopeArea = new QGroupBox(centralwidget);
        scopeArea->setObjectName(QStringLiteral("scopeArea"));
        scopeArea->setGeometry(QRect(8, 4, 485, 413));
        scopeArea->setStyleSheet(QStringLiteral("background:rgb(35,45,70)"));
        trigState = new QELabel(scopeArea);
        trigState->setObjectName(QStringLiteral("trigState"));
        trigState->setGeometry(QRect(420, 12, 48, 16));
        trigState->setStyleSheet(QStringLiteral(""));
        trigState->setDisplayAlarmState(false);
        caplot = new CAPlot(scopeArea);
        caplot->setObjectName(QStringLiteral("caplot"));
        caplot->setGeometry(QRect(14, 40, 454, 300));
        caplot->setFrameShadow(false);
        caplot->setAutoScaleX(false);
        caplot->setAxisEnableX(false);
        caplot->setProperty("gridEnableMajorX", QVariant(true));
        caplot->setXMax(500);
        caplot->setNTicksMajorX(10);
        caplot->setAutoScaleY(false);
        caplot->setAxisEnableY(false);
        caplot->setProperty("gridEnableMajorY", QVariant(true));
        caplot->setYMin(-4);
        caplot->setYMax(4);
        caplot->setProperty("gridMajorColor", QVariant(QColor(95, 105, 120)));
        caplot->setProperty("gridMinorColor", QVariant(QColor(80, 90, 105)));
        caplot->setProperty("backgroundColor", QVariant(QColor(35, 45, 70)));
        caplot->setTraceColor1(QColor(255, 200, 100));
        caplot->setTraceColor2(QColor(0, 255, 255));
        caplot->setTraceColor3(QColor(255, 0, 255));
        caplot->setTraceColor4(QColor(80, 80, 220));
        caplot->setProperty("Marker1Enable", QVariant(true));
        caplot->setDisplayAlarmState(false);
        ch1Label = new QLabel(centralwidget);
        ch1Label->setObjectName(QStringLiteral("ch1Label"));
        ch1Label->setGeometry(QRect(28, 360, 25, 16));
        ch1Label->setAutoFillBackground(false);
        ch1Label->setStyleSheet(QStringLiteral("background:rgb(255,220,200)"));
        ch1VDiv = new QELabel(centralwidget);
        ch1VDiv->setObjectName(QStringLiteral("ch1VDiv"));
        ch1VDiv->setGeometry(QRect(52, 360, 77, 16));
        ch1VDiv->setAutoFillBackground(false);
        ch1VDiv->setStyleSheet(QStringLiteral(""));
        ch1VDiv->setDisplayAlarmState(false);
        ch1VDiv->setPrecision(3);
        ch1VDiv->setUseDbPrecision(false);
        ch3VDiv = new QELabel(centralwidget);
        ch3VDiv->setObjectName(QStringLiteral("ch3VDiv"));
        ch3VDiv->setGeometry(QRect(52, 380, 77, 16));
        ch3VDiv->setAutoFillBackground(false);
        ch3VDiv->setStyleSheet(QStringLiteral(""));
        ch3VDiv->setDisplayAlarmState(false);
        ch3VDiv->setPrecision(3);
        ch3VDiv->setUseDbPrecision(false);
        ch3Label = new QLabel(centralwidget);
        ch3Label->setObjectName(QStringLiteral("ch3Label"));
        ch3Label->setGeometry(QRect(28, 380, 25, 16));
        ch3Label->setAutoFillBackground(false);
        ch3Label->setStyleSheet(QStringLiteral("background:rgb(255,220,200)"));
        ch2VDiv = new QELabel(centralwidget);
        ch2VDiv->setObjectName(QStringLiteral("ch2VDiv"));
        ch2VDiv->setGeometry(QRect(160, 360, 77, 16));
        ch2VDiv->setAutoFillBackground(false);
        ch2VDiv->setStyleSheet(QStringLiteral(""));
        ch2VDiv->setDisplayAlarmState(false);
        ch2VDiv->setPrecision(3);
        ch2VDiv->setUseDbPrecision(false);
        ch2Label = new QLabel(centralwidget);
        ch2Label->setObjectName(QStringLiteral("ch2Label"));
        ch2Label->setGeometry(QRect(136, 360, 25, 16));
        ch2Label->setAutoFillBackground(false);
        ch2Label->setStyleSheet(QStringLiteral("background:rgb(255,220,200)"));
        ch4VDiv = new QELabel(centralwidget);
        ch4VDiv->setObjectName(QStringLiteral("ch4VDiv"));
        ch4VDiv->setGeometry(QRect(160, 380, 77, 16));
        ch4VDiv->setAutoFillBackground(false);
        ch4VDiv->setStyleSheet(QStringLiteral(""));
        ch4VDiv->setDisplayAlarmState(false);
        ch4VDiv->setPrecision(3);
        ch4VDiv->setUseDbPrecision(false);
        ch4Label = new QLabel(centralwidget);
        ch4Label->setObjectName(QStringLiteral("ch4Label"));
        ch4Label->setGeometry(QRect(136, 380, 25, 16));
        ch4Label->setAutoFillBackground(false);
        ch4Label->setStyleSheet(QStringLiteral("background:rgb(255,220,200)"));
        idnLabel = new QELabel(centralwidget);
        idnLabel->setObjectName(QStringLiteral("idnLabel"));
        idnLabel->setGeometry(QRect(2, 424, 357, 16));
        idnLabel->setLineWidth(0);
        idnLabel->setDisplayAlarmState(false);
        tabWidget = new QTabWidget(centralwidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(518, 16, 341, 403));
        mainTab = new QWidget();
        mainTab->setObjectName(QStringLiteral("mainTab"));
        tbaseUnit = new CAMVButton(mainTab);
        tbaseUnit->setObjectName(QStringLiteral("tbaseUnit"));
        tbaseUnit->setGeometry(QRect(72, 150, 24, 20));
        tbaseUnit->setStyleSheet(QStringLiteral(""));
        tbaseUnit->setFlat(false);
        tbaseUnit->setOffColor(QColor(200, 210, 220));
        tbaseUnit->setUseTextColor(true);
        tbaseUnit->setProperty("AlarmEnable", QVariant(false));
        timeScale = new QELineEdit(mainTab);
        timeScale->setObjectName(QStringLiteral("timeScale"));
        timeScale->setGeometry(QRect(24, 150, 48, 20));
        timeScale->setDisplayAlarmState(false);
        tBaseKnob = new Knob(mainTab);
        tBaseKnob->setObjectName(QStringLiteral("tBaseKnob"));
        tBaseKnob->setGeometry(QRect(30, 86, 60, 60));
        tBaseKnob->setScaleMaxMajor(0);
        tBaseKnob->setScaleMaxMinor(0);
        tBaseKnob->setScaleStepSize(1);
        tBaseKnob->setTotalSteps(999u);
        tBaseKnob->setStepAlignment(true);
        tBaseKnob->setTracking(false);
        tBaseKnob->setWrapping(false);
        tBaseKnob->setKnobStyle(QwtKnob::Raised);
        tBaseKnob->setKnobWidth(40);
        tBaseKnob->setTotalAngle(720);
        tBaseKnob->setNumTurns(2);
        tBaseKnob->setMarkerStyle(QwtKnob::Tick);
        tBaseKnob->setSubscribe(true);
        tBaseKnob->setHaveScale(false);
        tBaseKnob->setProperty("minValue", QVariant(1));
        tBaseKnob->setProperty("maxValue", QVariant(999));
        tBaseKnob->setProperty("valueIncrement", QVariant(1));
        tBaseDown = new QPushButton(mainTab);
        tBaseDown->setObjectName(QStringLiteral("tBaseDown"));
        tBaseDown->setGeometry(QRect(82, 122, 16, 16));
        tBaseDown->setStyleSheet(QStringLiteral("background:rgb(0,0,0,0)"));
        QIcon icon;
        icon.addFile(QStringLiteral("down.xpm"), QSize(), QIcon::Normal, QIcon::Off);
        tBaseDown->setIcon(icon);
        tBaseDown->setIconSize(QSize(15, 15));
        tBaseDown->setFlat(true);
        tBaseOfst = new QELineEdit(mainTab);
        tBaseOfst->setObjectName(QStringLiteral("tBaseOfst"));
        tBaseOfst->setGeometry(QRect(110, 150, 69, 20));
        tBaseOfst->setDisplayAlarmState(false);
        tBaseOfst->setPrecision(6);
        tBaseOfst->setUseDbPrecision(false);
        tBaseUp = new QPushButton(mainTab);
        tBaseUp->setObjectName(QStringLiteral("tBaseUp"));
        tBaseUp->setGeometry(QRect(82, 92, 16, 16));
        tBaseUp->setStyleSheet(QStringLiteral("background:rgb(0,0,0,0)"));
        QIcon icon1;
        icon1.addFile(QStringLiteral("up.xpm"), QSize(), QIcon::Normal, QIcon::Off);
        tBaseUp->setIcon(icon1);
        tBaseUp->setIconSize(QSize(15, 15));
        tBaseUp->setFlat(true);
        hPosKnob = new Knob(mainTab);
        hPosKnob->setObjectName(QStringLiteral("hPosKnob"));
        hPosKnob->setGeometry(QRect(122, 92, 50, 50));
        hPosKnob->setLowerBound(-0.0014);
        hPosKnob->setUpperBound(1);
        hPosKnob->setScaleMaxMajor(0);
        hPosKnob->setScaleMaxMinor(0);
        hPosKnob->setTotalSteps(36000u);
        hPosKnob->setStepAlignment(true);
        hPosKnob->setTracking(false);
        hPosKnob->setWrapping(false);
        hPosKnob->setKnobStyle(QwtKnob::Raised);
        hPosKnob->setKnobWidth(30);
        hPosKnob->setTotalAngle(3600);
        hPosKnob->setNumTurns(10);
        hPosKnob->setMarkerStyle(QwtKnob::Tick);
        hPosKnob->setSubscribe(true);
        hPosKnob->setHaveScale(false);
        hPosKnob->setProperty("minValue", QVariant(-0.0014));
        hPosKnob->setProperty("maxValue", QVariant(1));
        hPosKnob->setProperty("valueIncrement", QVariant(1e-06));
        timeFrame = new QFrame(mainTab);
        timeFrame->setObjectName(QStringLiteral("timeFrame"));
        timeFrame->setGeometry(QRect(12, 70, 205, 109));
        timeFrame->setStyleSheet(QStringLiteral("color:rgb(130,130,140)"));
        timeFrame->setFrameShape(QFrame::Box);
        timeFrame->setFrameShadow(QFrame::Plain);
        timeFrame->setLineWidth(2);
        label = new QLabel(timeFrame);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(8, 4, 163, 16));
        label->setStyleSheet(QStringLiteral("color:rgb(20,20,40)"));
        label_8 = new QLabel(timeFrame);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(116, 60, 36, 20));
        label_8->setPixmap(QPixmap(QString::fromUtf8("../ui/rlarrow.xpm")));
        ch4KnobY = new Knob(mainTab);
        ch4KnobY->setObjectName(QStringLiteral("ch4KnobY"));
        ch4KnobY->setGeometry(QRect(236, 182, 50, 50));
        ch4KnobY->setScaleMaxMajor(0);
        ch4KnobY->setScaleMaxMinor(0);
        ch4KnobY->setTotalSteps(256u);
        ch4KnobY->setStepAlignment(true);
        ch4KnobY->setTracking(false);
        ch4KnobY->setWrapping(false);
        ch4KnobY->setKnobStyle(QwtKnob::Raised);
        ch4KnobY->setKnobWidth(30);
        ch4KnobY->setTotalAngle(720);
        ch4KnobY->setNumTurns(2);
        ch4KnobY->setMarkerStyle(QwtKnob::Tick);
        ch4KnobY->setSubscribe(true);
        ch4KnobY->setHaveScale(false);
        ch4KnobY->setProperty("minValue", QVariant(-8));
        ch4KnobY->setProperty("maxValue", QVariant(8));
        ch4KnobV = new Knob(mainTab);
        ch4KnobV->setObjectName(QStringLiteral("ch4KnobV"));
        ch4KnobV->setGeometry(QRect(226, 280, 60, 60));
        ch4KnobV->setScaleMaxMajor(0);
        ch4KnobV->setScaleMaxMinor(0);
        ch4KnobV->setTotalSteps(256u);
        ch4KnobV->setStepAlignment(true);
        ch4KnobV->setTracking(false);
        ch4KnobV->setWrapping(false);
        ch4KnobV->setKnobStyle(QwtKnob::Raised);
        ch4KnobV->setKnobWidth(40);
        ch4KnobV->setTotalAngle(720);
        ch4KnobV->setNumTurns(2);
        ch4KnobV->setMarkerStyle(QwtKnob::Tick);
        ch4KnobV->setSubscribe(true);
        ch4KnobV->setHaveScale(false);
        ch4KnobV->setProperty("minValue", QVariant(0));
        ch4KnobV->setProperty("maxValue", QVariant(5));
        ch4Up = new QPushButton(mainTab);
        ch4Up->setObjectName(QStringLiteral("ch4Up"));
        ch4Up->setGeometry(QRect(276, 286, 16, 16));
        ch4Up->setStyleSheet(QStringLiteral("background:rgb(0,0,0,0)"));
        ch4Up->setIcon(icon1);
        ch4Up->setIconSize(QSize(15, 15));
        ch4Up->setFlat(true);
        ch4Scale = new QELineEdit(mainTab);
        ch4Scale->setObjectName(QStringLiteral("ch4Scale"));
        ch4Scale->setGeometry(QRect(238, 338, 48, 20));
        ch4Scale->setDisplayAlarmState(false);
        ch4Down = new QPushButton(mainTab);
        ch4Down->setObjectName(QStringLiteral("ch4Down"));
        ch4Down->setGeometry(QRect(276, 318, 16, 16));
        ch4Down->setStyleSheet(QStringLiteral("background:rgb(0,0,0,0)"));
        ch4Down->setIcon(icon);
        ch4Down->setIconSize(QSize(15, 15));
        ch4Down->setFlat(true);
        ch4YPos = new QELineEdit(mainTab);
        ch4YPos->setObjectName(QStringLiteral("ch4YPos"));
        ch4YPos->setGeometry(QRect(236, 228, 48, 20));
        ch4YPos->setDisplayAlarmState(false);
        ch4CAEn = new CAButton(mainTab);
        ch4CAEn->setObjectName(QStringLiteral("ch4CAEn"));
        ch4CAEn->setGeometry(QRect(246, 268, 16, 16));
        ch4CAEn->setStyleSheet(QStringLiteral("background:rgb(160,180,200)"));
        ch4CAEn->setCheckable(true);
        ch4CAEn->setProperty("writeOnPress", QVariant(false));
        ch4CAEn->setProperty("writeOnClick", QVariant(true));
        ch4CAEn->setShowLabel(false);
        ch4CAEn->setSubscribe(true);
        ch4CAEn->setProperty("AlarmEnable", QVariant(false));
        ch4Frame = new QFrame(mainTab);
        ch4Frame->setObjectName(QStringLiteral("ch4Frame"));
        ch4Frame->setGeometry(QRect(228, 182, 68, 184));
        ch4Frame->setStyleSheet(QStringLiteral("color:rgb(80,80,220)"));
        ch4Frame->setFrameShape(QFrame::Box);
        ch4Frame->setFrameShadow(QFrame::Plain);
        ch4Frame->setLineWidth(2);
        ch3Frame = new QFrame(mainTab);
        ch3Frame->setObjectName(QStringLiteral("ch3Frame"));
        ch3Frame->setGeometry(QRect(156, 182, 68, 184));
        ch3Frame->setStyleSheet(QStringLiteral("color:rgb(255,0,255)"));
        ch3Frame->setFrameShape(QFrame::Box);
        ch3Frame->setFrameShadow(QFrame::Plain);
        ch3Frame->setLineWidth(2);
        ch3KnobV = new Knob(ch3Frame);
        ch3KnobV->setObjectName(QStringLiteral("ch3KnobV"));
        ch3KnobV->setGeometry(QRect(4, 98, 60, 60));
        ch3KnobV->setScaleMaxMajor(0);
        ch3KnobV->setScaleMaxMinor(0);
        ch3KnobV->setTotalSteps(256u);
        ch3KnobV->setStepAlignment(true);
        ch3KnobV->setTracking(false);
        ch3KnobV->setWrapping(false);
        ch3KnobV->setKnobStyle(QwtKnob::Raised);
        ch3KnobV->setKnobWidth(40);
        ch3KnobV->setTotalAngle(720);
        ch3KnobV->setNumTurns(2);
        ch3KnobV->setMarkerStyle(QwtKnob::Tick);
        ch3KnobV->setSubscribe(true);
        ch3KnobV->setHaveScale(false);
        ch3KnobV->setProperty("minValue", QVariant(0));
        ch3KnobV->setProperty("maxValue", QVariant(5));
        ch3CAEn = new CAButton(mainTab);
        ch3CAEn->setObjectName(QStringLiteral("ch3CAEn"));
        ch3CAEn->setGeometry(QRect(174, 268, 16, 16));
        ch3CAEn->setStyleSheet(QStringLiteral("background:rgb(160,180,200)"));
        ch3CAEn->setCheckable(true);
        ch3CAEn->setProperty("writeOnPress", QVariant(false));
        ch3CAEn->setProperty("writeOnClick", QVariant(true));
        ch3CAEn->setShowLabel(false);
        ch3CAEn->setSubscribe(true);
        ch3CAEn->setProperty("AlarmEnable", QVariant(false));
        ch3Up = new QPushButton(mainTab);
        ch3Up->setObjectName(QStringLiteral("ch3Up"));
        ch3Up->setGeometry(QRect(204, 286, 16, 16));
        ch3Up->setStyleSheet(QStringLiteral("background:rgb(0,0,0,0)"));
        ch3Up->setIcon(icon1);
        ch3Up->setIconSize(QSize(15, 15));
        ch3Up->setFlat(true);
        ch3Scale = new QELineEdit(mainTab);
        ch3Scale->setObjectName(QStringLiteral("ch3Scale"));
        ch3Scale->setGeometry(QRect(166, 338, 48, 20));
        ch3Scale->setDisplayAlarmState(false);
        ch3Down = new QPushButton(mainTab);
        ch3Down->setObjectName(QStringLiteral("ch3Down"));
        ch3Down->setGeometry(QRect(204, 318, 16, 16));
        ch3Down->setStyleSheet(QStringLiteral("background:rgb(0,0,0,0)"));
        ch3Down->setIcon(icon);
        ch3Down->setIconSize(QSize(15, 15));
        ch3Down->setFlat(true);
        ch3KnobY = new Knob(mainTab);
        ch3KnobY->setObjectName(QStringLiteral("ch3KnobY"));
        ch3KnobY->setGeometry(QRect(164, 182, 50, 50));
        ch3KnobY->setScaleMaxMajor(0);
        ch3KnobY->setScaleMaxMinor(0);
        ch3KnobY->setTotalSteps(256u);
        ch3KnobY->setStepAlignment(true);
        ch3KnobY->setTracking(false);
        ch3KnobY->setWrapping(false);
        ch3KnobY->setKnobStyle(QwtKnob::Raised);
        ch3KnobY->setKnobWidth(30);
        ch3KnobY->setTotalAngle(720);
        ch3KnobY->setNumTurns(2);
        ch3KnobY->setMarkerStyle(QwtKnob::Tick);
        ch3KnobY->setSubscribe(true);
        ch3KnobY->setHaveScale(false);
        ch3KnobY->setProperty("minValue", QVariant(-8));
        ch3KnobY->setProperty("maxValue", QVariant(8));
        ch3YPos = new QELineEdit(mainTab);
        ch3YPos->setObjectName(QStringLiteral("ch3YPos"));
        ch3YPos->setGeometry(QRect(164, 228, 48, 20));
        ch3YPos->setDisplayAlarmState(false);
        ch2Frame = new QFrame(mainTab);
        ch2Frame->setObjectName(QStringLiteral("ch2Frame"));
        ch2Frame->setGeometry(QRect(84, 182, 68, 184));
        ch2Frame->setStyleSheet(QStringLiteral("color:rgb(0,255,255)"));
        ch2Frame->setFrameShape(QFrame::Box);
        ch2Frame->setFrameShadow(QFrame::Plain);
        ch2Frame->setLineWidth(2);
        ch2Down = new QPushButton(mainTab);
        ch2Down->setObjectName(QStringLiteral("ch2Down"));
        ch2Down->setGeometry(QRect(132, 318, 16, 16));
        ch2Down->setStyleSheet(QStringLiteral("background:rgb(0,0,0,0)"));
        ch2Down->setIcon(icon);
        ch2Down->setIconSize(QSize(15, 15));
        ch2Down->setFlat(true);
        ch2Scale = new QELineEdit(mainTab);
        ch2Scale->setObjectName(QStringLiteral("ch2Scale"));
        ch2Scale->setGeometry(QRect(94, 338, 48, 20));
        ch2Scale->setDisplayAlarmState(false);
        ch2YPos = new QELineEdit(mainTab);
        ch2YPos->setObjectName(QStringLiteral("ch2YPos"));
        ch2YPos->setGeometry(QRect(92, 228, 48, 20));
        ch2YPos->setDisplayAlarmState(false);
        ch2KnobY = new Knob(mainTab);
        ch2KnobY->setObjectName(QStringLiteral("ch2KnobY"));
        ch2KnobY->setGeometry(QRect(92, 182, 50, 50));
        ch2KnobY->setScaleMaxMajor(0);
        ch2KnobY->setScaleMaxMinor(0);
        ch2KnobY->setTotalSteps(256u);
        ch2KnobY->setStepAlignment(true);
        ch2KnobY->setTracking(false);
        ch2KnobY->setWrapping(false);
        ch2KnobY->setKnobStyle(QwtKnob::Raised);
        ch2KnobY->setKnobWidth(30);
        ch2KnobY->setTotalAngle(720);
        ch2KnobY->setNumTurns(2);
        ch2KnobY->setMarkerStyle(QwtKnob::Tick);
        ch2KnobY->setSubscribe(true);
        ch2KnobY->setHaveScale(false);
        ch2KnobY->setProperty("minValue", QVariant(-8));
        ch2KnobY->setProperty("maxValue", QVariant(8));
        ch2CAEn = new CAButton(mainTab);
        ch2CAEn->setObjectName(QStringLiteral("ch2CAEn"));
        ch2CAEn->setGeometry(QRect(102, 268, 16, 16));
        ch2CAEn->setStyleSheet(QStringLiteral("background:rgb(128,255,128)"));
        ch2CAEn->setCheckable(true);
        ch2CAEn->setProperty("writeOnPress", QVariant(false));
        ch2CAEn->setProperty("writeOnClick", QVariant(true));
        ch2CAEn->setShowLabel(false);
        ch2CAEn->setSubscribe(true);
        ch2CAEn->setProperty("AlarmEnable", QVariant(false));
        ch2Up = new QPushButton(mainTab);
        ch2Up->setObjectName(QStringLiteral("ch2Up"));
        ch2Up->setGeometry(QRect(132, 286, 16, 16));
        ch2Up->setStyleSheet(QStringLiteral("background:rgb(0,0,0,0)"));
        ch2Up->setIcon(icon1);
        ch2Up->setIconSize(QSize(15, 15));
        ch2Up->setFlat(true);
        ch2KnobV = new Knob(mainTab);
        ch2KnobV->setObjectName(QStringLiteral("ch2KnobV"));
        ch2KnobV->setGeometry(QRect(82, 280, 60, 60));
        ch2KnobV->setScaleMaxMajor(0);
        ch2KnobV->setScaleMaxMinor(0);
        ch2KnobV->setTotalSteps(0u);
        ch2KnobV->setPageSteps(1u);
        ch2KnobV->setStepAlignment(true);
        ch2KnobV->setTracking(false);
        ch2KnobV->setWrapping(false);
        ch2KnobV->setKnobStyle(QwtKnob::Raised);
        ch2KnobV->setKnobWidth(40);
        ch2KnobV->setTotalAngle(720);
        ch2KnobV->setNumTurns(2);
        ch2KnobV->setMarkerStyle(QwtKnob::Tick);
        ch2KnobV->setSubscribe(true);
        ch2KnobV->setHaveScale(false);
        ch2KnobV->setProperty("minValue", QVariant(0));
        ch2KnobV->setProperty("maxValue", QVariant(5));
        ch1Frame = new QFrame(mainTab);
        ch1Frame->setObjectName(QStringLiteral("ch1Frame"));
        ch1Frame->setGeometry(QRect(12, 182, 68, 184));
        ch1Frame->setStyleSheet(QStringLiteral("color:rgb(255,200,100)"));
        ch1Frame->setFrameShape(QFrame::Box);
        ch1Frame->setFrameShadow(QFrame::Plain);
        ch1Frame->setLineWidth(2);
        ch1KnobV = new Knob(mainTab);
        ch1KnobV->setObjectName(QStringLiteral("ch1KnobV"));
        ch1KnobV->setGeometry(QRect(10, 280, 60, 60));
        ch1KnobV->setScaleMaxMajor(0);
        ch1KnobV->setScaleMaxMinor(0);
        ch1KnobV->setTotalSteps(0u);
        ch1KnobV->setPageSteps(1u);
        ch1KnobV->setStepAlignment(true);
        ch1KnobV->setTracking(false);
        ch1KnobV->setWrapping(false);
        ch1KnobV->setKnobStyle(QwtKnob::Raised);
        ch1KnobV->setKnobWidth(40);
        ch1KnobV->setTotalAngle(720);
        ch1KnobV->setNumTurns(2);
        ch1KnobV->setMarkerStyle(QwtKnob::Tick);
        ch1KnobV->setSubscribe(true);
        ch1KnobV->setHaveScale(false);
        ch1KnobV->setProperty("minValue", QVariant(0));
        ch1KnobV->setProperty("maxValue", QVariant(5));
        ch1KnobV->setProperty("valueIncrement", QVariant(1));
        ch1KnobY = new Knob(mainTab);
        ch1KnobY->setObjectName(QStringLiteral("ch1KnobY"));
        ch1KnobY->setGeometry(QRect(20, 182, 50, 50));
        ch1KnobY->setScaleMaxMajor(0);
        ch1KnobY->setScaleMaxMinor(0);
        ch1KnobY->setTotalSteps(256u);
        ch1KnobY->setStepAlignment(true);
        ch1KnobY->setTracking(false);
        ch1KnobY->setWrapping(false);
        ch1KnobY->setKnobStyle(QwtKnob::Raised);
        ch1KnobY->setKnobWidth(30);
        ch1KnobY->setTotalAngle(720);
        ch1KnobY->setNumTurns(2);
        ch1KnobY->setMarkerStyle(QwtKnob::Tick);
        ch1KnobY->setSubscribe(true);
        ch1KnobY->setHaveScale(false);
        ch1KnobY->setProperty("minValue", QVariant(-8));
        ch1KnobY->setProperty("maxValue", QVariant(8));
        ch1Up = new QPushButton(mainTab);
        ch1Up->setObjectName(QStringLiteral("ch1Up"));
        ch1Up->setGeometry(QRect(60, 286, 16, 16));
        ch1Up->setStyleSheet(QStringLiteral("background:rgb(0,0,0,0)"));
        ch1Up->setIcon(icon1);
        ch1Up->setIconSize(QSize(15, 15));
        ch1Up->setFlat(true);
        ch1Down = new QPushButton(mainTab);
        ch1Down->setObjectName(QStringLiteral("ch1Down"));
        ch1Down->setGeometry(QRect(60, 318, 16, 16));
        ch1Down->setStyleSheet(QStringLiteral("background:rgb(0,0,0,0)"));
        ch1Down->setIcon(icon);
        ch1Down->setIconSize(QSize(15, 15));
        ch1Down->setFlat(true);
        ch1YPos = new QELineEdit(mainTab);
        ch1YPos->setObjectName(QStringLiteral("ch1YPos"));
        ch1YPos->setGeometry(QRect(20, 228, 48, 20));
        ch1YPos->setDisplayAlarmState(false);
        ch1YPos->setPrecision(3);
        ch1YPos->setUseDbPrecision(true);
        ch1Scale = new QELineEdit(mainTab);
        ch1Scale->setObjectName(QStringLiteral("ch1Scale"));
        ch1Scale->setGeometry(QRect(22, 338, 48, 20));
        ch1Scale->setDisplayAlarmState(false);
        ch1CAEn = new CAButton(mainTab);
        ch1CAEn->setObjectName(QStringLiteral("ch1CAEn"));
        ch1CAEn->setGeometry(QRect(30, 268, 16, 16));
        ch1CAEn->setStyleSheet(QStringLiteral("background:rgb(128,255,128)"));
        ch1CAEn->setCheckable(true);
        ch1CAEn->setProperty("writeOnPress", QVariant(false));
        ch1CAEn->setProperty("writeOnClick", QVariant(true));
        ch1CAEn->setShowLabel(false);
        ch1CAEn->setSubscribe(true);
        ch1CAEn->setProperty("AlarmEnable", QVariant(false));
        trigSource = new CAMVButton(mainTab);
        trigSource->setObjectName(QStringLiteral("trigSource"));
        trigSource->setGeometry(QRect(230, 36, 56, 20));
        trigSource->setStyleSheet(QStringLiteral(""));
        trigSource->setOffColor(QColor(200, 210, 220));
        trigSource->setUseTextColor(true);
        trigSource->setProperty("AlarmEnable", QVariant(false));
        trigSlopeBut = new CAMVButton(mainTab);
        trigSlopeBut->setObjectName(QStringLiteral("trigSlopeBut"));
        trigSlopeBut->setGeometry(QRect(230, 60, 56, 20));
        trigSlopeBut->setStyleSheet(QStringLiteral(""));
        trigSlopeBut->setOffColor(QColor(200, 210, 220));
        trigSlopeBut->setUseTextColor(true);
        trigSlopeBut->setProperty("AlarmEnable", QVariant(false));
        trigSweep = new CAMVButton(mainTab);
        trigSweep->setObjectName(QStringLiteral("trigSweep"));
        trigSweep->setGeometry(QRect(230, 84, 56, 20));
        trigSweep->setStyleSheet(QStringLiteral(""));
        trigSweep->setOffColor(QColor(200, 210, 220));
        trigSweep->setProperty("AlarmEnable", QVariant(false));
        tLevKnob = new Knob(mainTab);
        tLevKnob->setObjectName(QStringLiteral("tLevKnob"));
        tLevKnob->setGeometry(QRect(250, 108, 40, 40));
        tLevKnob->setLowerBound(-5);
        tLevKnob->setUpperBound(5);
        tLevKnob->setScaleMaxMajor(0);
        tLevKnob->setScaleMaxMinor(0);
        tLevKnob->setTotalSteps(256u);
        tLevKnob->setStepAlignment(true);
        tLevKnob->setTracking(false);
        tLevKnob->setWrapping(false);
        tLevKnob->setKnobStyle(QwtKnob::Raised);
        tLevKnob->setKnobWidth(30);
        tLevKnob->setTotalAngle(3600);
        tLevKnob->setNumTurns(10);
        tLevKnob->setMarkerStyle(QwtKnob::Tick);
        tLevKnob->setSubscribe(true);
        tLevKnob->setHaveScale(false);
        tLevKnob->setProperty("minValue", QVariant(-5));
        tLevKnob->setProperty("maxValue", QVariant(5));
        trigLevl = new QELineEdit(mainTab);
        trigLevl->setObjectName(QStringLiteral("trigLevl"));
        trigLevl->setGeometry(QRect(230, 150, 56, 20));
        trigLevl->setDisplayAlarmState(false);
        trigFrame = new QFrame(mainTab);
        trigFrame->setObjectName(QStringLiteral("trigFrame"));
        trigFrame->setGeometry(QRect(220, 10, 75, 169));
        trigFrame->setStyleSheet(QStringLiteral("color:rgb(200,255,200)"));
        trigFrame->setFrameShape(QFrame::Box);
        trigFrame->setFrameShadow(QFrame::Plain);
        trigFrame->setLineWidth(2);
        label_3 = new QLabel(trigFrame);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(32, 108, 20, 20));
        label_3->setPixmap(QPixmap(QString::fromUtf8("../../../../../tools/display/scope/ui/tlevel.xpm")));
        label_2 = new QLabel(trigFrame);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 108, 20, 20));
        label_2->setPixmap(QPixmap(QString::fromUtf8("../../../../../tools/display/scope/ui/tlevel.xpm")));
        label_4 = new QLabel(mainTab);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(230, 16, 47, 16));
        label_4->setAlignment(Qt::AlignCenter);
        runStopBut = new CAButton(mainTab);
        runStopBut->setObjectName(QStringLiteral("runStopBut"));
        runStopBut->setGeometry(QRect(98, 10, 48, 20));
        runStopBut->setCheckable(true);
        runStopBut->setUseTextColor(true);
        runStopBut->setProperty("writeOnPress", QVariant(false));
        runStopBut->setProperty("writeOnClick", QVariant(true));
        runStopBut->setSubscribe(true);
        runStopBut->setProperty("AlarmEnable", QVariant(false));
        runStopBut->setLiteralLabel(true);
        label_5 = new QLabel(mainTab);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(14, 42, 89, 16));
        label_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel = new QELabel(mainTab);
        qelabel->setObjectName(QStringLiteral("qelabel"));
        qelabel->setGeometry(QRect(108, 42, 103, 16));
        qelabel->setDisplayAlarmState(false);
        qelabel->setProperty("notation", QVariant(QELabel::Automatic));
        label_6 = new QLabel(mainTab);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(298, 302, 37, 16));
        label_7 = new QLabel(mainTab);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(298, 188, 24, 40));
        label_7->setPixmap(QPixmap(QString::fromUtf8("../ui/udarrow.xpm")));
        label_7->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        runStopBut_2 = new CAButton(mainTab);
        runStopBut_2->setObjectName(QStringLiteral("runStopBut_2"));
        runStopBut_2->setGeometry(QRect(158, 10, 48, 20));
        runStopBut_2->setCheckable(true);
        runStopBut_2->setUseTextColor(true);
        runStopBut_2->setProperty("writeOnPress", QVariant(false));
        runStopBut_2->setProperty("writeOnClick", QVariant(true));
        runStopBut_2->setSubscribe(true);
        runStopBut_2->setProperty("AlarmEnable", QVariant(false));
        runStopBut_2->setLiteralLabel(true);
        tabWidget->addTab(mainTab, QString());
        trigFrame->raise();
        timeFrame->raise();
        ch4Frame->raise();
        tbaseUnit->raise();
        timeScale->raise();
        tBaseKnob->raise();
        tBaseDown->raise();
        tBaseOfst->raise();
        tBaseUp->raise();
        hPosKnob->raise();
        ch4KnobY->raise();
        ch4KnobV->raise();
        ch4Up->raise();
        ch4Scale->raise();
        ch4Down->raise();
        ch4YPos->raise();
        ch4CAEn->raise();
        ch3Frame->raise();
        ch3CAEn->raise();
        ch3Up->raise();
        ch3Scale->raise();
        ch3Down->raise();
        ch3KnobY->raise();
        ch3YPos->raise();
        ch2Frame->raise();
        ch2Down->raise();
        ch2Scale->raise();
        ch2YPos->raise();
        ch2KnobY->raise();
        ch2CAEn->raise();
        ch2Up->raise();
        ch2KnobV->raise();
        ch1Frame->raise();
        ch1KnobV->raise();
        ch1KnobY->raise();
        ch1Up->raise();
        ch1Down->raise();
        ch1YPos->raise();
        ch1Scale->raise();
        ch1CAEn->raise();
        trigSource->raise();
        trigSlopeBut->raise();
        trigSweep->raise();
        tLevKnob->raise();
        trigLevl->raise();
        label_4->raise();
        runStopBut->raise();
        label_5->raise();
        qelabel->raise();
        label_6->raise();
        label_7->raise();
        runStopBut_2->raise();
        horTab = new QWidget();
        horTab->setObjectName(QStringLiteral("horTab"));
        tabWidget->addTab(horTab, QString());
        trigTab = new QWidget();
        trigTab->setObjectName(QStringLiteral("trigTab"));
        tabWidget->addTab(trigTab, QString());
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        tabWidget->addTab(tab, QString());
        MainWindow->setCentralWidget(centralwidget);
        tabWidget->raise();
        scopeArea->raise();
        ch1Label->raise();
        ch1VDiv->raise();
        ch3VDiv->raise();
        ch3Label->raise();
        ch2VDiv->raise();
        ch2Label->raise();
        ch4VDiv->raise();
        ch4Label->raise();
        idnLabel->raise();
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 867, 20));
        menuFile = new QMenu(menubar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        MainWindow->setMenuBar(menubar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menubar->addAction(menuFile->menuAction());
        menuFile->addAction(actionQuit);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        actionQuit->setText(QApplication::translate("MainWindow", "quit", 0));
        scopeArea->setTitle(QString());
        trigState->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):SI:TRIG:STATE", 0)));
        trigState->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        caplot->setProperty("variable1", QVariant(QApplication::translate("MainWindow", "$(P):WF:CH0:TRACE", 0)));
        caplot->setProperty("variable2", QVariant(QApplication::translate("MainWindow", "$(P):WF:CH1:TRACE", 0)));
        caplot->setProperty("variable3", QVariant(QApplication::translate("MainWindow", "$(P):WF:CH2:TRACE", 0)));
        caplot->setProperty("variable4", QVariant(QApplication::translate("MainWindow", "$(P):WF:CH3:TRACE", 0)));
        caplot->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SC01", 0)));
        caplot->setProperty("Marker1PV", QVariant(QApplication::translate("MainWindow", "$(P):LI:TRIG:LEVQT", 0)));
        ch1Label->setText(QApplication::translate("MainWindow", "CH1", 0));
        ch1VDiv->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH0:SCL", 0)));
        ch1VDiv->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch3VDiv->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH2:SCL", 0)));
        ch3VDiv->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch3Label->setText(QApplication::translate("MainWindow", "CH3", 0));
        ch2VDiv->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH1:SCL", 0)));
        ch2VDiv->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch2Label->setText(QApplication::translate("MainWindow", "CH2", 0));
        ch4VDiv->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH3:SCL", 0)));
        ch4VDiv->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch4Label->setText(QApplication::translate("MainWindow", "CH4", 0));
        idnLabel->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):WF:IDN", 0)));
        idnLabel->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SC01", 0)));
        tbaseUnit->setText(QApplication::translate("MainWindow", "us", 0));
        tbaseUnit->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):MBBO:TIM:DIV:U", 0)));
        tbaseUnit->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        timeScale->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):LO:TIME:DIV:V", 0)));
        timeScale->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        tBaseKnob->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:TIME:DIV", 0)));
        tBaseKnob->setProperty("variableSubst", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        tBaseDown->setText(QString());
        tBaseOfst->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:TIME:OFST", 0)));
        tBaseOfst->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        tBaseUp->setText(QString());
        hPosKnob->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:TIME:OFST", 0)));
        hPosKnob->setProperty("variableSubst", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        label->setText(QApplication::translate("MainWindow", "Horizontal Time & Position", 0));
        label_8->setText(QString());
        ch4KnobY->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH3:POS", 0)));
        ch4KnobY->setProperty("variableSubst", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch4KnobV->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH3:SCL", 0)));
        ch4KnobV->setProperty("variableSubst", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch4Up->setText(QString());
        ch4Scale->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH3:SCL", 0)));
        ch4Scale->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch4Down->setText(QString());
        ch4YPos->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH3:POS", 0)));
        ch4YPos->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch4CAEn->setText(QString());
        ch4CAEn->setOnText(QApplication::translate("MainWindow", "On", 0));
        ch4CAEn->setOffText(QApplication::translate("MainWindow", "Off", 0));
        ch4CAEn->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:CH3:ON", 0)));
        ch4CAEn->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch3KnobV->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH2:SCL", 0)));
        ch3KnobV->setProperty("variableSubst", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch3CAEn->setText(QString());
        ch3CAEn->setOnText(QApplication::translate("MainWindow", "On", 0));
        ch3CAEn->setOffText(QApplication::translate("MainWindow", "Off", 0));
        ch3CAEn->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:CH2:ON", 0)));
        ch3CAEn->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch3Up->setText(QString());
        ch3Scale->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH2:SCL", 0)));
        ch3Scale->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch3Down->setText(QString());
        ch3KnobY->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH2:POS", 0)));
        ch3KnobY->setProperty("variableSubst", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch3YPos->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH2:POS", 0)));
        ch3YPos->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch2Down->setText(QString());
        ch2Scale->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH1:SCL", 0)));
        ch2Scale->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch2YPos->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH1:POS", 0)));
        ch2YPos->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch2KnobY->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH1:POS", 0)));
        ch2KnobY->setProperty("variableSubst", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch2CAEn->setText(QString());
        ch2CAEn->setOnText(QApplication::translate("MainWindow", "On", 0));
        ch2CAEn->setOffText(QApplication::translate("MainWindow", "Off", 0));
        ch2CAEn->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:CH1:ON", 0)));
        ch2CAEn->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch2Up->setText(QString());
        ch2KnobV->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH1:SCL", 0)));
        ch2KnobV->setProperty("variableSubst", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch1KnobV->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH0:SCL", 0)));
        ch1KnobV->setProperty("variableSubst", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch1KnobY->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH0:POS", 0)));
        ch1KnobY->setProperty("variableSubst", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch1Up->setText(QString());
        ch1Down->setText(QString());
        ch1YPos->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH0:POS", 0)));
        ch1YPos->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch1Scale->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:CH0:SCL", 0)));
        ch1Scale->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        ch1CAEn->setText(QString());
        ch1CAEn->setOnText(QApplication::translate("MainWindow", "On", 0));
        ch1CAEn->setOffText(QApplication::translate("MainWindow", "Off", 0));
        ch1CAEn->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:CH0:ON", 0)));
        ch1CAEn->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        trigSource->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):MBBO:TRIG:SOU", 0)));
        trigSource->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        trigSlopeBut->setText(QApplication::translate("MainWindow", "Fall", 0));
        trigSlopeBut->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):MBBO:TRIG:SLOPE", 0)));
        trigSlopeBut->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        trigSweep->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):MBBO:TRIG:SWEEP", 0)));
        trigSweep->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        tLevKnob->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:TRIG:LEV", 0)));
        tLevKnob->setProperty("variableSubst", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        trigLevl->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):AO:TRIG:LEV", 0)));
        trigLevl->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        label_3->setText(QString());
        label_2->setText(QString());
        label_4->setText(QApplication::translate("MainWindow", "Trigger", 0));
        runStopBut->setOnText(QApplication::translate("MainWindow", "Run", 0));
        runStopBut->setOffText(QApplication::translate("MainWindow", "Stop", 0));
        runStopBut->setOnLabel(QApplication::translate("MainWindow", "Run", 0));
        runStopBut->setOffLabel(QApplication::translate("MainWindow", "Run", 0));
        runStopBut->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:RUN", 0)));
        runStopBut->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        label_5->setText(QApplication::translate("MainWindow", "Sampling rate", 0));
        qelabel->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):SI:SMPL:RATE", 0)));
        qelabel->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        label_6->setText(QApplication::translate("MainWindow", "Scale", 0));
        label_7->setText(QString());
        runStopBut_2->setOnText(QApplication::translate("MainWindow", "Run", 0));
        runStopBut_2->setOffText(QApplication::translate("MainWindow", "Stop", 0));
        runStopBut_2->setOnLabel(QApplication::translate("MainWindow", "Stop", 0));
        runStopBut_2->setOffLabel(QApplication::translate("MainWindow", "Stop", 0));
        runStopBut_2->setProperty("variable", QVariant(QApplication::translate("MainWindow", "$(P):BO:STOP", 0)));
        runStopBut_2->setProperty("variableSubstitutions", QVariant(QApplication::translate("MainWindow", "P=CHA:SCP1", 0)));
        tabWidget->setTabText(tabWidget->indexOf(mainTab), QApplication::translate("MainWindow", "Main", 0));
        tabWidget->setTabText(tabWidget->indexOf(horTab), QApplication::translate("MainWindow", "Time", 0));
        tabWidget->setTabText(tabWidget->indexOf(trigTab), QApplication::translate("MainWindow", "Trigger", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Acquire", 0));
        menuFile->setTitle(QApplication::translate("MainWindow", "File", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
