/********************************************************************************
** Form generated from reading UI file 'motordetails.ui'
**
** Created by: Qt User Interface Compiler version 4.8.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MOTORDETAILS_H
#define UI_MOTORDETAILS_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QListWidget>
#include <QtGui/QPushButton>
#include <QtGui/QStackedWidget>
#include <QtGui/QWidget>
#include "QEComboBox.h"
#include "QELabel.h"
#include "QELineEdit.h"
#include "QEPushButton.h"
#include "bytemonitor.h"

QT_BEGIN_NAMESPACE

class Ui_MotorDetails
{
public:
    QListWidget *listWidget;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QLabel *label_3;
    QELineEdit *qelineedit;
    QLabel *label_9;
    QLabel *label_10;
    QELineEdit *qelineedit_2;
    QELineEdit *qelineedit_3;
    QELineEdit *qelineedit_4;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QEComboBox *qecombobox;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QELabel *qelabel_6;
    QELabel *qelabel_7;
    QELineEdit *qelineedit_5;
    QELineEdit *qelineedit_6;
    QELineEdit *qelineedit_7;
    QELabel *qelabel_8;
    QELineEdit *qelineedit_8;
    QEPushButton *tweekReverse;
    QEPushButton *tweekForward;
    QEPushButton *homeReverse;
    QEPushButton *homeForward;
    QEPushButton *jogReverse;
    QEPushButton *jogForward;
    QELineEdit *qelineedit_9;
    QWidget *page_2;
    QLabel *label_4;
    QGroupBox *groupBoxNormal;
    QELineEdit *qelineedit_10;
    QELineEdit *qelineedit_11;
    QELineEdit *qelineedit_12;
    QELineEdit *qelineedit_13;
    QGroupBox *groupBoxBack;
    QELineEdit *qelineedit_14;
    QELineEdit *qelineedit_15;
    QELineEdit *qelineedit_16;
    QELineEdit *qelineedit_17;
    QGroupBox *groupBoxJog;
    QELineEdit *qelineedit_18;
    QELineEdit *qelineedit_19;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QWidget *page_3;
    QLabel *label_5;
    QLabel *label_29;
    QELineEdit *qelineedit_20;
    QLabel *label_30;
    QELineEdit *qelineedit_21;
    QLabel *label_31;
    QLabel *label_32;
    QELineEdit *qelineedit_22;
    QLabel *label_33;
    QLabel *label_34;
    QELineEdit *qelineedit_23;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QELineEdit *qelineedit_24;
    QELabel *qelabel_9;
    QEComboBox *qecombobox_2;
    QLabel *label_38;
    QEComboBox *qecombobox_3;
    QLabel *label_39;
    QLabel *label_40;
    QELineEdit *qelineedit_25;
    QLabel *label_41;
    QLabel *label_42;
    QELineEdit *qelineedit_26;
    QLabel *label_43;
    QELineEdit *qelineedit_27;
    QLabel *label_44;
    QELineEdit *qelineedit_28;
    QLabel *label_45;
    QEComboBox *qecombobox_4;
    QWidget *page_4;
    QLabel *label_6;
    QELabel *qelabel_10;
    QLabel *label_46;
    QELabel *qelabel_11;
    QLabel *label_47;
    QELabel *qelabel_12;
    QLabel *label_48;
    QELabel *qelabel_13;
    QLabel *label_49;
    QELabel *qelabel_14;
    QLabel *label_50;
    QELabel *qelabel_15;
    QLabel *label_51;
    QELabel *qelabel_16;
    QLabel *label_52;
    QELabel *qelabel_17;
    QLabel *label_53;
    QELabel *qelabel_18;
    QLabel *label_54;
    QELabel *qelabel_19;
    QELabel *qelabel_20;
    QLabel *label_55;
    QLabel *label_56;
    QELineEdit *qelineedit_29;
    QELineEdit *qelineedit_30;
    QLabel *label_57;
    QLabel *label_58;
    QEComboBox *qecombobox_5;
    ByteMonitor *bytemonitor;
    QLabel *label_65;
    QLabel *label_70;
    QLabel *label_72;
    QLabel *label_74;
    QLabel *label_76;
    QLabel *label_77;
    QLabel *label_78;
    ByteMonitor *bytemonitor_2;
    QLabel *label_66;
    QLabel *label_79;
    QLabel *label_71;
    QLabel *label_80;
    QLabel *label_81;
    QLabel *label_82;
    QLabel *label_83;
    QLabel *label_84;
    QLabel *label_75;
    QWidget *page_5;
    QLabel *label_7;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QEComboBox *qecombobox_6;
    QEComboBox *qecombobox_7;
    QEComboBox *qecombobox_8;
    QELineEdit *qelineedit_31;
    QWidget *page_6;
    QLabel *label_8;
    QLabel *label_62;
    QLabel *label_63;
    QLabel *label_64;
    QELineEdit *qelineedit_32;
    QELineEdit *qelineedit_33;
    QELineEdit *qelineedit_34;
    QGroupBox *groupBox;
    QELabel *qelabel;
    QELabel *qelabel_2;
    QELabel *qelabel_3;
    QLabel *label;
    QELabel *qelabel_4;
    QLabel *label_2;
    QELabel *qelabel_5;
    QPushButton *pushButton;

    void setupUi(QDialog *MotorDetails)
    {
        if (MotorDetails->objectName().isEmpty())
            MotorDetails->setObjectName(QString::fromUtf8("MotorDetails"));
        MotorDetails->resize(520, 312);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MotorDetails->sizePolicy().hasHeightForWidth());
        MotorDetails->setSizePolicy(sizePolicy);
        MotorDetails->setMinimumSize(QSize(520, 312));
        MotorDetails->setMaximumSize(QSize(520, 312));
        listWidget = new QListWidget(MotorDetails);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        listWidget->setObjectName(QString::fromUtf8("listWidget"));
        listWidget->setGeometry(QRect(4, 56, 84, 248));
        sizePolicy.setHeightForWidth(listWidget->sizePolicy().hasHeightForWidth());
        listWidget->setSizePolicy(sizePolicy);
        stackedWidget = new QStackedWidget(MotorDetails);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(92, 56, 421, 248));
        sizePolicy.setHeightForWidth(stackedWidget->sizePolicy().hasHeightForWidth());
        stackedWidget->setSizePolicy(sizePolicy);
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        label_3 = new QLabel(page);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(4, 4, 57, 15));
        qelineedit = new QELineEdit(page);
        qelineedit->setObjectName(QString::fromUtf8("qelineedit"));
        qelineedit->setGeometry(QRect(84, 40, 88, 20));
        qelineedit->setAddUnits(false);
        label_9 = new QLabel(page);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(4, 40, 72, 20));
        label_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_10 = new QLabel(page);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(4, 68, 72, 20));
        label_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_2 = new QELineEdit(page);
        qelineedit_2->setObjectName(QString::fromUtf8("qelineedit_2"));
        qelineedit_2->setGeometry(QRect(84, 68, 88, 20));
        qelineedit_2->setAddUnits(false);
        qelineedit_3 = new QELineEdit(page);
        qelineedit_3->setObjectName(QString::fromUtf8("qelineedit_3"));
        qelineedit_3->setGeometry(QRect(192, 40, 88, 20));
        qelineedit_3->setAddUnits(false);
        qelineedit_4 = new QELineEdit(page);
        qelineedit_4->setObjectName(QString::fromUtf8("qelineedit_4"));
        qelineedit_4->setGeometry(QRect(192, 68, 88, 20));
        qelineedit_4->setAddUnits(false);
        label_11 = new QLabel(page);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(84, 20, 57, 15));
        label_12 = new QLabel(page);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(192, 20, 57, 15));
        label_13 = new QLabel(page);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(308, 20, 57, 15));
        qecombobox = new QEComboBox(page);
        qecombobox->setObjectName(QString::fromUtf8("qecombobox"));
        qecombobox->setGeometry(QRect(308, 212, 74, 22));
        qecombobox->setSubscribe(true);
        label_14 = new QLabel(page);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(4, 116, 72, 20));
        label_14->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_15 = new QLabel(page);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(4, 140, 72, 20));
        label_15->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_16 = new QLabel(page);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(4, 180, 72, 16));
        label_16->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_17 = new QLabel(page);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(4, 212, 64, 22));
        label_17->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_6 = new QELabel(page);
        qelabel_6->setObjectName(QString::fromUtf8("qelabel_6"));
        qelabel_6->setGeometry(QRect(84, 116, 72, 20));
        qelabel_6->setAddUnits(false);
        qelabel_7 = new QELabel(page);
        qelabel_7->setObjectName(QString::fromUtf8("qelabel_7"));
        qelabel_7->setGeometry(QRect(192, 116, 72, 20));
        qelabel_7->setAddUnits(false);
        qelineedit_5 = new QELineEdit(page);
        qelineedit_5->setObjectName(QString::fromUtf8("qelineedit_5"));
        qelineedit_5->setGeometry(QRect(84, 140, 88, 20));
        qelineedit_5->setAddUnits(false);
        qelineedit_6 = new QELineEdit(page);
        qelineedit_6->setObjectName(QString::fromUtf8("qelineedit_6"));
        qelineedit_6->setGeometry(QRect(192, 140, 88, 20));
        qelineedit_6->setAddUnits(false);
        qelineedit_7 = new QELineEdit(page);
        qelineedit_7->setObjectName(QString::fromUtf8("qelineedit_7"));
        qelineedit_7->setGeometry(QRect(308, 140, 88, 20));
        qelineedit_7->setAddUnits(false);
        qelabel_8 = new QELabel(page);
        qelabel_8->setObjectName(QString::fromUtf8("qelabel_8"));
        qelabel_8->setGeometry(QRect(308, 116, 72, 20));
        qelabel_8->setAddUnits(false);
        qelineedit_8 = new QELineEdit(page);
        qelineedit_8->setObjectName(QString::fromUtf8("qelineedit_8"));
        qelineedit_8->setGeometry(QRect(84, 180, 88, 20));
        qelineedit_8->setAddUnits(false);
        tweekReverse = new QEPushButton(page);
        tweekReverse->setObjectName(QString::fromUtf8("tweekReverse"));
        tweekReverse->setGeometry(QRect(76, 212, 22, 22));
        QFont font;
        font.setPointSize(12);
        font.setBold(true);
        font.setWeight(75);
        tweekReverse->setFont(font);
        tweekForward = new QEPushButton(page);
        tweekForward->setObjectName(QString::fromUtf8("tweekForward"));
        tweekForward->setGeometry(QRect(156, 212, 22, 22));
        tweekForward->setFont(font);
        homeReverse = new QEPushButton(page);
        homeReverse->setObjectName(QString::fromUtf8("homeReverse"));
        homeReverse->setGeometry(QRect(184, 212, 48, 22));
        QFont font1;
        font1.setPointSize(9);
        font1.setBold(true);
        font1.setWeight(75);
        homeReverse->setFont(font1);
        homeForward = new QEPushButton(page);
        homeForward->setObjectName(QString::fromUtf8("homeForward"));
        homeForward->setGeometry(QRect(240, 212, 48, 22));
        homeForward->setFont(font1);
        jogReverse = new QEPushButton(page);
        jogReverse->setObjectName(QString::fromUtf8("jogReverse"));
        jogReverse->setGeometry(QRect(184, 180, 48, 22));
        jogReverse->setFont(font1);
        jogForward = new QEPushButton(page);
        jogForward->setObjectName(QString::fromUtf8("jogForward"));
        jogForward->setGeometry(QRect(240, 180, 48, 22));
        jogForward->setFont(font1);
        qelineedit_9 = new QELineEdit(page);
        qelineedit_9->setObjectName(QString::fromUtf8("qelineedit_9"));
        qelineedit_9->setGeometry(QRect(100, 212, 53, 22));
        qelineedit_9->setAddUnits(false);
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        label_4 = new QLabel(page_2);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(4, 4, 65, 16));
        groupBoxNormal = new QGroupBox(page_2);
        groupBoxNormal->setObjectName(QString::fromUtf8("groupBoxNormal"));
        groupBoxNormal->setGeometry(QRect(92, 24, 80, 193));
        qelineedit_10 = new QELineEdit(groupBoxNormal);
        qelineedit_10->setObjectName(QString::fromUtf8("qelineedit_10"));
        qelineedit_10->setGeometry(QRect(8, 20, 64, 20));
        qelineedit_10->setAddUnits(false);
        qelineedit_11 = new QELineEdit(groupBoxNormal);
        qelineedit_11->setObjectName(QString::fromUtf8("qelineedit_11"));
        qelineedit_11->setGeometry(QRect(8, 48, 64, 20));
        qelineedit_11->setAddUnits(false);
        qelineedit_12 = new QELineEdit(groupBoxNormal);
        qelineedit_12->setObjectName(QString::fromUtf8("qelineedit_12"));
        qelineedit_12->setGeometry(QRect(8, 76, 64, 20));
        qelineedit_12->setAddUnits(false);
        qelineedit_13 = new QELineEdit(groupBoxNormal);
        qelineedit_13->setObjectName(QString::fromUtf8("qelineedit_13"));
        qelineedit_13->setGeometry(QRect(8, 104, 64, 20));
        qelineedit_13->setAddUnits(false);
        groupBoxBack = new QGroupBox(page_2);
        groupBoxBack->setObjectName(QString::fromUtf8("groupBoxBack"));
        groupBoxBack->setGeometry(QRect(174, 24, 80, 193));
        qelineedit_14 = new QELineEdit(groupBoxBack);
        qelineedit_14->setObjectName(QString::fromUtf8("qelineedit_14"));
        qelineedit_14->setGeometry(QRect(8, 48, 64, 20));
        qelineedit_14->setAddUnits(false);
        qelineedit_15 = new QELineEdit(groupBoxBack);
        qelineedit_15->setObjectName(QString::fromUtf8("qelineedit_15"));
        qelineedit_15->setGeometry(QRect(8, 104, 64, 20));
        qelineedit_15->setAddUnits(false);
        qelineedit_16 = new QELineEdit(groupBoxBack);
        qelineedit_16->setObjectName(QString::fromUtf8("qelineedit_16"));
        qelineedit_16->setGeometry(QRect(8, 132, 64, 20));
        qelineedit_16->setAddUnits(false);
        qelineedit_17 = new QELineEdit(groupBoxBack);
        qelineedit_17->setObjectName(QString::fromUtf8("qelineedit_17"));
        qelineedit_17->setGeometry(QRect(8, 160, 64, 20));
        qelineedit_17->setAddUnits(false);
        groupBoxJog = new QGroupBox(page_2);
        groupBoxJog->setObjectName(QString::fromUtf8("groupBoxJog"));
        groupBoxJog->setGeometry(QRect(256, 24, 80, 193));
        qelineedit_18 = new QELineEdit(groupBoxJog);
        qelineedit_18->setObjectName(QString::fromUtf8("qelineedit_18"));
        qelineedit_18->setGeometry(QRect(8, 48, 64, 20));
        qelineedit_18->setAddUnits(false);
        qelineedit_19 = new QELineEdit(groupBoxJog);
        qelineedit_19->setObjectName(QString::fromUtf8("qelineedit_19"));
        qelineedit_19->setGeometry(QRect(8, 104, 64, 20));
        qelineedit_19->setAddUnits(false);
        label_18 = new QLabel(page_2);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(4, 44, 80, 20));
        label_18->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_19 = new QLabel(page_2);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(4, 72, 80, 20));
        label_19->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_20 = new QLabel(page_2);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(4, 100, 80, 20));
        label_20->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_21 = new QLabel(page_2);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(4, 128, 80, 20));
        label_21->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_22 = new QLabel(page_2);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(4, 156, 80, 20));
        label_22->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_23 = new QLabel(page_2);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(4, 184, 80, 20));
        label_23->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_24 = new QLabel(page_2);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(338, 44, 64, 20));
        label_24->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_25 = new QLabel(page_2);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(338, 72, 64, 20));
        label_25->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_26 = new QLabel(page_2);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(338, 100, 64, 20));
        label_26->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_27 = new QLabel(page_2);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(338, 128, 64, 20));
        label_27->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_28 = new QLabel(page_2);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(338, 156, 64, 20));
        label_28->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        label_5 = new QLabel(page_3);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(4, 4, 65, 16));
        label_29 = new QLabel(page_3);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(88, 20, 109, 20));
        label_29->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_20 = new QELineEdit(page_3);
        qelineedit_20->setObjectName(QString::fromUtf8("qelineedit_20"));
        qelineedit_20->setGeometry(QRect(200, 20, 100, 20));
        qelineedit_20->setPrecision(8u);
        qelineedit_20->setUseDbPrecision(false);
        qelineedit_20->setAddUnits(false);
        label_30 = new QLabel(page_3);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(304, 20, 65, 20));
        qelineedit_21 = new QELineEdit(page_3);
        qelineedit_21->setObjectName(QString::fromUtf8("qelineedit_21"));
        qelineedit_21->setGeometry(QRect(200, 44, 100, 20));
        qelineedit_21->setPrecision(8u);
        qelineedit_21->setUseDbPrecision(false);
        qelineedit_21->setAddUnits(false);
        label_31 = new QLabel(page_3);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(88, 44, 109, 20));
        label_31->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_32 = new QLabel(page_3);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(304, 44, 65, 20));
        qelineedit_22 = new QELineEdit(page_3);
        qelineedit_22->setObjectName(QString::fromUtf8("qelineedit_22"));
        qelineedit_22->setGeometry(QRect(200, 68, 100, 20));
        qelineedit_22->setPrecision(8u);
        qelineedit_22->setUseDbPrecision(false);
        qelineedit_22->setAddUnits(false);
        label_33 = new QLabel(page_3);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(88, 68, 109, 20));
        label_33->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_34 = new QLabel(page_3);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(304, 68, 65, 20));
        qelineedit_23 = new QELineEdit(page_3);
        qelineedit_23->setObjectName(QString::fromUtf8("qelineedit_23"));
        qelineedit_23->setGeometry(QRect(200, 92, 100, 20));
        qelineedit_23->setPrecision(8u);
        qelineedit_23->setUseDbPrecision(true);
        qelineedit_23->setAddUnits(false);
        label_35 = new QLabel(page_3);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(88, 92, 109, 20));
        label_35->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_36 = new QLabel(page_3);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(304, 92, 65, 20));
        label_37 = new QLabel(page_3);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(40, 116, 73, 20));
        label_37->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_24 = new QELineEdit(page_3);
        qelineedit_24->setObjectName(QString::fromUtf8("qelineedit_24"));
        qelineedit_24->setGeometry(QRect(116, 116, 49, 20));
        qelineedit_24->setPrecision(8u);
        qelineedit_24->setUseDbPrecision(true);
        qelineedit_24->setAddUnits(false);
        qelabel_9 = new QELabel(page_3);
        qelabel_9->setObjectName(QString::fromUtf8("qelabel_9"));
        qelabel_9->setGeometry(QRect(172, 116, 37, 20));
        qelabel_9->setAddUnits(false);
        qecombobox_2 = new QEComboBox(page_3);
        qecombobox_2->setObjectName(QString::fromUtf8("qecombobox_2"));
        qecombobox_2->setGeometry(QRect(328, 116, 56, 20));
        label_38 = new QLabel(page_3);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(244, 116, 81, 20));
        label_38->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qecombobox_3 = new QEComboBox(page_3);
        qecombobox_3->setObjectName(QString::fromUtf8("qecombobox_3"));
        qecombobox_3->setGeometry(QRect(328, 140, 56, 20));
        label_39 = new QLabel(page_3);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(232, 140, 93, 20));
        label_39->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_40 = new QLabel(page_3);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(12, 140, 101, 20));
        label_40->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_25 = new QELineEdit(page_3);
        qelineedit_25->setObjectName(QString::fromUtf8("qelineedit_25"));
        qelineedit_25->setGeometry(QRect(116, 140, 49, 20));
        qelineedit_25->setPrecision(8u);
        qelineedit_25->setUseDbPrecision(true);
        qelineedit_25->setAddUnits(false);
        label_41 = new QLabel(page_3);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(168, 140, 25, 20));
        label_42 = new QLabel(page_3);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(40, 164, 73, 20));
        label_42->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_26 = new QELineEdit(page_3);
        qelineedit_26->setObjectName(QString::fromUtf8("qelineedit_26"));
        qelineedit_26->setGeometry(QRect(116, 164, 193, 20));
        qelineedit_26->setPrecision(8u);
        qelineedit_26->setUseDbPrecision(true);
        qelineedit_26->setAddUnits(false);
        label_43 = new QLabel(page_3);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(12, 188, 101, 20));
        label_43->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_27 = new QELineEdit(page_3);
        qelineedit_27->setObjectName(QString::fromUtf8("qelineedit_27"));
        qelineedit_27->setGeometry(QRect(116, 188, 124, 20));
        qelineedit_27->setPrecision(8u);
        qelineedit_27->setUseDbPrecision(true);
        qelineedit_27->setAddUnits(false);
        label_44 = new QLabel(page_3);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(8, 212, 105, 20));
        label_44->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_28 = new QELineEdit(page_3);
        qelineedit_28->setObjectName(QString::fromUtf8("qelineedit_28"));
        qelineedit_28->setGeometry(QRect(116, 212, 124, 20));
        qelineedit_28->setPrecision(8u);
        qelineedit_28->setUseDbPrecision(true);
        qelineedit_28->setAddUnits(false);
        label_45 = new QLabel(page_3);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(264, 192, 41, 20));
        label_45->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qecombobox_4 = new QEComboBox(page_3);
        qecombobox_4->setObjectName(QString::fromUtf8("qecombobox_4"));
        qecombobox_4->setGeometry(QRect(312, 192, 101, 20));
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QString::fromUtf8("page_4"));
        label_6 = new QLabel(page_4);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(4, 4, 57, 15));
        qelabel_10 = new QELabel(page_4);
        qelabel_10->setObjectName(QString::fromUtf8("qelabel_10"));
        qelabel_10->setGeometry(QRect(120, 2, 117, 20));
        qelabel_10->setAddUnits(false);
        label_46 = new QLabel(page_4);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(196, 4, 57, 16));
        label_46->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_11 = new QELabel(page_4);
        qelabel_11->setObjectName(QString::fromUtf8("qelabel_11"));
        qelabel_11->setGeometry(QRect(256, 4, 33, 16));
        qelabel_11->setAddUnits(false);
        qelabel_11->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_11->setRadix(16u);
        label_47 = new QLabel(page_4);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(4, 28, 85, 16));
        label_47->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_12 = new QELabel(page_4);
        qelabel_12->setObjectName(QString::fromUtf8("qelabel_12"));
        qelabel_12->setGeometry(QRect(92, 28, 58, 16));
        qelabel_12->setAddUnits(false);
        qelabel_12->setProperty("format", QVariant(QELabel::Default));
        qelabel_12->setRadix(10u);
        label_48 = new QLabel(page_4);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(4, 48, 85, 16));
        label_48->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_13 = new QELabel(page_4);
        qelabel_13->setObjectName(QString::fromUtf8("qelabel_13"));
        qelabel_13->setGeometry(QRect(92, 48, 58, 16));
        qelabel_13->setAddUnits(false);
        qelabel_13->setProperty("format", QVariant(QELabel::Default));
        qelabel_13->setRadix(10u);
        label_49 = new QLabel(page_4);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(4, 68, 85, 16));
        label_49->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_14 = new QELabel(page_4);
        qelabel_14->setObjectName(QString::fromUtf8("qelabel_14"));
        qelabel_14->setGeometry(QRect(92, 68, 58, 16));
        qelabel_14->setAddUnits(false);
        qelabel_14->setProperty("format", QVariant(QELabel::Default));
        qelabel_14->setRadix(10u);
        label_50 = new QLabel(page_4);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(4, 88, 85, 16));
        label_50->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_15 = new QELabel(page_4);
        qelabel_15->setObjectName(QString::fromUtf8("qelabel_15"));
        qelabel_15->setGeometry(QRect(92, 88, 61, 16));
        qelabel_15->setAddUnits(false);
        qelabel_15->setProperty("format", QVariant(QELabel::Default));
        qelabel_15->setRadix(10u);
        label_51 = new QLabel(page_4);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(4, 108, 85, 16));
        label_51->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_16 = new QELabel(page_4);
        qelabel_16->setObjectName(QString::fromUtf8("qelabel_16"));
        qelabel_16->setGeometry(QRect(92, 108, 58, 16));
        qelabel_16->setAddUnits(false);
        qelabel_16->setProperty("format", QVariant(QELabel::Default));
        qelabel_16->setRadix(10u);
        label_52 = new QLabel(page_4);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(4, 128, 85, 16));
        label_52->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_17 = new QELabel(page_4);
        qelabel_17->setObjectName(QString::fromUtf8("qelabel_17"));
        qelabel_17->setGeometry(QRect(92, 128, 58, 16));
        qelabel_17->setAddUnits(false);
        qelabel_17->setProperty("format", QVariant(QELabel::UnsignedInteger));
        qelabel_17->setRadix(16u);
        label_53 = new QLabel(page_4);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(4, 148, 85, 16));
        label_53->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_18 = new QELabel(page_4);
        qelabel_18->setObjectName(QString::fromUtf8("qelabel_18"));
        qelabel_18->setGeometry(QRect(92, 148, 58, 16));
        qelabel_18->setAddUnits(false);
        qelabel_18->setProperty("format", QVariant(QELabel::Default));
        qelabel_18->setRadix(10u);
        label_54 = new QLabel(page_4);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(4, 168, 85, 16));
        label_54->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelabel_19 = new QELabel(page_4);
        qelabel_19->setObjectName(QString::fromUtf8("qelabel_19"));
        qelabel_19->setGeometry(QRect(92, 168, 58, 16));
        qelabel_19->setAddUnits(false);
        qelabel_19->setProperty("format", QVariant(QELabel::Default));
        qelabel_19->setRadix(10u);
        qelabel_20 = new QELabel(page_4);
        qelabel_20->setObjectName(QString::fromUtf8("qelabel_20"));
        qelabel_20->setGeometry(QRect(92, 188, 58, 16));
        qelabel_20->setAddUnits(false);
        qelabel_20->setProperty("format", QVariant(QELabel::Default));
        qelabel_20->setRadix(10u);
        label_55 = new QLabel(page_4);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(4, 188, 85, 16));
        label_55->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_56 = new QLabel(page_4);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(4, 212, 85, 20));
        label_56->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_29 = new QELineEdit(page_4);
        qelineedit_29->setObjectName(QString::fromUtf8("qelineedit_29"));
        qelineedit_29->setGeometry(QRect(96, 212, 41, 20));
        qelineedit_29->setAddUnits(false);
        qelineedit_30 = new QELineEdit(page_4);
        qelineedit_30->setObjectName(QString::fromUtf8("qelineedit_30"));
        qelineedit_30->setGeometry(QRect(216, 212, 185, 20));
        qelineedit_30->setAddUnits(false);
        label_57 = new QLabel(page_4);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(148, 212, 61, 20));
        label_57->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_58 = new QLabel(page_4);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(268, 188, 45, 20));
        label_58->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qecombobox_5 = new QEComboBox(page_4);
        qecombobox_5->setObjectName(QString::fromUtf8("qecombobox_5"));
        qecombobox_5->setGeometry(QRect(316, 188, 85, 20));
        bytemonitor = new ByteMonitor(page_4);
        bytemonitor->setObjectName(QString::fromUtf8("bytemonitor"));
        bytemonitor->setGeometry(QRect(188, 24, 16, 114));
        sizePolicy.setHeightForWidth(bytemonitor->sizePolicy().hasHeightForWidth());
        bytemonitor->setSizePolicy(sizePolicy);
        bytemonitor->setProperty("nbits", QVariant(8u));
        label_65 = new QLabel(page_4);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(208, 26, 57, 12));
        sizePolicy.setHeightForWidth(label_65->sizePolicy().hasHeightForWidth());
        label_65->setSizePolicy(sizePolicy);
        QFont font2;
        font2.setPointSize(8);
        label_65->setFont(font2);
        label_70 = new QLabel(page_4);
        label_70->setObjectName(QString::fromUtf8("label_70"));
        label_70->setGeometry(QRect(208, 124, 57, 12));
        sizePolicy.setHeightForWidth(label_70->sizePolicy().hasHeightForWidth());
        label_70->setSizePolicy(sizePolicy);
        label_70->setFont(font2);
        label_72 = new QLabel(page_4);
        label_72->setObjectName(QString::fromUtf8("label_72"));
        label_72->setGeometry(QRect(208, 110, 57, 12));
        sizePolicy.setHeightForWidth(label_72->sizePolicy().hasHeightForWidth());
        label_72->setSizePolicy(sizePolicy);
        label_72->setFont(font2);
        label_74 = new QLabel(page_4);
        label_74->setObjectName(QString::fromUtf8("label_74"));
        label_74->setGeometry(QRect(208, 82, 57, 12));
        sizePolicy.setHeightForWidth(label_74->sizePolicy().hasHeightForWidth());
        label_74->setSizePolicy(sizePolicy);
        label_74->setFont(font2);
        label_76 = new QLabel(page_4);
        label_76->setObjectName(QString::fromUtf8("label_76"));
        label_76->setGeometry(QRect(208, 68, 57, 12));
        sizePolicy.setHeightForWidth(label_76->sizePolicy().hasHeightForWidth());
        label_76->setSizePolicy(sizePolicy);
        label_76->setFont(font2);
        label_77 = new QLabel(page_4);
        label_77->setObjectName(QString::fromUtf8("label_77"));
        label_77->setGeometry(QRect(208, 54, 57, 12));
        sizePolicy.setHeightForWidth(label_77->sizePolicy().hasHeightForWidth());
        label_77->setSizePolicy(sizePolicy);
        label_77->setFont(font2);
        label_78 = new QLabel(page_4);
        label_78->setObjectName(QString::fromUtf8("label_78"));
        label_78->setGeometry(QRect(208, 40, 57, 12));
        sizePolicy.setHeightForWidth(label_78->sizePolicy().hasHeightForWidth());
        label_78->setSizePolicy(sizePolicy);
        label_78->setFont(font2);
        bytemonitor_2 = new ByteMonitor(page_4);
        bytemonitor_2->setObjectName(QString::fromUtf8("bytemonitor_2"));
        bytemonitor_2->setGeometry(QRect(284, 24, 16, 114));
        bytemonitor_2->setProperty("nbits", QVariant(8u));
        bytemonitor_2->setProperty("firstbit", QVariant(8u));
        label_66 = new QLabel(page_4);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(304, 26, 57, 12));
        label_66->setFont(font2);
        label_79 = new QLabel(page_4);
        label_79->setObjectName(QString::fromUtf8("label_79"));
        label_79->setGeometry(QRect(304, 110, 60, 12));
        label_79->setFont(font2);
        label_71 = new QLabel(page_4);
        label_71->setObjectName(QString::fromUtf8("label_71"));
        label_71->setGeometry(QRect(304, 124, 72, 12));
        label_71->setFont(font2);
        label_80 = new QLabel(page_4);
        label_80->setObjectName(QString::fromUtf8("label_80"));
        label_80->setGeometry(QRect(304, 96, 57, 12));
        label_80->setFont(font2);
        label_81 = new QLabel(page_4);
        label_81->setObjectName(QString::fromUtf8("label_81"));
        label_81->setGeometry(QRect(304, 68, 72, 12));
        label_81->setFont(font2);
        label_82 = new QLabel(page_4);
        label_82->setObjectName(QString::fromUtf8("label_82"));
        label_82->setGeometry(QRect(304, 54, 57, 12));
        label_82->setFont(font2);
        label_83 = new QLabel(page_4);
        label_83->setObjectName(QString::fromUtf8("label_83"));
        label_83->setGeometry(QRect(304, 82, 80, 12));
        label_83->setFont(font2);
        label_84 = new QLabel(page_4);
        label_84->setObjectName(QString::fromUtf8("label_84"));
        label_84->setGeometry(QRect(304, 40, 57, 12));
        label_84->setFont(font2);
        label_75 = new QLabel(page_4);
        label_75->setObjectName(QString::fromUtf8("label_75"));
        label_75->setGeometry(QRect(208, 96, 57, 12));
        sizePolicy.setHeightForWidth(label_75->sizePolicy().hasHeightForWidth());
        label_75->setSizePolicy(sizePolicy);
        label_75->setFont(font2);
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName(QString::fromUtf8("page_5"));
        label_7 = new QLabel(page_5);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(4, 4, 69, 16));
        label_59 = new QLabel(page_5);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(88, 40, 33, 22));
        label_59->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_60 = new QLabel(page_5);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(88, 68, 33, 22));
        label_60->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_61 = new QLabel(page_5);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(88, 96, 33, 22));
        label_61->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qecombobox_6 = new QEComboBox(page_5);
        qecombobox_6->setObjectName(QString::fromUtf8("qecombobox_6"));
        qecombobox_6->setGeometry(QRect(124, 40, 74, 22));
        qecombobox_7 = new QEComboBox(page_5);
        qecombobox_7->setObjectName(QString::fromUtf8("qecombobox_7"));
        qecombobox_7->setGeometry(QRect(124, 96, 74, 22));
        qecombobox_8 = new QEComboBox(page_5);
        qecombobox_8->setObjectName(QString::fromUtf8("qecombobox_8"));
        qecombobox_8->setGeometry(QRect(124, 128, 73, 22));
        qelineedit_31 = new QELineEdit(page_5);
        qelineedit_31->setObjectName(QString::fromUtf8("qelineedit_31"));
        qelineedit_31->setGeometry(QRect(124, 68, 110, 22));
        qelineedit_31->setAddUnits(false);
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName(QString::fromUtf8("page_6"));
        label_8 = new QLabel(page_6);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(4, 4, 57, 15));
        label_62 = new QLabel(page_6);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(64, 36, 81, 20));
        label_62->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_63 = new QLabel(page_6);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(64, 64, 81, 20));
        label_63->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_64 = new QLabel(page_6);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(64, 92, 81, 20));
        label_64->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        qelineedit_32 = new QELineEdit(page_6);
        qelineedit_32->setObjectName(QString::fromUtf8("qelineedit_32"));
        qelineedit_32->setGeometry(QRect(148, 36, 80, 20));
        qelineedit_32->setAddUnits(false);
        qelineedit_33 = new QELineEdit(page_6);
        qelineedit_33->setObjectName(QString::fromUtf8("qelineedit_33"));
        qelineedit_33->setGeometry(QRect(148, 64, 80, 20));
        qelineedit_33->setAddUnits(false);
        qelineedit_34 = new QELineEdit(page_6);
        qelineedit_34->setObjectName(QString::fromUtf8("qelineedit_34"));
        qelineedit_34->setGeometry(QRect(148, 92, 80, 20));
        qelineedit_34->setAddUnits(false);
        stackedWidget->addWidget(page_6);
        groupBox = new QGroupBox(MotorDetails);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(4, 4, 513, 49));
        qelabel = new QELabel(groupBox);
        qelabel->setObjectName(QString::fromUtf8("qelabel"));
        qelabel->setGeometry(QRect(8, 8, 100, 16));
        QFont font3;
        font3.setPointSize(10);
        font3.setBold(true);
        font3.setWeight(75);
        qelabel->setFont(font3);
        qelabel_2 = new QELabel(groupBox);
        qelabel_2->setObjectName(QString::fromUtf8("qelabel_2"));
        qelabel_2->setGeometry(QRect(8, 28, 100, 16));
        qelabel_2->setFont(font3);
        qelabel_3 = new QELabel(groupBox);
        qelabel_3->setObjectName(QString::fromUtf8("qelabel_3"));
        qelabel_3->setGeometry(QRect(216, 8, 85, 16));
        qelabel_3->setFont(font3);
        label = new QLabel(groupBox);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(216, 28, 38, 16));
        label->setFont(font3);
        qelabel_4 = new QELabel(groupBox);
        qelabel_4->setObjectName(QString::fromUtf8("qelabel_4"));
        qelabel_4->setGeometry(QRect(254, 28, 48, 16));
        qelabel_4->setFont(font3);
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(336, 28, 58, 16));
        label_2->setFont(font3);
        qelabel_5 = new QELabel(groupBox);
        qelabel_5->setObjectName(QString::fromUtf8("qelabel_5"));
        qelabel_5->setGeometry(QRect(394, 28, 33, 16));
        qelabel_5->setFont(font3);
        qelabel_5->setAddUnits(false);
        pushButton = new QPushButton(groupBox);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(448, 12, 48, 26));

        retranslateUi(MotorDetails);
        QObject::connect(pushButton, SIGNAL(clicked(bool)), MotorDetails, SLOT(close()));
        QObject::connect(listWidget, SIGNAL(currentRowChanged(int)), stackedWidget, SLOT(setCurrentIndex(int)));

        stackedWidget->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(MotorDetails);
    } // setupUi

    void retranslateUi(QDialog *MotorDetails)
    {
        MotorDetails->setWindowTitle(QApplication::translate("MotorDetails", "Dialog", 0, QApplication::UnicodeUTF8));

        const bool __sortingEnabled = listWidget->isSortingEnabled();
        listWidget->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem = listWidget->item(0);
        ___qlistwidgetitem->setText(QApplication::translate("MotorDetails", "Drive", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem1 = listWidget->item(1);
        ___qlistwidgetitem1->setText(QApplication::translate("MotorDetails", "Dynamics", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem2 = listWidget->item(2);
        ___qlistwidgetitem2->setText(QApplication::translate("MotorDetails", "Resolution", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem3 = listWidget->item(3);
        ___qlistwidgetitem3->setText(QApplication::translate("MotorDetails", "Status", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem4 = listWidget->item(4);
        ___qlistwidgetitem4->setText(QApplication::translate("MotorDetails", "Calibration", 0, QApplication::UnicodeUTF8));
        QListWidgetItem *___qlistwidgetitem5 = listWidget->item(5);
        ___qlistwidgetitem5->setText(QApplication::translate("MotorDetails", "Servo", 0, QApplication::UnicodeUTF8));
        listWidget->setSortingEnabled(__sortingEnabled);

        label_3->setText(QApplication::translate("MotorDetails", "Drive", 0, QApplication::UnicodeUTF8));
        qelineedit->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).HLM", 0, QApplication::UnicodeUTF8)));
        qelineedit->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_9->setText(QApplication::translate("MotorDetails", "Hi Limit", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("MotorDetails", "Lo Limit", 0, QApplication::UnicodeUTF8));
        qelineedit_2->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).LLM", 0, QApplication::UnicodeUTF8)));
        qelineedit_2->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_3->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).DHLM", 0, QApplication::UnicodeUTF8)));
        qelineedit_3->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_4->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).DLLM", 0, QApplication::UnicodeUTF8)));
        qelineedit_4->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_11->setText(QApplication::translate("MotorDetails", "User", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("MotorDetails", "Dial", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("MotorDetails", "Raw", 0, QApplication::UnicodeUTF8));
        qecombobox->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).SPMG", 0, QApplication::UnicodeUTF8)));
        qecombobox->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_14->setText(QApplication::translate("MotorDetails", "Readback", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("MotorDetails", "Move Abs", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("MotorDetails", "Move Rel", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("MotorDetails", "Tweek", 0, QApplication::UnicodeUTF8));
        qelabel_6->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).RBV", 0, QApplication::UnicodeUTF8)));
        qelabel_6->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelabel_7->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).DRBV", 0, QApplication::UnicodeUTF8)));
        qelabel_7->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_5->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).VAL", 0, QApplication::UnicodeUTF8)));
        qelineedit_5->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_6->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).DVAL", 0, QApplication::UnicodeUTF8)));
        qelineedit_6->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_7->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).RVAL", 0, QApplication::UnicodeUTF8)));
        qelineedit_7->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelabel_8->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).RRBV", 0, QApplication::UnicodeUTF8)));
        qelabel_8->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_8->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).RLV", 0, QApplication::UnicodeUTF8)));
        qelineedit_8->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        tweekReverse->setText(QApplication::translate("MotorDetails", "-", 0, QApplication::UnicodeUTF8));
        tweekReverse->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).TWR", 0, QApplication::UnicodeUTF8)));
        tweekReverse->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        tweekForward->setText(QApplication::translate("MotorDetails", "+", 0, QApplication::UnicodeUTF8));
        tweekForward->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).TWR", 0, QApplication::UnicodeUTF8)));
        tweekForward->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        homeReverse->setText(QApplication::translate("MotorDetails", "HomR", 0, QApplication::UnicodeUTF8));
        homeReverse->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).HOMR", 0, QApplication::UnicodeUTF8)));
        homeReverse->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        homeForward->setText(QApplication::translate("MotorDetails", "HomF", 0, QApplication::UnicodeUTF8));
        homeForward->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).HOMF", 0, QApplication::UnicodeUTF8)));
        homeForward->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        jogReverse->setText(QApplication::translate("MotorDetails", "JogR", 0, QApplication::UnicodeUTF8));
        jogReverse->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).JOGR", 0, QApplication::UnicodeUTF8)));
        jogReverse->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        jogForward->setText(QApplication::translate("MotorDetails", "JogF", 0, QApplication::UnicodeUTF8));
        jogForward->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).JOGF", 0, QApplication::UnicodeUTF8)));
        jogForward->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_9->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).RLV", 0, QApplication::UnicodeUTF8)));
        qelineedit_9->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_4->setText(QApplication::translate("MotorDetails", "Dynamics", 0, QApplication::UnicodeUTF8));
        groupBoxNormal->setTitle(QApplication::translate("MotorDetails", "Normal", 0, QApplication::UnicodeUTF8));
        qelineedit_10->setText(QApplication::translate("MotorDetails", "0.000", 0, QApplication::UnicodeUTF8));
        qelineedit_10->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).VMAX", 0, QApplication::UnicodeUTF8)));
        qelineedit_10->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_11->setText(QApplication::translate("MotorDetails", "2.000", 0, QApplication::UnicodeUTF8));
        qelineedit_11->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).VELO", 0, QApplication::UnicodeUTF8)));
        qelineedit_11->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_12->setText(QApplication::translate("MotorDetails", "0.000", 0, QApplication::UnicodeUTF8));
        qelineedit_12->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).VBAS", 0, QApplication::UnicodeUTF8)));
        qelineedit_12->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_13->setText(QApplication::translate("MotorDetails", "1.000", 0, QApplication::UnicodeUTF8));
        qelineedit_13->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).ACCL", 0, QApplication::UnicodeUTF8)));
        qelineedit_13->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        groupBoxBack->setTitle(QApplication::translate("MotorDetails", "Backlash", 0, QApplication::UnicodeUTF8));
        qelineedit_14->setText(QApplication::translate("MotorDetails", "1.000", 0, QApplication::UnicodeUTF8));
        qelineedit_14->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).BVEL", 0, QApplication::UnicodeUTF8)));
        qelineedit_14->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_15->setText(QApplication::translate("MotorDetails", "0.200", 0, QApplication::UnicodeUTF8));
        qelineedit_15->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).BACC", 0, QApplication::UnicodeUTF8)));
        qelineedit_15->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_16->setText(QApplication::translate("MotorDetails", "0.000", 0, QApplication::UnicodeUTF8));
        qelineedit_16->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).BDST", 0, QApplication::UnicodeUTF8)));
        qelineedit_16->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_17->setText(QApplication::translate("MotorDetails", "1.000", 0, QApplication::UnicodeUTF8));
        qelineedit_17->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).FRAC", 0, QApplication::UnicodeUTF8)));
        qelineedit_17->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        groupBoxJog->setTitle(QApplication::translate("MotorDetails", "Jog", 0, QApplication::UnicodeUTF8));
        qelineedit_18->setText(QApplication::translate("MotorDetails", "2.000", 0, QApplication::UnicodeUTF8));
        qelineedit_18->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).JVEL", 0, QApplication::UnicodeUTF8)));
        qelineedit_18->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_19->setText(QApplication::translate("MotorDetails", "2.000", 0, QApplication::UnicodeUTF8));
        qelineedit_19->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).JVEL", 0, QApplication::UnicodeUTF8)));
        qelineedit_19->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_18->setText(QApplication::translate("MotorDetails", "Max Speed", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("MotorDetails", "Speed", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("MotorDetails", "Base Speed", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("MotorDetails", "Acceleration", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("MotorDetails", "Backlash Dis", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("MotorDetails", "Move Fractio", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("MotorDetails", "EGU/s", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("MotorDetails", "EGU/s", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("MotorDetails", "EGU/s", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("MotorDetails", "EGU/s/s", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("MotorDetails", "EGU", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("MotorDetails", "Resolution", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("MotorDetails", "Motor Resolution", 0, QApplication::UnicodeUTF8));
        qelineedit_20->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).MRES", 0, QApplication::UnicodeUTF8)));
        qelineedit_20->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_30->setText(QApplication::translate("MotorDetails", "EGU/step", 0, QApplication::UnicodeUTF8));
        qelineedit_21->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).ERES", 0, QApplication::UnicodeUTF8)));
        qelineedit_21->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_31->setText(QApplication::translate("MotorDetails", "Encoder Resolu.", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("MotorDetails", "EGU/step", 0, QApplication::UnicodeUTF8));
        qelineedit_22->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).RRES", 0, QApplication::UnicodeUTF8)));
        qelineedit_22->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_33->setText(QApplication::translate("MotorDetails", "Readback Resol.", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("MotorDetails", "EGU/step", 0, QApplication::UnicodeUTF8));
        qelineedit_23->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).RDBD", 0, QApplication::UnicodeUTF8)));
        qelineedit_23->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_35->setText(QApplication::translate("MotorDetails", "Retry Deadband", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("MotorDetails", "EGU", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("MotorDetails", "Retries Max", 0, QApplication::UnicodeUTF8));
        qelineedit_24->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).RTRY", 0, QApplication::UnicodeUTF8)));
        qelineedit_24->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelabel_9->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).RCNT", 0, QApplication::UnicodeUTF8)));
        qelabel_9->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qecombobox_2->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).UEIP", 0, QApplication::UnicodeUTF8)));
        qecombobox_2->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_38->setText(QApplication::translate("MotorDetails", "Use Encoder", 0, QApplication::UnicodeUTF8));
        qecombobox_3->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).URIP", 0, QApplication::UnicodeUTF8)));
        qecombobox_3->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_39->setText(QApplication::translate("MotorDetails", "Use Readback", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("MotorDetails", "Readback Dlelay", 0, QApplication::UnicodeUTF8));
        qelineedit_25->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).RTRY", 0, QApplication::UnicodeUTF8)));
        qelineedit_25->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_41->setText(QApplication::translate("MotorDetails", "sec", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("MotorDetails", "RBV Link", 0, QApplication::UnicodeUTF8));
        qelineedit_26->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).RDBL", 0, QApplication::UnicodeUTF8)));
        qelineedit_26->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_43->setText(QApplication::translate("MotorDetails", "Pre-move string", 0, QApplication::UnicodeUTF8));
        qelineedit_27->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).PREM", 0, QApplication::UnicodeUTF8)));
        qelineedit_27->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_44->setText(QApplication::translate("MotorDetails", "Post-move string", 0, QApplication::UnicodeUTF8));
        qelineedit_28->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).POST", 0, QApplication::UnicodeUTF8)));
        qelineedit_28->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_45->setText(QApplication::translate("MotorDetails", "Mode", 0, QApplication::UnicodeUTF8));
        qecombobox_4->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).OMSL", 0, QApplication::UnicodeUTF8)));
        qecombobox_4->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_6->setText(QApplication::translate("MotorDetails", "Status", 0, QApplication::UnicodeUTF8));
        qelabel_10->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).STAT", 0, QApplication::UnicodeUTF8)));
        qelabel_10->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_46->setText(QApplication::translate("MotorDetails", "State 0x", 0, QApplication::UnicodeUTF8));
        qelabel_11->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).MSTA", 0, QApplication::UnicodeUTF8)));
        qelabel_11->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_47->setText(QApplication::translate("MotorDetails", "Current Dir", 0, QApplication::UnicodeUTF8));
        qelabel_12->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).TDIR", 0, QApplication::UnicodeUTF8)));
        qelabel_12->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_48->setText(QApplication::translate("MotorDetails", "Moving", 0, QApplication::UnicodeUTF8));
        qelabel_13->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).MOVN", 0, QApplication::UnicodeUTF8)));
        qelabel_13->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_49->setText(QApplication::translate("MotorDetails", "At Home", 0, QApplication::UnicodeUTF8));
        qelabel_14->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).ATHM", 0, QApplication::UnicodeUTF8)));
        qelabel_14->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_50->setText(QApplication::translate("MotorDetails", "Motor Posit", 0, QApplication::UnicodeUTF8));
        qelabel_15->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).RMP", 0, QApplication::UnicodeUTF8)));
        qelabel_15->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_51->setText(QApplication::translate("MotorDetails", "Encoder Posi", 0, QApplication::UnicodeUTF8));
        qelabel_16->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).REP", 0, QApplication::UnicodeUTF8)));
        qelabel_16->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_52->setText(QApplication::translate("MotorDetails", "MIP 0x", 0, QApplication::UnicodeUTF8));
        qelabel_17->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).MIP", 0, QApplication::UnicodeUTF8)));
        qelabel_17->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_53->setText(QApplication::translate("MotorDetails", "VME Card No.", 0, QApplication::UnicodeUTF8));
        qelabel_18->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).CARD", 0, QApplication::UnicodeUTF8)));
        qelabel_18->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_54->setText(QApplication::translate("MotorDetails", "Error", 0, QApplication::UnicodeUTF8));
        qelabel_19->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).DIFF", 0, QApplication::UnicodeUTF8)));
        qelabel_19->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelabel_20->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).VERS", 0, QApplication::UnicodeUTF8)));
        qelabel_20->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_55->setText(QApplication::translate("MotorDetails", "Version", 0, QApplication::UnicodeUTF8));
        label_56->setText(QApplication::translate("MotorDetails", "Precision", 0, QApplication::UnicodeUTF8));
        qelineedit_29->setText(QApplication::translate("MotorDetails", "3", 0, QApplication::UnicodeUTF8));
        qelineedit_29->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).PREC", 0, QApplication::UnicodeUTF8)));
        qelineedit_29->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_30->setText(QApplication::translate("MotorDetails", "0", 0, QApplication::UnicodeUTF8));
        qelineedit_30->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).FLNK", 0, QApplication::UnicodeUTF8)));
        qelineedit_30->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_57->setText(QApplication::translate("MotorDetails", "FWD Link", 0, QApplication::UnicodeUTF8));
        label_58->setText(QApplication::translate("MotorDetails", "Torque", 0, QApplication::UnicodeUTF8));
        qecombobox_5->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).CNEN", 0, QApplication::UnicodeUTF8)));
        qecombobox_5->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        bytemonitor->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).MSTA", 0, QApplication::UnicodeUTF8)));
        bytemonitor->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_65->setText(QApplication::translate("MotorDetails", "at Home", 0, QApplication::UnicodeUTF8));
        label_70->setText(QApplication::translate("MotorDetails", "direction", 0, QApplication::UnicodeUTF8));
        label_72->setText(QApplication::translate("MotorDetails", "DONE", 0, QApplication::UnicodeUTF8));
        label_74->setText(QApplication::translate("MotorDetails", "Home LS", 0, QApplication::UnicodeUTF8));
        label_76->setText(QApplication::translate("MotorDetails", "not used", 0, QApplication::UnicodeUTF8));
        label_77->setText(QApplication::translate("MotorDetails", "Position", 0, QApplication::UnicodeUTF8));
        label_78->setText(QApplication::translate("MotorDetails", "not used", 0, QApplication::UnicodeUTF8));
        bytemonitor_2->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).MSTA", 0, QApplication::UnicodeUTF8)));
        bytemonitor_2->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_66->setText(QApplication::translate("MotorDetails", "not used", 0, QApplication::UnicodeUTF8));
        label_79->setText(QApplication::translate("MotorDetails", "not Polling", 0, QApplication::UnicodeUTF8));
        label_71->setText(QApplication::translate("MotorDetails", "enc Present", 0, QApplication::UnicodeUTF8));
        label_80->setText(QApplication::translate("MotorDetails", "Moving", 0, QApplication::UnicodeUTF8));
        label_81->setText(QApplication::translate("MotorDetails", "comm Error", 0, QApplication::UnicodeUTF8));
        label_82->setText(QApplication::translate("MotorDetails", "- Lim Sw", 0, QApplication::UnicodeUTF8));
        label_83->setText(QApplication::translate("MotorDetails", "gain support", 0, QApplication::UnicodeUTF8));
        label_84->setText(QApplication::translate("MotorDetails", "not used", 0, QApplication::UnicodeUTF8));
        label_75->setText(QApplication::translate("MotorDetails", "+ Lim Sw", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("MotorDetails", "Calibration", 0, QApplication::UnicodeUTF8));
        label_59->setText(QApplication::translate("MotorDetails", "Cal", 0, QApplication::UnicodeUTF8));
        label_60->setText(QApplication::translate("MotorDetails", "Off", 0, QApplication::UnicodeUTF8));
        label_61->setText(QApplication::translate("MotorDetails", "Dir", 0, QApplication::UnicodeUTF8));
        qecombobox_6->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).SET", 0, QApplication::UnicodeUTF8)));
        qecombobox_6->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qecombobox_7->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).DIR", 0, QApplication::UnicodeUTF8)));
        qecombobox_7->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qecombobox_8->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).FOFF", 0, QApplication::UnicodeUTF8)));
        qecombobox_8->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_31->setText(QApplication::translate("MotorDetails", "0.000", 0, QApplication::UnicodeUTF8));
        qelineedit_31->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).OFF", 0, QApplication::UnicodeUTF8)));
        qelineedit_31->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_8->setText(QApplication::translate("MotorDetails", "Servo", 0, QApplication::UnicodeUTF8));
        label_62->setText(QApplication::translate("MotorDetails", "Proportional", 0, QApplication::UnicodeUTF8));
        label_63->setText(QApplication::translate("MotorDetails", "Integral", 0, QApplication::UnicodeUTF8));
        label_64->setText(QApplication::translate("MotorDetails", "Derivative", 0, QApplication::UnicodeUTF8));
        qelineedit_32->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).PCOF", 0, QApplication::UnicodeUTF8)));
        qelineedit_32->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_33->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).ICOF", 0, QApplication::UnicodeUTF8)));
        qelineedit_33->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelineedit_34->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).DCOF", 0, QApplication::UnicodeUTF8)));
        qelineedit_34->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        groupBox->setTitle(QString());
        qelabel->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).NAME", 0, QApplication::UnicodeUTF8)));
        qelabel->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelabel_2->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).DESC", 0, QApplication::UnicodeUTF8)));
        qelabel_2->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        qelabel_3->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).DTYP", 0, QApplication::UnicodeUTF8)));
        qelabel_3->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label->setText(QApplication::translate("MotorDetails", "EGU:", 0, QApplication::UnicodeUTF8));
        qelabel_4->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).EGU", 0, QApplication::UnicodeUTF8)));
        qelabel_4->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        label_2->setText(QApplication::translate("MotorDetails", "mRec V", 0, QApplication::UnicodeUTF8));
        qelabel_5->setProperty("variable", QVariant(QApplication::translate("MotorDetails", "$(P):$(M).VERS", 0, QApplication::UnicodeUTF8)));
        qelabel_5->setProperty("variableSubstitutions", QVariant(QApplication::translate("MotorDetails", "P=PICO,M=m1", 0, QApplication::UnicodeUTF8)));
        pushButton->setText(QApplication::translate("MotorDetails", "Close", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MotorDetails: public Ui_MotorDetails {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MOTORDETAILS_H
